ARGOBOTS: src/include/abtd_futex.h File Reference
abtd_futex.h File Reference
Data Structures
struct ABTD_futex_multiple
struct ABTD_futex_single
Typedefs
typedef struct ABTD_futex_multiple ABTD_futex_multiple
typedef struct ABTD_futex_single ABTD_futex_single
Functions
static void ABTD_futex_multiple_init (ABTD_futex_multiple *p_futex)
void ABTD_futex_wait_and_unlock (ABTD_futex_multiple *p_futex, ABTD_spinlock *p_lock)
void ABTD_futex_timedwait_and_unlock (ABTD_futex_multiple *p_futex, ABTD_spinlock *p_lock, double wait_time_sec)
void ABTD_futex_broadcast (ABTD_futex_multiple *p_futex)
static void ABTD_futex_single_init (ABTD_futex_single *p_futex)
void ABTD_futex_suspend (ABTD_futex_single *p_futex)
void ABTD_futex_resume (ABTD_futex_single *p_futex)
Typedef Documentation
ABTD_futex_multiple
typedef struct ABTD_futex_multiple ABTD_futex_multiple
Definition at line 13 of file abtd_futex.h.
ABTD_futex_single
typedef struct ABTD_futex_single ABTD_futex_single
Definition at line 37 of file abtd_futex.h.
Function Documentation
ABTD_futex_broadcast()
void ABTD_futex_broadcast (ABTD_futex_multiple * p_futex)
Definition at line 174 of file abtd_futex.c.
Referenced by ABTI_waitlist_broadcast(), and ABTI_waitlist_signal().
ABTD_futex_multiple_init()
static void ABTD_futex_multiple_init (ABTD_futex_multiple * p_futex) inline static
Definition at line 79 of file abtd_futex.h.
Referenced by ABTI_waitlist_init().
ABTD_futex_resume()
void ABTD_futex_resume (ABTD_futex_single * p_futex)
Definition at line 216 of file abtd_futex.c.
Referenced by ABTI_ythread_context_switch_to_child_internal(), and ythread_terminate().
ABTD_futex_single_init()
static void ABTD_futex_single_init (ABTD_futex_single * p_futex) inline static
Definition at line 88 of file abtd_futex.h.
ABTD_futex_suspend()
void ABTD_futex_suspend (ABTD_futex_single * p_futex)
Definition at line 191 of file abtd_futex.c.
ABTD_futex_timedwait_and_unlock()
void ABTD_futex_timedwait_and_unlock (ABTD_futex_multiple * p_futex, ABTD_spinlock * p_lock, double wait_time_sec)
Definition at line 117 of file abtd_futex.c.
Referenced by ABTI_waitlist_wait_timedout_and_unlock().
ABTD_futex_wait_and_unlock()
void ABTD_futex_wait_and_unlock (ABTD_futex_multiple * p_futex, ABTD_spinlock * p_lock)
Definition at line 87 of file abtd_futex.c.
Referenced by ABTI_waitlist_wait_and_unlock().