ARGOBOTS: src/include/abti_mutex.h File Reference
abti_mutex.h File Reference
Functions
static ABTI_mutex * ABTI_mutex_get_ptr (ABT_mutex mutex)
static ABT_mutex ABTI_mutex_get_handle (ABTI_mutex *p_mutex)
static void ABTI_mutex_init (ABTI_mutex *p_mutex)
static void ABTI_mutex_fini (ABTI_mutex *p_mutex)
static void ABTI_mutex_lock_no_recursion (ABTI_local **pp_local, ABTI_mutex *p_mutex)
static void ABTI_mutex_lock (ABTI_local **pp_local, ABTI_mutex *p_mutex)
static int ABTI_mutex_trylock_no_recursion (ABTI_mutex *p_mutex)
static int ABTI_mutex_trylock (ABTI_local *p_local, ABTI_mutex *p_mutex)
static void ABTI_mutex_spinlock_no_recursion (ABTI_mutex *p_mutex)
static void ABTI_mutex_spinlock (ABTI_local *p_local, ABTI_mutex *p_mutex)
static void ABTI_mutex_unlock_no_recursion (ABTI_local *p_local, ABTI_mutex *p_mutex)
static void ABTI_mutex_unlock (ABTI_local *p_local, ABTI_mutex *p_mutex)
Function Documentation
ABTI_mutex_fini()
static void ABTI_mutex_fini (ABTI_mutex * p_mutex) inline static
Definition at line 51 of file abti_mutex.h.
ABTI_mutex_get_handle()
static ABT_mutex ABTI_mutex_get_handle (ABTI_mutex * p_mutex) inline static
Definition at line 24 of file abti_mutex.h.
Referenced by ABT_mutex_create(), ABT_mutex_create_with_attr(), and tool_query().
ABTI_mutex_get_ptr()
static ABTI_mutex* ABTI_mutex_get_ptr (ABT_mutex mutex) inline static
Definition at line 9 of file abti_mutex.h.
Referenced by ABT_cond_timedwait(), ABT_cond_wait(), ABT_mutex_equal(), ABT_mutex_free(), ABT_mutex_get_attr(), ABT_mutex_lock(), ABT_mutex_lock_high(), ABT_mutex_lock_low(), ABT_mutex_spinlock(), ABT_mutex_trylock(), ABT_mutex_unlock(), ABT_mutex_unlock_de(), and ABT_mutex_unlock_se().
ABTI_mutex_init()
static void ABTI_mutex_init (ABTI_mutex * p_mutex) inline static
Definition at line 39 of file abti_mutex.h.
Referenced by ABT_mutex_create(), ABT_mutex_create_with_attr(), and ABT_rwlock_create().
ABTI_mutex_lock()
static void ABTI_mutex_lock (ABTI_local ** pp_local, ABTI_mutex * p_mutex) inline static
Definition at line 98 of file abti_mutex.h.
Referenced by ABT_cond_timedwait(), ABT_mutex_lock(), ABT_mutex_lock_high(), ABT_mutex_lock_low(), ABT_rwlock_rdlock(), ABT_rwlock_unlock(), ABT_rwlock_wrlock(), and ABTI_cond_wait().
ABTI_mutex_lock_no_recursion()
static void ABTI_mutex_lock_no_recursion (ABTI_local ** pp_local, ABTI_mutex * p_mutex) inline static
Definition at line 58 of file abti_mutex.h.
Referenced by ABTI_mutex_lock().
ABTI_mutex_spinlock()
static void ABTI_mutex_spinlock (ABTI_local * p_local, ABTI_mutex * p_mutex) inline static
Definition at line 149 of file abti_mutex.h.
Referenced by ABT_mutex_spinlock().
ABTI_mutex_spinlock_no_recursion()
static void ABTI_mutex_spinlock_no_recursion (ABTI_mutex * p_mutex) inline static
Definition at line 144 of file abti_mutex.h.
Referenced by ABTI_mutex_spinlock().
ABTI_mutex_trylock()
static int ABTI_mutex_trylock (ABTI_local * p_local, ABTI_mutex * p_mutex) inline static
Definition at line 122 of file abti_mutex.h.
Referenced by ABT_mutex_trylock().
ABTI_mutex_trylock_no_recursion()
static int ABTI_mutex_trylock_no_recursion (ABTI_mutex * p_mutex) inline static
Definition at line 116 of file abti_mutex.h.
Referenced by ABTI_mutex_trylock().
ABTI_mutex_unlock()
static void ABTI_mutex_unlock (ABTI_local * p_local, ABTI_mutex * p_mutex) inline static
Definition at line 181 of file abti_mutex.h.
Referenced by ABT_cond_timedwait(), ABT_mutex_unlock(), ABT_mutex_unlock_de(), ABT_mutex_unlock_se(), ABT_rwlock_rdlock(), ABT_rwlock_unlock(), ABT_rwlock_wrlock(), and ABTI_cond_wait().
ABTI_mutex_unlock_no_recursion()
static void ABTI_mutex_unlock_no_recursion (ABTI_local * p_local, ABTI_mutex * p_mutex) inline static
Definition at line 167 of file abti_mutex.h.
Referenced by ABTI_mutex_unlock().