ARGOBOTS: src/include/abti_global.h File Reference
abti_global.h File Reference
Functions
static size_t ABTI_global_get_thread_stacksize (void)
static size_t ABTI_global_get_sched_stacksize (void)
static size_t ABTI_global_get_sched_event_freq (void)
static long ABTI_global_get_sched_sleep_nsec (void)
static ABTI_thread * ABTI_global_get_main (void)
static uint32_t ABTI_global_get_mutex_max_handovers (void)
static uint32_t ABTI_global_get_mutex_max_wakeups (void)
Function Documentation
static ABTI_thread* ABTI_global_get_main (void) inline static
Definition at line 31 of file abti_global.h.
Referenced by ABTI_thread_create_main_sched().
static uint32_t ABTI_global_get_mutex_max_handovers (void) inline static
Definition at line 36 of file abti_global.h.
Referenced by ABT_mutex_attr_create(), and ABTI_mutex_init().
static uint32_t ABTI_global_get_mutex_max_wakeups (void) inline static
Definition at line 41 of file abti_global.h.
Referenced by ABT_mutex_attr_create(), and ABTI_mutex_init().
static size_t ABTI_global_get_sched_event_freq (void) inline static
Definition at line 21 of file abti_global.h.
Referenced by sched_init().
static long ABTI_global_get_sched_sleep_nsec (void) inline static
Definition at line 26 of file abti_global.h.
Referenced by sched_init().
static size_t ABTI_global_get_sched_stacksize (void) inline static
Definition at line 16 of file abti_global.h.
Referenced by ABTI_thread_create_main_sched(), and ABTI_thread_create_sched().
static size_t ABTI_global_get_thread_stacksize (void) inline static
Definition at line 11 of file abti_global.h.
Referenced by ABT_thread_attr_create(), ABT_thread_attr_set_stack(), ABT_thread_attr_set_stacksize(), and ABTI_mem_alloc_thread_default().