ARGOBOTS: src/pool/thread_queue.h File Reference
thread_queue.h File Reference
#include "abti.h"
Data Structures
struct thread_queue_t
Functions
static void thread_queue_init (thread_queue_t *p_queue)
static void thread_queue_free (thread_queue_t *p_queue)
static ABTU_ret_err int thread_queue_acquire_spinlock_if_not_empty (thread_queue_t *p_queue, ABTD_spinlock *p_lock)
static ABT_bool thread_queue_is_empty (const thread_queue_t *p_queue)
static size_t thread_queue_get_size (const thread_queue_t *p_queue)
static void thread_queue_push_head (thread_queue_t *p_queue, ABTI_thread *p_thread)
static void thread_queue_push_tail (thread_queue_t *p_queue, ABTI_thread *p_thread)
static ABTI_thread * thread_queue_pop_head (thread_queue_t *p_queue)
static ABTI_thread * thread_queue_pop_tail (thread_queue_t *p_queue)
static ABTU_ret_err int thread_queue_remove (thread_queue_t *p_queue, ABTI_thread *p_thread)
static void thread_queue_print_all (const thread_queue_t *p_queue, void *arg, void(*print_fn)(void *, ABT_thread))
Function Documentation
thread_queue_acquire_spinlock_if_not_empty()
static ABTU_ret_err int thread_queue_acquire_spinlock_if_not_empty (thread_queue_t * p_queue, ABTD_spinlock * p_lock) inline static
Definition at line 35 of file thread_queue.h.
Referenced by pool_pop_many_shared(), pool_pop_shared(), pool_pop_timedwait(), and pool_pop_wait().
thread_queue_free()
static void thread_queue_free (thread_queue_t * p_queue) inline static
Definition at line 29 of file thread_queue.h.
Referenced by pool_free().
thread_queue_get_size()
static size_t thread_queue_get_size (const thread_queue_t * p_queue) inline static
Definition at line 64 of file thread_queue.h.
Referenced by pool_get_size().
thread_queue_init()
static void thread_queue_init (thread_queue_t * p_queue) inline static
Definition at line 21 of file thread_queue.h.
Referenced by pool_init().
thread_queue_is_empty()
static ABT_bool thread_queue_is_empty (const thread_queue_t * p_queue) inline static
Definition at line 58 of file thread_queue.h.
Referenced by pool_is_empty(), pool_pop(), pool_pop_many(), pool_pop_timedwait(), pool_pop_wait(), and pool_remove().
thread_queue_pop_head()
static ABTI_thread* thread_queue_pop_head (thread_queue_t * p_queue) inline static
Definition at line 115 of file thread_queue.h.
Referenced by pool_pop(), pool_pop_many(), pool_pop_many_private(), pool_pop_many_shared(), pool_pop_private(), pool_pop_shared(), pool_pop_timedwait(), and pool_pop_wait().
thread_queue_pop_tail()
static ABTI_thread* thread_queue_pop_tail (thread_queue_t * p_queue) inline static
Definition at line 140 of file thread_queue.h.
Referenced by pool_pop_many_private(), pool_pop_many_shared(), pool_pop_private(), pool_pop_shared(), and pool_pop_wait().
thread_queue_print_all()
static void thread_queue_print_all (const thread_queue_t * p_queue, void * arg, void(*)(void *, ABT_thread) print_fn) inline static
Definition at line 193 of file thread_queue.h.
Referenced by pool_print_all().
thread_queue_push_head()
static void thread_queue_push_head (thread_queue_t * p_queue, ABTI_thread * p_thread) inline static
Definition at line 69 of file thread_queue.h.
Referenced by pool_push_many_private(), pool_push_many_shared(), pool_push_private(), and pool_push_shared().
thread_queue_push_tail()
static void thread_queue_push_tail (thread_queue_t * p_queue, ABTI_thread * p_thread) inline static
Definition at line 92 of file thread_queue.h.
Referenced by pool_push(), pool_push_many(), pool_push_many_private(), pool_push_many_shared(), pool_push_private(), and pool_push_shared().
thread_queue_remove()
static ABTU_ret_err int thread_queue_remove (thread_queue_t * p_queue, ABTI_thread * p_thread) inline static
Definition at line 165 of file thread_queue.h.
Referenced by pool_remove(), pool_remove_private(), and pool_remove_shared().