ARGOBOTS: src/util/hashtable.c File Reference
hashtable.c File Reference
#include "abti.h"
Functions
static ABTU_hashtable_element * get_element (const ABTU_hashtable *p_hashtable, size_t entry_index)
ABTU_ret_err int ABTU_hashtable_create (size_t num_entries, size_t data_size, ABTU_hashtable **pp_hashtable)
void ABTU_hashtable_free (ABTU_hashtable *p_hashtable)
void ABTU_hashtable_get (const ABTU_hashtable *p_hashtable, int key, void *data, int *found)
ABTU_ret_err int ABTU_hashtable_set (ABTU_hashtable *p_hashtable, int key, const void *data, int *overwritten)
void ABTU_hashtable_delete (ABTU_hashtable *p_hashtable, int key, int *deleted)
Function Documentation
ABTU_hashtable_create()
ABTU_ret_err int ABTU_hashtable_create (size_t num_entries, size_t data_size, ABTU_hashtable ** pp_hashtable)
Definition at line 21 of file hashtable.c.
ABTU_hashtable_delete()
void ABTU_hashtable_delete (ABTU_hashtable * p_hashtable, int key, int * deleted)
Definition at line 144 of file hashtable.c.
ABTU_hashtable_free()
void ABTU_hashtable_free (ABTU_hashtable * p_hashtable)
Definition at line 42 of file hashtable.c.
ABTU_hashtable_get()
void ABTU_hashtable_get (const ABTU_hashtable * p_hashtable, int key, void * data, int * found)
Definition at line 56 of file hashtable.c.
ABTU_hashtable_set()
ABTU_ret_err int ABTU_hashtable_set (ABTU_hashtable * p_hashtable, int key, const void * data, int * overwritten)
Definition at line 91 of file hashtable.c.
get_element()
static ABTU_hashtable_element* get_element (const ABTU_hashtable * p_hashtable, size_t entry_index) inline static
Definition at line 9 of file hashtable.c.
Referenced by ABTU_hashtable_delete(), ABTU_hashtable_free(), and ABTU_hashtable_get().