ARGOBOTS: src/include/abti_pool_user_def.h File Reference
abti_pool_user_def.h File Reference
Functions
static ABTI_pool_user_def * ABTI_pool_user_def_get_ptr (ABT_pool_user_def def)
static ABT_pool_user_def ABTI_pool_user_def_get_handle (ABTI_pool_user_def *p_def)
Function Documentation
ABTI_pool_user_def_get_handle()
static ABT_pool_user_def ABTI_pool_user_def_get_handle (ABTI_pool_user_def * p_def) inline static
Definition at line 28 of file abti_pool_user_def.h.
Referenced by ABT_pool_user_def_create().
ABTI_pool_user_def_get_ptr()
static ABTI_pool_user_def* ABTI_pool_user_def_get_ptr (ABT_pool_user_def def) inline static
Definition at line 12 of file abti_pool_user_def.h.
Referenced by ABT_pool_create(), ABT_pool_user_def_free(), ABT_pool_user_def_set_free(), ABT_pool_user_def_set_get_size(), ABT_pool_user_def_set_init(), ABT_pool_user_def_set_pop_many(), ABT_pool_user_def_set_pop_wait(), ABT_pool_user_def_set_print_all(), and ABT_pool_user_def_set_push_many().