ARGOBOTS: src/include/abti_timer.h File Reference
abti_timer.h File Reference
Functions
static double ABTI_get_wtime (void)
static ABTI_timer * ABTI_timer_get_ptr (ABT_timer timer)
static ABT_timer ABTI_timer_get_handle (ABTI_timer *p_timer)
Function Documentation
static double ABTI_get_wtime (void) inline static
Definition at line 11 of file abti_timer.h.
Referenced by ABT_cond_timedwait(), ABT_get_wtime(), ABTI_info_check_print_all_thread_stacks(), pool_pop_timedwait(), and pool_pop_wait().
static ABT_timer ABTI_timer_get_handle (ABTI_timer * p_timer) inline static
Definition at line 33 of file abti_timer.h.
Referenced by ABT_timer_create(), and ABT_timer_dup().
static ABTI_timer* ABTI_timer_get_ptr (ABT_timer timer) inline static
Definition at line 18 of file abti_timer.h.
Referenced by ABT_timer_dup(), ABT_timer_free(), ABT_timer_read(), ABT_timer_start(), ABT_timer_stop(), ABT_timer_stop_and_add(), and ABT_timer_stop_and_read().