ARGOBOTS: src/include/abti_future.h File Reference
abti_future.h File Reference
Functions
static ABTI_future * ABTI_future_get_ptr (ABT_future future)
static ABT_future ABTI_future_get_handle (ABTI_future *p_future)
Function Documentation
ABTI_future_get_handle()
static ABT_future ABTI_future_get_handle (ABTI_future * p_future) inline static
Definition at line 26 of file abti_future.h.
Referenced by ABT_future_create(), and tool_query().
ABTI_future_get_ptr()
static ABTI_future* ABTI_future_get_ptr (ABT_future future) inline static
Definition at line 11 of file abti_future.h.
Referenced by ABT_future_free(), ABT_future_reset(), ABT_future_set(), ABT_future_test(), and ABT_future_wait().