ARGOBOTS: src/include/abti_waitlist.h File Reference
abti_waitlist.h File Reference
#include "abt_config.h"
Functions
static void ABTI_waitlist_init (ABTI_waitlist *p_waitlist)
static void ABTI_waitlist_wait_and_unlock (ABTI_local **pp_local, ABTI_waitlist *p_waitlist, ABTD_spinlock *p_lock, ABT_sync_event_type sync_event_type, void *p_sync)
static ABT_bool ABTI_waitlist_wait_timedout_and_unlock (ABTI_local **pp_local, ABTI_waitlist *p_waitlist, ABTD_spinlock *p_lock, double target_time, ABT_sync_event_type sync_event_type, void *p_sync)
static void ABTI_waitlist_signal (ABTI_local *p_local, ABTI_waitlist *p_waitlist)
static void ABTI_waitlist_broadcast (ABTI_local *p_local, ABTI_waitlist *p_waitlist)
static ABT_bool ABTI_waitlist_is_empty (ABTI_waitlist *p_waitlist)
Function Documentation
ABTI_waitlist_broadcast()
static void ABTI_waitlist_broadcast (ABTI_local * p_local, ABTI_waitlist * p_waitlist) inline static
Definition at line 246 of file abti_waitlist.h.
Referenced by ABT_barrier_wait(), ABT_future_set(), ABTI_cond_broadcast(), and ABTI_mutex_unlock_no_recursion().
ABTI_waitlist_init()
static void ABTI_waitlist_init (ABTI_waitlist * p_waitlist) inline static
Definition at line 11 of file abti_waitlist.h.
Referenced by ABT_barrier_create(), ABT_eventual_create(), ABT_future_create(), ABTI_cond_init(), and ABTI_mutex_init().
ABTI_waitlist_is_empty()
static ABT_bool ABTI_waitlist_is_empty (ABTI_waitlist * p_waitlist) inline static
Definition at line 282 of file abti_waitlist.h.
Referenced by ABT_cond_free(), ABT_eventual_free(), ABT_future_free(), ABT_future_reset(), and ABTI_cond_fini().
ABTI_waitlist_signal()
static void ABTI_waitlist_signal (ABTI_local * p_local, ABTI_waitlist * p_waitlist) inline static
Definition at line 216 of file abti_waitlist.h.
Referenced by ABT_cond_signal().
ABTI_waitlist_wait_and_unlock()
static void ABTI_waitlist_wait_and_unlock (ABTI_local ** pp_local, ABTI_waitlist * p_waitlist, ABTD_spinlock * p_lock, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 21 of file abti_waitlist.h.
Referenced by ABT_barrier_wait(), ABT_eventual_wait(), ABT_future_wait(), ABTI_cond_wait(), and ABTI_mutex_lock_no_recursion().
ABTI_waitlist_wait_timedout_and_unlock()
static ABT_bool ABTI_waitlist_wait_timedout_and_unlock (ABTI_local ** pp_local, ABTI_waitlist * p_waitlist, ABTD_spinlock * p_lock, double target_time, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 91 of file abti_waitlist.h.
Referenced by ABT_cond_timedwait().