ARGOBOTS: src/include/abti_eventual.h File Reference
abti_eventual.h File Reference
Functions
static ABTI_eventual * ABTI_eventual_get_ptr (ABT_eventual eventual)
static ABT_eventual ABTI_eventual_get_handle (ABTI_eventual *p_eventual)
Function Documentation
ABTI_eventual_get_handle()
static ABT_eventual ABTI_eventual_get_handle (ABTI_eventual * p_eventual) inline static
Definition at line 26 of file abti_eventual.h.
Referenced by ABT_eventual_create(), and tool_query().
ABTI_eventual_get_ptr()
static ABTI_eventual* ABTI_eventual_get_ptr (ABT_eventual eventual) inline static
Definition at line 11 of file abti_eventual.h.
Referenced by ABT_eventual_free(), ABT_eventual_test(), and ABT_eventual_wait().