ARGOBOTS: src/pool/fifo.c File Reference
fifo.c File Reference
#include "abti.h"
#include "thread_queue.h"
#include <time.h>
Data Structures
struct data
Typedefs
typedef struct data data_t
Functions
static int pool_init (ABT_pool pool, ABT_pool_config config)
static void pool_free (ABT_pool pool)
static ABT_bool pool_is_empty (ABT_pool pool)
static size_t pool_get_size (ABT_pool pool)
static void pool_push_shared (ABT_pool pool, ABT_unit unit, ABT_pool_context context)
static void pool_push_private (ABT_pool pool, ABT_unit unit, ABT_pool_context context)
static ABT_thread pool_pop_shared (ABT_pool pool, ABT_pool_context context)
static ABT_thread pool_pop_private (ABT_pool pool, ABT_pool_context context)
static ABT_thread pool_pop_wait (ABT_pool pool, double time_secs, ABT_pool_context context)
static void pool_push_many_shared (ABT_pool pool, const ABT_unit *units, size_t num_units, ABT_pool_context context)
static void pool_push_many_private (ABT_pool pool, const ABT_unit *units, size_t num_units, ABT_pool_context context)
static void pool_pop_many_shared (ABT_pool pool, ABT_thread *threads, size_t max_threads, size_t *num_popped, ABT_pool_context context)
static void pool_pop_many_private (ABT_pool pool, ABT_thread *threads, size_t max_threads, size_t *num_popped, ABT_pool_context context)
static void pool_print_all (ABT_pool pool, void *arg, void(*print_fn)(void *, ABT_thread))
static ABT_unit pool_create_unit (ABT_pool pool, ABT_thread thread)
static void pool_free_unit (ABT_pool pool, ABT_unit unit)
static int pool_remove_shared (ABT_pool pool, ABT_unit unit)
static int pool_remove_private (ABT_pool pool, ABT_unit unit)
static ABT_unit pool_pop_timedwait (ABT_pool pool, double abstime_secs)
static ABT_bool pool_unit_is_in_pool (ABT_unit unit)
static data_t * pool_get_data_ptr (void *p_data)
ABTU_ret_err int ABTI_pool_get_fifo_def (ABT_pool_access access, ABTI_pool_required_def *p_required_def, ABTI_pool_optional_def *p_optional_def, ABTI_pool_deprecated_def *p_deprecated_def)
Typedef Documentation
data_t
typedef struct data data_t
Definition at line 49 of file fifo.c.
Function Documentation
ABTI_pool_get_fifo_def()
ABTU_ret_err int ABTI_pool_get_fifo_def (ABT_pool_access access, ABTI_pool_required_def * p_required_def, ABTI_pool_optional_def * p_optional_def, ABTI_pool_deprecated_def * p_deprecated_def)
Definition at line 58 of file fifo.c.
Referenced by ABTI_pool_create_basic().
pool_create_unit()
static ABT_unit pool_create_unit (ABT_pool pool, ABT_thread thread) static
Definition at line 365 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_free()
static void pool_free (ABT_pool pool) static
Definition at line 128 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_free_unit()
static void pool_free_unit (ABT_pool pool, ABT_unit unit) static
Definition at line 372 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_get_data_ptr()
static data_t* pool_get_data_ptr (void * p_data) inline static
Definition at line 51 of file fifo.c.
Referenced by pool_free(), pool_get_size(), pool_is_empty(), pool_pop_many_private(), pool_pop_many_shared(), pool_pop_private(), pool_pop_shared(), pool_pop_timedwait(), pool_pop_wait(), pool_print_all(), pool_push_many_private(), pool_push_many_shared(), pool_push_private(), pool_push_shared(), pool_remove_private(), and pool_remove_shared().
pool_get_size()
static size_t pool_get_size (ABT_pool pool) static
Definition at line 143 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_init()
static int pool_init (ABT_pool pool, ABT_pool_config config) static
Definition at line 106 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_is_empty()
static ABT_bool pool_is_empty (ABT_pool pool) static
Definition at line 136 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_pop_many_private()
static void pool_pop_many_private (ABT_pool pool, ABT_thread * threads, size_t max_threads, size_t * num_popped, ABT_pool_context context) static
Definition at line 303 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_pop_many_shared()
static void pool_pop_many_shared (ABT_pool pool, ABT_thread * threads, size_t max_threads, size_t * num_popped, ABT_pool_context context) static
Definition at line 279 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_pop_private()
static ABT_thread pool_pop_private (ABT_pool pool, ABT_pool_context context) static
Definition at line 270 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_pop_shared()
static ABT_thread pool_pop_shared (ABT_pool pool, ABT_pool_context context) static
Definition at line 255 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_pop_timedwait()
static ABT_unit pool_pop_timedwait (ABT_pool pool, double abstime_secs) static
Definition at line 233 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_pop_wait()
static ABT_thread pool_pop_wait (ABT_pool pool, double time_secs, ABT_pool_context context) static
Definition at line 204 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_print_all()
static void pool_print_all (ABT_pool pool, void * arg, void(*)(void *, ABT_thread) print_fn) static
Definition at line 339 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_push_many_private()
static void pool_push_many_private (ABT_pool pool, const ABT_unit * units, size_t num_units, ABT_pool_context context) static
Definition at line 190 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_push_many_shared()
static void pool_push_many_shared (ABT_pool pool, const ABT_unit * units, size_t num_units, ABT_pool_context context) static
Definition at line 172 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_push_private()
static void pool_push_private (ABT_pool pool, ABT_unit unit, ABT_pool_context context) static
Definition at line 162 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_push_shared()
static void pool_push_shared (ABT_pool pool, ABT_unit unit, ABT_pool_context context) static
Definition at line 150 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_remove_private()
static int pool_remove_private (ABT_pool pool, ABT_unit unit) static
Definition at line 331 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_remove_shared()
static int pool_remove_shared (ABT_pool pool, ABT_unit unit) static
Definition at line 320 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().
pool_unit_is_in_pool()
static ABT_bool pool_unit_is_in_pool (ABT_unit unit) static
Definition at line 358 of file fifo.c.
Referenced by ABTI_pool_get_fifo_def().