ARGOBOTS: src/include/abtd_ythread.h File Reference
abtd_ythread.h File Reference
Macros
#define ABT_API_PRIVATE
Functions
void ABTD_ythread_func_wrapper (void *p_arg)
void ABTD_ythread_terminate_no_arg (void)
static void ABTD_ythread_context_create (ABTD_ythread_context *p_link, size_t stacksize, void *p_stack, ABTD_ythread_context *p_newctx)
static void ABTD_ythread_context_invalidate (ABTD_ythread_context *p_newctx)
static void ABTD_ythread_context_init (ABTD_ythread_context *p_link, ABTD_ythread_context *p_newctx)
static void ABTD_ythread_context_arm_ythread (size_t stacksize, void *p_stack, ABTD_ythread_context *p_newctx)
static void ABTD_ythread_context_switch (ABTD_ythread_context *p_old, ABTD_ythread_context *p_new)
static ABTU_noreturn void ABTD_ythread_finish_context (ABTD_ythread_context *p_old, ABTD_ythread_context *p_new)
static void ABTD_ythread_context_make_and_call (ABTD_ythread_context *p_old, void(*f_thread)(void *), void *p_arg, void *p_stacktop)
static ABT_bool ABTD_ythread_context_is_dynamic_promoted (ABTD_ythread_context *p_ctx)
static void ABTDI_ythread_context_dynamic_promote (void *p_stacktop, void *jump_f)
static void ABTD_ythread_context_dynamic_promote_ythread (void *p_stacktop)
Macro Definition Documentation
ABT_API_PRIVATE
#define ABT_API_PRIVATE
Definition at line 12 of file abtd_ythread.h.
Function Documentation
ABTD_ythread_context_arm_ythread()
static void ABTD_ythread_context_arm_ythread (size_t stacksize, void * p_stack, ABTD_ythread_context * p_newctx) inline static
Definition at line 55 of file abtd_ythread.h.
Referenced by ABTI_ythread_context_switch_to_sibling_internal().
ABTD_ythread_context_create()
static void ABTD_ythread_context_create (ABTD_ythread_context * p_link, size_t stacksize, void * p_stack, ABTD_ythread_context * p_newctx) inline static
Definition at line 20 of file abtd_ythread.h.
Referenced by ABTI_thread_revive(), and ythread_create().
ABTD_ythread_context_dynamic_promote_ythread()
static void ABTD_ythread_context_dynamic_promote_ythread (void * p_stacktop) inline static
Definition at line 114 of file abtd_ythread.h.
Referenced by ABTI_ythread_dynamic_promote_ythread().
ABTD_ythread_context_init()
static void ABTD_ythread_context_init (ABTD_ythread_context * p_link, ABTD_ythread_context * p_newctx) inline static
Definition at line 47 of file abtd_ythread.h.
Referenced by ythread_create().
ABTD_ythread_context_invalidate()
static void ABTD_ythread_context_invalidate (ABTD_ythread_context * p_newctx) inline static
Definition at line 34 of file abtd_ythread.h.
Referenced by ythread_create().
ABTD_ythread_context_is_dynamic_promoted()
static ABT_bool ABTD_ythread_context_is_dynamic_promoted (ABTD_ythread_context * p_ctx) inline static
Definition at line 96 of file abtd_ythread.h.
Referenced by ABTI_ythread_is_dynamic_promoted().
ABTD_ythread_context_make_and_call()
static void ABTD_ythread_context_make_and_call (ABTD_ythread_context * p_old, void(*)(void *) f_thread, void * p_arg, void * p_stacktop) inline static
Definition at line 88 of file abtd_ythread.h.
Referenced by ABTI_ythread_context_switch_to_child_internal().
ABTD_ythread_context_switch()
static void ABTD_ythread_context_switch (ABTD_ythread_context * p_old, ABTD_ythread_context * p_new) inline static
Definition at line 73 of file abtd_ythread.h.
Referenced by ABTI_ythread_context_switch_to_child_internal(), ABTI_ythread_context_switch_to_parent_internal(), and ABTI_ythread_context_switch_to_sibling_internal().
ABTD_ythread_finish_context()
static ABTU_noreturn void ABTD_ythread_finish_context (ABTD_ythread_context * p_old, ABTD_ythread_context * p_new) inline static
Definition at line 80 of file abtd_ythread.h.
Referenced by ABTI_ythread_context_switch_to_parent_internal(), and ABTI_ythread_context_switch_to_sibling_internal().
ABTD_ythread_func_wrapper()
void ABTD_ythread_func_wrapper (void * p_arg)
Definition at line 11 of file abtd_ythread.c.
Referenced by ABTD_ythread_context_arm_ythread(), and ABTD_ythread_context_create().
ABTD_ythread_terminate_no_arg()
void ABTD_ythread_terminate_no_arg (void)
Definition at line 100 of file abtd_ythread.c.
Referenced by ABTD_ythread_context_dynamic_promote_ythread().
ABTDI_ythread_context_dynamic_promote()
static void ABTDI_ythread_context_dynamic_promote (void * p_stacktop, void * jump_f) inline static
Definition at line 103 of file abtd_ythread.h.
Referenced by ABTD_ythread_context_dynamic_promote_ythread().