ARGOBOTS: src/include/abtd_ucontext.h File Reference
abtd_ucontext.h File Reference
Data Structures
struct ABTD_ythread_context
Functions
static void ABTDI_ucontext_check_peeked (ABTD_ythread_context *p_self)
static void ABTD_ucontext_wrapper (int arg1, int arg2)
static void ABTD_ythread_context_init (ABTD_ythread_context *p_ctx, void *p_stacktop, size_t stacksize)
static void ABTD_ythread_context_init_lazy (ABTD_ythread_context *p_ctx, size_t stacksize)
static void ABTD_ythread_context_lazy_set_stack (ABTD_ythread_context *p_ctx, void *p_stacktop)
static void ABTD_ythread_context_lazy_unset_stack (ABTD_ythread_context *p_ctx)
static void ABTD_ythread_context_reinit (ABTD_ythread_context *p_ctx)
static void * ABTD_ythread_context_get_stacktop (ABTD_ythread_context *p_ctx)
static ABT_bool ABTD_ythread_context_has_stack (const ABTD_ythread_context *p_ctx)
static size_t ABTD_ythread_context_get_stacksize (ABTD_ythread_context *p_ctx)
static void ABTDI_ythread_context_make (ABTD_ythread_context *p_ctx)
static ABT_bool ABTD_ythread_context_is_started (const ABTD_ythread_context *p_ctx)
static void ABTD_ythread_context_switch (ABTD_ythread_context *p_old, ABTD_ythread_context *p_new)
static void ABTD_ythread_context_start_and_switch (ABTD_ythread_context *p_old, ABTD_ythread_context *p_new)
static ABTU_noreturn void ABTD_ythread_context_jump (ABTD_ythread_context *p_new)
static ABTU_noreturn void ABTD_ythread_context_start_and_jump (ABTD_ythread_context *p_new)
static void ABTD_ythread_context_switch_with_call (ABTD_ythread_context *p_old, ABTD_ythread_context *p_new, void(*f_cb)(void *), void *cb_arg)
static void ABTD_ythread_context_start_and_switch_with_call (ABTD_ythread_context *p_old, ABTD_ythread_context *p_new, void(*f_cb)(void *), void *cb_arg)
static ABTU_noreturn void ABTD_ythread_context_jump_with_call (ABTD_ythread_context *p_new, void(*f_cb)(void *), void *cb_arg)
static ABTU_noreturn void ABTD_ythread_context_start_and_jump_with_call (ABTD_ythread_context *p_new, void(*f_cb)(void *), void *cb_arg)
static ABT_bool ABTD_ythread_context_peek (ABTD_ythread_context *p_ctx, void(*peek_func)(void *), void *arg)
Function Documentation
ABTD_ucontext_wrapper()
static void ABTD_ucontext_wrapper (int arg1, int arg2) static
Definition at line 42 of file abtd_ucontext.h.
Referenced by ABTDI_ythread_context_make().
ABTD_ythread_context_get_stacksize()
static size_t ABTD_ythread_context_get_stacksize (ABTD_ythread_context * p_ctx) inline static
Definition at line 114 of file abtd_ucontext.h.
ABTD_ythread_context_get_stacktop()
static void* ABTD_ythread_context_get_stacktop (ABTD_ythread_context * p_ctx) inline static
Definition at line 102 of file abtd_ucontext.h.
ABTD_ythread_context_has_stack()
static ABT_bool ABTD_ythread_context_has_stack (const ABTD_ythread_context * p_ctx) inline static
Definition at line 108 of file abtd_ucontext.h.
ABTD_ythread_context_init()
static void ABTD_ythread_context_init (ABTD_ythread_context * p_ctx, void * p_stacktop, size_t stacksize) inline static
Definition at line 63 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_init_lazy().
ABTD_ythread_context_init_lazy()
static void ABTD_ythread_context_init_lazy (ABTD_ythread_context * p_ctx, size_t stacksize) inline static
Definition at line 74 of file abtd_ucontext.h.
ABTD_ythread_context_is_started()
static ABT_bool ABTD_ythread_context_is_started (const ABTD_ythread_context * p_ctx) inline static
Definition at line 143 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_jump(), ABTD_ythread_context_jump_with_call(), ABTD_ythread_context_start_and_jump(), ABTD_ythread_context_start_and_jump_with_call(), ABTD_ythread_context_start_and_switch(), ABTD_ythread_context_start_and_switch_with_call(), ABTD_ythread_context_switch(), and ABTD_ythread_context_switch_with_call().
ABTD_ythread_context_jump()
static ABTU_noreturn void ABTD_ythread_context_jump (ABTD_ythread_context * p_new) inline static
Definition at line 175 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_start_and_jump().
ABTD_ythread_context_jump_with_call()
static ABTU_noreturn void ABTD_ythread_context_jump_with_call (ABTD_ythread_context * p_new, void(*)(void *) f_cb, void * cb_arg) inline static
Definition at line 222 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_start_and_jump_with_call().
ABTD_ythread_context_lazy_set_stack()
static void ABTD_ythread_context_lazy_set_stack (ABTD_ythread_context * p_ctx, void * p_stacktop) inline static
Definition at line 81 of file abtd_ucontext.h.
ABTD_ythread_context_lazy_unset_stack()
static void ABTD_ythread_context_lazy_unset_stack (ABTD_ythread_context * p_ctx) inline static
Definition at line 88 of file abtd_ucontext.h.
ABTD_ythread_context_peek()
static ABT_bool ABTD_ythread_context_peek (ABTD_ythread_context * p_ctx, void(*)(void *) peek_func, void * arg) inline static
Definition at line 242 of file abtd_ucontext.h.
ABTD_ythread_context_reinit()
static void ABTD_ythread_context_reinit (ABTD_ythread_context * p_ctx) inline static
Definition at line 93 of file abtd_ucontext.h.
ABTD_ythread_context_start_and_jump()
static ABTU_noreturn void ABTD_ythread_context_start_and_jump (ABTD_ythread_context * p_new) inline static
Definition at line 184 of file abtd_ucontext.h.
ABTD_ythread_context_start_and_jump_with_call()
static ABTU_noreturn void ABTD_ythread_context_start_and_jump_with_call (ABTD_ythread_context * p_new, void(*)(void *) f_cb, void * cb_arg) inline static
Definition at line 233 of file abtd_ucontext.h.
ABTD_ythread_context_start_and_switch()
static void ABTD_ythread_context_start_and_switch (ABTD_ythread_context * p_old, ABTD_ythread_context * p_new) inline static
Definition at line 166 of file abtd_ucontext.h.
ABTD_ythread_context_start_and_switch_with_call()
static void ABTD_ythread_context_start_and_switch_with_call (ABTD_ythread_context * p_old, ABTD_ythread_context * p_new, void(*)(void *) f_cb, void * cb_arg) inline static
Definition at line 212 of file abtd_ucontext.h.
ABTD_ythread_context_switch()
static void ABTD_ythread_context_switch (ABTD_ythread_context * p_old, ABTD_ythread_context * p_new) inline static
Definition at line 148 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_start_and_switch().
ABTD_ythread_context_switch_with_call()
static void ABTD_ythread_context_switch_with_call (ABTD_ythread_context * p_old, ABTD_ythread_context * p_new, void(*)(void *) f_cb, void * cb_arg) inline static
Definition at line 193 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_start_and_switch_with_call().
ABTDI_ucontext_check_peeked()
static void ABTDI_ucontext_check_peeked (ABTD_ythread_context * p_self) inline static
Definition at line 26 of file abtd_ucontext.h.
Referenced by ABTD_ucontext_wrapper(), ABTD_ythread_context_switch(), and ABTD_ythread_context_switch_with_call().
ABTDI_ythread_context_make()
static void ABTDI_ythread_context_make (ABTD_ythread_context * p_ctx) inline static
Definition at line 119 of file abtd_ucontext.h.
Referenced by ABTD_ythread_context_start_and_jump(), ABTD_ythread_context_start_and_jump_with_call(), ABTD_ythread_context_start_and_switch(), and ABTD_ythread_context_start_and_switch_with_call().