ARGOBOTS: src/include/abti_thread_attr.h File Reference
abti_thread_attr.h File Reference
Functions
static ABTI_thread_attr * ABTI_thread_attr_get_ptr (ABT_thread_attr attr)
static ABT_thread_attr ABTI_thread_attr_get_handle (ABTI_thread_attr *p_attr)
static void ABTI_thread_attr_init_migration (ABTI_thread_attr *p_attr, ABT_bool migratable)
static void ABTI_thread_attr_init (ABTI_thread_attr *p_attr, void *p_stack, size_t stacksize, ABTI_stack_type stacktype, ABT_bool migratable)
static void ABTI_thread_attr_copy (ABTI_thread_attr *p_dest, ABTI_thread_attr *p_src)
Function Documentation
static void ABTI_thread_attr_copy (ABTI_thread_attr * p_dest, ABTI_thread_attr * p_src) inline static
Definition at line 65 of file abti_thread_attr.h.
Referenced by ABTI_thread_attr_dup().
static ABT_thread_attr ABTI_thread_attr_get_handle (ABTI_thread_attr * p_attr) inline static
Definition at line 27 of file abti_thread_attr.h.
Referenced by ABT_thread_attr_create(), and ABT_thread_get_attr().
static ABTI_thread_attr* ABTI_thread_attr_get_ptr (ABT_thread_attr attr) inline static
Definition at line 11 of file abti_thread_attr.h.
Referenced by ABT_info_print_thread_attr(), ABT_thread_attr_free(), ABT_thread_attr_get_stack(), ABT_thread_attr_get_stacksize(), ABT_thread_attr_set_callback(), ABT_thread_attr_set_migratable(), ABT_thread_attr_set_stack(), ABT_thread_attr_set_stacksize(), ABT_thread_create(), ABT_thread_create_many(), and ABT_thread_create_on_xstream().
static void ABTI_thread_attr_init (ABTI_thread_attr * p_attr, void * p_stack, size_t stacksize, ABTI_stack_type stacktype, ABT_bool migratable) inline static
Definition at line 52 of file abti_thread_attr.h.
Referenced by ABT_thread_attr_create(), ABTI_thread_create_main(), ABTI_thread_create_main_sched(), and ABTI_thread_create_sched().
static void ABTI_thread_attr_init_migration (ABTI_thread_attr * p_attr, ABT_bool migratable) inline static
Definition at line 43 of file abti_thread_attr.h.
Referenced by ABTI_thread_attr_init().