ARGOBOTS: src/sched/basic_wait.c File Reference
basic_wait.c File Reference
#include "abti.h"
Data Structures
struct sched_data
Functions
static int sched_init (ABT_sched sched, ABT_sched_config config)
static void sched_run (ABT_sched sched)
static int sched_free (ABT_sched)
static void sched_sort_pools (int num_pools, ABT_pool *pools)
ABT_sched_def * ABTI_sched_get_basic_wait_def (void)
static sched_data * sched_data_get_ptr (void *data)
static int pool_get_access_num (ABT_pool *p_pool)
static int sched_cmp_pools (const void *p1, const void *p2)
Variables
static ABT_sched_def sched_basic_wait_def
Function Documentation
ABTI_sched_get_basic_wait_def()
ABT_sched_def* ABTI_sched_get_basic_wait_def (void)
Definition at line 27 of file basic_wait.c.
Referenced by ABTI_sched_create_basic(), and ABTI_sched_print().
pool_get_access_num()
static int pool_get_access_num (ABT_pool * p_pool) static
Definition at line 169 of file basic_wait.c.
Referenced by sched_cmp_pools().
sched_cmp_pools()
static int sched_cmp_pools (const void * p1, const void * p2) static
Definition at line 195 of file basic_wait.c.
Referenced by sched_sort_pools().
sched_data_get_ptr()
static sched_data* sched_data_get_ptr (void * data) inline static
Definition at line 32 of file basic_wait.c.
Referenced by sched_free(), and sched_run().
sched_free()
static int sched_free (ABT_sched sched) static
Definition at line 158 of file basic_wait.c.
sched_init()
static int sched_init (ABT_sched sched, ABT_sched_config config) static
Definition at line 37 of file basic_wait.c.
sched_run()
static void sched_run (ABT_sched sched) static
Definition at line 85 of file basic_wait.c.
sched_sort_pools()
static void sched_sort_pools (int num_pools, ABT_pool * pools) static
Definition at line 211 of file basic_wait.c.
Referenced by sched_init().
Variable Documentation
sched_basic_wait_def
ABT_sched_def sched_basic_wait_def static
Initial value:
= {
    .type = ABT_SCHED_TYPE_ULT,
    .init = sched_init,
    .run = sched_run,
    .free = sched_free,
    .get_migr_pool = NULL,
}
Definition at line 13 of file basic_wait.c.
Referenced by ABTI_sched_get_basic_wait_def().