ARGOBOTS: src/util/atoi.c File Reference
atoi.c File Reference
#include "abti.h"
Functions
static ABTU_ret_err int atoi_impl (const char *str, ABT_bool *p_is_signed, uint64_t *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atoi (const char *str, int *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atoui32 (const char *str, uint32_t *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atoui64 (const char *str, uint64_t *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atosz (const char *str, size_t *p_val, ABT_bool *p_overflow)
Function Documentation
ABTU_atoi()
ABTU_ret_err int ABTU_atoi (const char * str, int * p_val, ABT_bool * p_overflow)
Definition at line 11 of file atoi.c.
Referenced by load_env_int().
ABTU_atosz()
ABTU_ret_err int ABTU_atosz (const char * str, size_t * p_val, ABT_bool * p_overflow)
Definition at line 85 of file atoi.c.
Referenced by load_env_size().
ABTU_atoui32()
ABTU_ret_err int ABTU_atoui32 (const char * str, uint32_t * p_val, ABT_bool * p_overflow)
Definition at line 39 of file atoi.c.
Referenced by ABTU_atosz(), and load_env_uint32().
ABTU_atoui64()
ABTU_ret_err int ABTU_atoui64 (const char * str, uint64_t * p_val, ABT_bool * p_overflow)
Definition at line 65 of file atoi.c.
Referenced by ABTU_atosz(), and load_env_uint64().
atoi_impl()
static ABTU_ret_err int atoi_impl (const char * str, ABT_bool * p_is_signed, uint64_t * p_val, ABT_bool * p_overflow) static
Definition at line 114 of file atoi.c.
Referenced by ABTU_atoi(), ABTU_atoui32(), and ABTU_atoui64().