ARGOBOTS: src/include/abti.h File Reference
abti.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>
#include <string.h>
#include <limits.h>
#include "abt_config.h"
#include "abt.h"
#include "abtu.h"
#include "abti_error.h"
#include "abti_valgrind.h"
#include "abtd.h"
#include "abti_spinlock.h"
#include "abti_sync_lifo.h"
#include "abti_mem_pool.h"
#include "abti_log.h"
#include "abti_local.h"
#include "abti_global.h"
#include "abti_pool.h"
#include "abti_sched.h"
#include "abti_config.h"
#include "abti_stream.h"
#include "abti_self.h"
#include "abti_thread.h"
#include "abti_tool.h"
#include "abti_ythread.h"
#include "abti_thread_attr.h"
#include "abti_mutex.h"
#include "abti_mutex_attr.h"
#include "abti_cond.h"
#include "abti_rwlock.h"
#include "abti_eventual.h"
#include "abti_future.h"
#include "abti_barrier.h"
#include "abti_timer.h"
#include "abti_mem.h"
#include "abti_key.h"
Data Structures
struct ABTI_mutex_attr
struct ABTI_mutex
struct ABTI_global
struct ABTI_local_func
struct ABTI_xstream
struct ABTI_sched
struct ABTI_pool
struct ABTI_thread
struct ABTI_thread_attr
struct ABTI_thread_mig_data
struct ABTI_ythread
struct ABTI_key
struct ABTI_ktelem
struct ABTI_ktable
struct ABTI_cond
struct ABTI_rwlock
struct ABTI_eventual
struct ABTI_future
struct ABTI_barrier
struct ABTI_timer
Macros
#define ABTI_SCHED_NUM_PRIO 3
#define ABTI_XSTREAM_REQ_JOIN (1 << 0)
#define ABTI_XSTREAM_REQ_EXIT (1 << 1)
#define ABTI_XSTREAM_REQ_CANCEL (1 << 2)
#define ABTI_XSTREAM_REQ_STOP (1 << 3)
#define ABTI_SCHED_REQ_FINISH (1 << 0)
#define ABTI_SCHED_REQ_EXIT (1 << 1)
#define ABTI_THREAD_REQ_JOIN (1 << 0)
#define ABTI_THREAD_REQ_EXIT (1 << 1)
#define ABTI_THREAD_REQ_CANCEL (1 << 2)
#define ABTI_THREAD_REQ_MIGRATE (1 << 3)
#define ABTI_THREAD_REQ_TERMINATE (1 << 4)
#define ABTI_THREAD_REQ_BLOCK (1 << 5)
#define ABTI_THREAD_REQ_ORPHAN (1 << 6)
#define ABTI_THREAD_REQ_NOPUSH (1 << 7)
#define ABTI_THREAD_REQ_STOP (ABTI_THREAD_REQ_EXIT | ABTI_THREAD_REQ_TERMINATE)
#define ABTI_THREAD_REQ_NON_YIELD
#define ABTI_THREAD_INIT_ID 0xFFFFFFFFFFFFFFFF
#define ABTI_TASK_INIT_ID 0xFFFFFFFFFFFFFFFF
#define ABTI_INDENT 4
#define ABT_THREAD_TYPE_FULLY_FLEDGED 0
#define ABT_THREAD_TYPE_DYNAMIC_PROMOTION 1
#define ABTI_THREAD_TYPE_EXT ((ABTI_thread_type)0)
#define ABTI_THREAD_TYPE_THREAD ((ABTI_thread_type)(0x1 << 0))
#define ABTI_THREAD_TYPE_MAIN ((ABTI_thread_type)(0x1 << 1))
#define ABTI_THREAD_TYPE_MAIN_SCHED ((ABTI_thread_type)(0x1 << 2))
#define ABTI_THREAD_TYPE_YIELDABLE ((ABTI_thread_type)(0x1 << 3))
#define ABTI_THREAD_TYPE_NAMED ((ABTI_thread_type)(0x1 << 4))
#define ABTI_THREAD_TYPE_MIGRATABLE ((ABTI_thread_type)(0x1 << 5))
#define ABTI_UNUSED(a) (void)(a)
Typedefs
typedef struct ABTI_global ABTI_global
typedef struct ABTI_local_func ABTI_local_func
typedef struct ABTI_xstream ABTI_xstream
typedef enum ABTI_xstream_type ABTI_xstream_type
typedef struct ABTI_sched ABTI_sched
typedef char * ABTI_sched_config
typedef enum ABTI_sched_used ABTI_sched_used
typedef void * ABTI_sched_id
typedef uintptr_t ABTI_sched_kind
typedef struct ABTI_pool ABTI_pool
typedef struct ABTI_thread ABTI_thread
typedef struct ABTI_thread_attr ABTI_thread_attr
typedef struct ABTI_ythread ABTI_ythread
typedef struct ABTI_thread_mig_data ABTI_thread_mig_data
typedef enum ABTI_stack_type ABTI_stack_type
typedef uint32_t ABTI_thread_type
typedef enum ABTI_thread_state ABTI_thread_state
typedef struct ABTI_ythread_htable ABTI_ythread_htable
typedef struct ABTI_ythread_queue ABTI_ythread_queue
typedef struct ABTI_key ABTI_key
typedef struct ABTI_ktelem ABTI_ktelem
typedef struct ABTI_ktable ABTI_ktable
typedef struct ABTI_mutex_attr ABTI_mutex_attr
typedef struct ABTI_mutex ABTI_mutex
typedef struct ABTI_cond ABTI_cond
typedef struct ABTI_rwlock ABTI_rwlock
typedef struct ABTI_eventual ABTI_eventual
typedef struct ABTI_future ABTI_future
typedef struct ABTI_barrier ABTI_barrier
typedef struct ABTI_timer ABTI_timer
typedef struct
ABTI_native_thread_id_opaque * ABTI_native_thread_id
typedef struct
ABTI_thread_id_opaque * ABTI_thread_id
typedef struct ABTI_spinlock ABTI_spinlock
Enumerations
enum ABTI_xstream_type { ABTI_XSTREAM_TYPE_PRIMARY, ABTI_XSTREAM_TYPE_SECONDARY }
enum ABTI_sched_used { ABTI_SCHED_NOT_USED, ABTI_SCHED_MAIN, ABTI_SCHED_IN_POOL }
enum ABTI_thread_state { ABTI_THREAD_STATE_READY, ABTI_THREAD_STATE_RUNNING, ABTI_THREAD_STATE_BLOCKED, ABTI_THREAD_STATE_TERMINATED }
enum ABTI_mutex_attr_val { ABTI_MUTEX_ATTR_NONE = 0, ABTI_MUTEX_ATTR_RECURSIVE = 1 << 0 }
enum ABTI_stack_type { ABTI_STACK_TYPE_MEMPOOL = 0, ABTI_STACK_TYPE_MALLOC, ABTI_STACK_TYPE_USER, ABTI_STACK_TYPE_MAIN }
Functions
void ABTI_global_update_max_xstreams (int new_size)
int ABTI_xstream_create (ABTI_sched *p_sched, ABTI_xstream **pp_xstream)
int ABTI_xstream_create_primary (ABTI_xstream **pp_xstream)
int ABTI_xstream_start (ABTI_xstream *p_local_xstream, ABTI_xstream *p_xstream)
int ABTI_xstream_start_primary (ABTI_xstream **pp_local_xstream, ABTI_xstream *p_xstream, ABTI_ythread *p_ythread)
int ABTI_xstream_free (ABTI_xstream *p_local_xstream, ABTI_xstream *p_xstream, ABT_bool force_free)
int ABTI_xstream_join (ABTI_xstream **pp_local_xstream, ABTI_xstream *p_xstream)
void ABTI_xstream_schedule (void *p_arg)
int ABTI_xstream_run_unit (ABTI_xstream **pp_local_xstream, ABT_unit unit, ABTI_pool *p_pool)
int ABTI_xstream_schedule_ythread (ABTI_xstream **pp_local_xstream, ABTI_ythread *p_ythread)
void ABTI_xstream_schedule_task (ABTI_xstream *p_local_xstream, ABTI_thread *p_task)
int ABTI_xstream_migrate_thread (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
int ABTI_xstream_init_main_sched (ABTI_xstream *p_xstream, ABTI_sched *p_sched)
int ABTI_xstream_update_main_sched (ABTI_xstream **pp_local_xstream, ABTI_xstream *p_xstream, ABTI_sched *p_sched)
int ABTI_xstream_check_events (ABTI_xstream *p_xstream, ABT_sched sched)
void * ABTI_xstream_launch_main_sched (void *p_arg)
void ABTI_xstream_print (ABTI_xstream *p_xstream, FILE *p_os, int indent, ABT_bool print_sub)
ABT_sched_def * ABTI_sched_get_basic_def (void)
ABT_sched_def * ABTI_sched_get_basic_wait_def (void)
ABT_sched_def * ABTI_sched_get_prio_def (void)
ABT_sched_def * ABTI_sched_get_randws_def (void)
void ABTI_sched_finish (ABTI_sched *p_sched)
void ABTI_sched_exit (ABTI_sched *p_sched)
int ABTI_sched_create (ABT_sched_def *def, int num_pools, ABT_pool *pools, ABT_sched_config config, ABT_bool automatic, ABTI_sched **pp_newsched)
int ABTI_sched_create_basic (ABT_sched_predef predef, int num_pools, ABT_pool *pools, ABT_sched_config config, ABTI_sched **pp_newsched)
int ABTI_sched_free (ABTI_xstream *p_local_xstream, ABTI_sched *p_sched, ABT_bool force_free)
int ABTI_sched_get_migration_pool (ABTI_sched *, ABTI_pool *, ABTI_pool **)
ABTI_sched_kind ABTI_sched_get_kind (ABT_sched_def *def)
ABT_bool ABTI_sched_has_to_stop (ABTI_xstream **pp_local_xstream, ABTI_sched *p_sched)
size_t ABTI_sched_get_size (ABTI_sched *p_sched)
size_t ABTI_sched_get_total_size (ABTI_sched *p_sched)
size_t ABTI_sched_get_effective_size (ABTI_xstream *p_local_xstream, ABTI_sched *p_sched)
void ABTI_sched_print (ABTI_sched *p_sched, FILE *p_os, int indent, ABT_bool print_sub)
void ABTI_sched_reset_id (void)
size_t ABTI_sched_config_type_size (ABT_sched_config_type type)
int ABTI_sched_config_read (ABT_sched_config config, int type, int num_vars, void **variables)
int ABTI_sched_config_read_global (ABT_sched_config config, ABT_pool_access *access, ABT_bool *automatic)
int ABTI_pool_create (ABT_pool_def *def, ABT_pool_config config, ABT_bool automatic, ABTI_pool **pp_newpool)
int ABTI_pool_create_basic (ABT_pool_kind kind, ABT_pool_access access, ABT_bool automatic, ABTI_pool **pp_newpool)
void ABTI_pool_free (ABTI_pool *p_pool)
int ABTI_pool_get_fifo_def (ABT_pool_access access, ABT_pool_def *p_def)
int ABTI_pool_get_fifo_wait_def (ABT_pool_access access, ABT_pool_def *p_def)
int ABTI_pool_set_consumer (ABTI_pool *p_pool, ABTI_native_thread_id consumer_id)
int ABTI_pool_set_producer (ABTI_pool *p_pool, ABTI_native_thread_id producer_id)
int ABTI_pool_accept_migration (ABTI_pool *p_pool, ABTI_pool *source)
void ABTI_pool_print (ABTI_pool *p_pool, FILE *p_os, int indent)
void ABTI_pool_reset_id (void)
void ABTI_unit_set_associated_pool (ABT_unit unit, ABTI_pool *p_pool)
int ABTI_thread_migrate_to_pool (ABTI_xstream **pp_local_xstream, ABTI_thread *p_thread, ABTI_pool *p_pool)
ABTI_thread_mig_data * ABTI_thread_get_mig_data (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
void ABTI_thread_free (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
void ABTI_thread_print (ABTI_thread *p_thread, FILE *p_os, int indent)
void ABTI_thread_reset_id (void)
ABT_unit_id ABTI_thread_get_id (ABTI_thread *p_thread)
int ABTI_ythread_create (ABTI_xstream *p_local_xstream, ABTI_pool *p_pool, void(*thread_func)(void *), void *arg, ABTI_thread_attr *p_attr, ABTI_ythread **pp_newthread)
int ABTI_ythread_create_main (ABTI_xstream *p_local_xstream, ABTI_xstream *p_xstream, ABTI_ythread **p_ythread)
int ABTI_ythread_create_main_sched (ABTI_xstream *p_local_xstream, ABTI_xstream *p_xstream, ABTI_sched *p_sched)
int ABTI_ythread_create_sched (ABTI_xstream *p_local_xstream, ABTI_pool *p_pool, ABTI_sched *p_sched)
void ABTI_ythread_free_main (ABTI_xstream *p_local_xstream, ABTI_ythread *p_ythread)
void ABTI_ythread_free_main_sched (ABTI_xstream *p_local_xstream, ABTI_ythread *p_ythread)
int ABTI_ythread_set_blocked (ABTI_ythread *p_ythread)
void ABTI_ythread_suspend (ABTI_xstream **pp_local_xstream, ABTI_ythread *p_ythread, ABT_sync_event_type sync_event_type, void *p_sync)
int ABTI_ythread_set_ready (ABTI_xstream *p_local_xstream, ABTI_ythread *p_ythread)
int ABTI_ythread_print_stack (ABTI_ythread *p_ythread, FILE *p_os)
void ABTI_thread_attr_print (ABTI_thread_attr *p_attr, FILE *p_os, int indent)
void ABTI_thread_attr_get_str (ABTI_thread_attr *p_attr, char *p_buf)
ABTI_thread_attr * ABTI_thread_attr_dup (ABTI_thread_attr *p_attr)
ABTI_ythread_htable * ABTI_ythread_htable_create (uint32_t num_rows)
void ABTI_ythread_htable_free (ABTI_ythread_htable *p_htable)
void ABTI_ythread_htable_push (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
ABT_bool ABTI_ythread_htable_add (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
void ABTI_ythread_htable_push_low (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
ABT_bool ABTI_ythread_htable_add_low (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
ABTI_ythread * ABTI_ythread_htable_pop (ABTI_ythread_htable *p_htable, ABTI_ythread_queue *p_queue)
ABTI_ythread * ABTI_ythread_htable_pop_low (ABTI_ythread_htable *p_htable, ABTI_ythread_queue *p_queue)
ABT_bool ABTI_ythread_htable_switch_low (ABTI_xstream **pp_local_xstream, ABTI_ythread_queue *p_queue, ABTI_ythread *p_ythread, ABTI_ythread_htable *p_htable, ABT_sync_event_type sync_event_type, void *p_sync)
void ABTI_ktable_free (ABTI_xstream *p_local_xstream, ABTI_ktable *p_ktable)
void ABTI_mutex_wait (ABTI_xstream **pp_local_xstream, ABTI_mutex *p_mutex, int val)
void ABTI_mutex_wait_low (ABTI_xstream **pp_local_xstream, ABTI_mutex *p_mutex, int val)
void ABTI_mutex_wake_se (ABTI_mutex *p_mutex, int num)
void ABTI_mutex_wake_de (ABTI_xstream *p_local_xstream, ABTI_mutex *p_mutex)
void ABTI_mutex_attr_print (ABTI_mutex_attr *p_attr, FILE *p_os, int indent)
void ABTI_mutex_attr_get_str (ABTI_mutex_attr *p_attr, char *p_buf)
int ABTI_info_print_config (FILE *fp)
void ABTI_info_check_print_all_thread_stacks (void)
Variables
ABTI_global * gp_ABTI_global
ABTI_local_func gp_ABTI_local_func
ABTD_XSTREAM_LOCAL ABTI_xstream * lp_ABTI_xstream
Macro Definition Documentation
#define ABT_THREAD_TYPE_DYNAMIC_PROMOTION 1
Definition at line 53 of file abti.h.
#define ABT_THREAD_TYPE_FULLY_FLEDGED 0
Definition at line 52 of file abti.h.
#define ABTI_INDENT 4
Definition at line 50 of file abti.h.
Referenced by ABTI_xstream_print().
#define ABTI_SCHED_NUM_PRIO 3
Definition at line 23 of file abti.h.
Referenced by ABTI_sched_create_basic().
#define ABTI_SCHED_REQ_EXIT (1 << 1)
Definition at line 31 of file abti.h.
Referenced by ABTI_sched_exit(), and ABTI_sched_has_to_stop().
#define ABTI_SCHED_REQ_FINISH (1 << 0)
Definition at line 30 of file abti.h.
Referenced by ABTI_sched_finish(), ABTI_sched_has_to_stop(), and ABTI_xstream_update_main_sched().
#define ABTI_TASK_INIT_ID 0xFFFFFFFFFFFFFFFF
Definition at line 48 of file abti.h.
Referenced by ABTI_task_create().
#define ABTI_THREAD_INIT_ID 0xFFFFFFFFFFFFFFFF
Definition at line 47 of file abti.h.
Referenced by ABTI_thread_get_id(), and ABTI_ythread_create_internal().
#define ABTI_THREAD_REQ_BLOCK (1 << 5)
Definition at line 38 of file abti.h.
Referenced by ABTI_mutex_unlock_se(), ABTI_tool_event_ythread_yield_impl(), ABTI_xstream_schedule_ythread(), ABTI_ythread_set_blocked(), and ABTI_ythread_set_ready().
#define ABTI_THREAD_REQ_CANCEL (1 << 2)
Definition at line 35 of file abti.h.
Referenced by ABT_thread_cancel(), ABTI_xstream_schedule_task(), and ABTI_xstream_schedule_ythread().
#define ABTI_THREAD_REQ_EXIT (1 << 1)
Definition at line 34 of file abti.h.
Referenced by ABT_thread_exit(), and ABTI_xstream_schedule_ythread().
#define ABTI_THREAD_REQ_JOIN (1 << 0)
Definition at line 33 of file abti.h.
Referenced by ABTD_ythread_cancel(), ABTD_ythread_terminate(), ABTI_thread_join(), and ABTI_ythread_context_switch_to_child_internal().
#define ABTI_THREAD_REQ_MIGRATE (1 << 3)
Definition at line 36 of file abti.h.
Referenced by ABTI_thread_migrate_to_pool(), ABTI_xstream_migrate_thread(), and ABTI_xstream_schedule_ythread().
#define ABTI_THREAD_REQ_NON_YIELD
Value:
(ABTI_THREAD_REQ_EXIT | ABTI_THREAD_REQ_CANCEL | ABTI_THREAD_REQ_MIGRATE | \
     ABTI_THREAD_REQ_TERMINATE | ABTI_THREAD_REQ_BLOCK |                       \
     ABTI_THREAD_REQ_ORPHAN | ABTI_THREAD_REQ_NOPUSH)
Definition at line 42 of file abti.h.
Referenced by ABTI_xstream_schedule_ythread().
#define ABTI_THREAD_REQ_NOPUSH (1 << 7)
Definition at line 40 of file abti.h.
Referenced by ABTI_xstream_schedule_ythread(), and ABTI_xstream_update_main_sched().
#define ABTI_THREAD_REQ_ORPHAN (1 << 6)
Definition at line 39 of file abti.h.
Referenced by ABT_finalize(), and ABTI_xstream_schedule_ythread().
#define ABTI_THREAD_REQ_STOP (ABTI_THREAD_REQ_EXIT | ABTI_THREAD_REQ_TERMINATE)
Definition at line 41 of file abti.h.
Referenced by ABTI_xstream_schedule_ythread().
#define ABTI_THREAD_REQ_TERMINATE (1 << 4)
Definition at line 37 of file abti.h.
Referenced by ABTD_ythread_cancel(), ABTD_ythread_terminate(), ABTI_xstream_schedule_ythread(), and ABTI_ythread_context_switch_to_child_internal().
#define ABTI_THREAD_TYPE_EXT ((ABTI_thread_type)0)
Definition at line 66 of file abti.h.
Referenced by ABT_cond_timedwait(), ABT_eventual_wait(), ABT_future_wait(), ABTI_cond_wait(), ABTI_self_get_type(), and ABTI_thread_type_get_type().
#define ABTI_THREAD_TYPE_MAIN ((ABTI_thread_type)(0x1 << 1))
Definition at line 68 of file abti.h.
Referenced by ABT_finalize(), ABT_self_is_primary(), ABT_thread_cancel(), ABT_thread_free(), ABT_thread_is_primary(), ABT_thread_migrate_to_sched(), ABT_thread_set_migratable(), ABTI_thread_join(), ABTI_thread_migrate_to_pool(), ABTI_thread_migrate_to_xstream(), ABTI_thread_print(), ABTI_xstream_update_main_sched(), ABTI_ythread_create_internal(), ABTI_ythread_create_main(), and ABTI_ythread_finish_context_sched_to_main_thread().
#define ABTI_THREAD_TYPE_MAIN_SCHED ((ABTI_thread_type)(0x1 << 2))
Definition at line 69 of file abti.h.
Referenced by ABT_thread_cancel(), ABT_thread_free(), ABT_thread_migrate_to_sched(), ABT_thread_set_migratable(), ABTI_sched_free(), ABTI_thread_join(), ABTI_thread_migrate_to_pool(), ABTI_thread_migrate_to_xstream(), ABTI_thread_print(), ABTI_ythread_create_internal(), ABTI_ythread_create_main_sched(), ABTI_ythread_finish_context_sched_to_main_thread(), and ABTI_ythread_set_blocked().
#define ABTI_THREAD_TYPE_MIGRATABLE ((ABTI_thread_type)(0x1 << 5))
Definition at line 72 of file abti.h.
Referenced by ABT_thread_get_attr(), ABT_thread_is_migratable(), ABT_thread_set_migratable(), ABTI_task_create(), and ABTI_ythread_create_internal().
#define ABTI_THREAD_TYPE_NAMED ((ABTI_thread_type)(0x1 << 4))
Definition at line 71 of file abti.h.
Referenced by ABT_self_is_unnamed(), ABT_thread_create(), ABT_thread_create_many(), ABT_thread_create_on_xstream(), ABT_thread_is_unnamed(), ABTI_task_create(), ABTI_xstream_terminate_thread(), and ABTI_ythread_create().
#define ABTI_THREAD_TYPE_THREAD ((ABTI_thread_type)(0x1 << 0))
Definition at line 67 of file abti.h.
Referenced by ABTI_task_create().
#define ABTI_THREAD_TYPE_YIELDABLE ((ABTI_thread_type)(0x1 << 3))
Definition at line 70 of file abti.h.
Referenced by ABT_cond_timedwait(), ABT_self_is_primary(), ABT_task_self(), ABT_task_self_id(), ABT_thread_create(), ABT_thread_create_many(), ABT_thread_create_on_xstream(), ABT_thread_self_id(), ABT_xstream_set_main_sched(), ABTD_ythread_terminate_no_arg(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_mutex_unlock_se(), ABTI_thread_get_ythread_or_null(), ABTI_thread_print(), ABTI_thread_type_get_type(), ABTI_tool_query(), ABTI_xstream_join(), ABTI_ythread_context_switch_to_child_internal(), ABTI_ythread_context_switch_to_parent_internal(), ABTI_ythread_context_switch_to_sibling_internal(), ABTI_ythread_create(), ABTI_ythread_create_main(), ABTI_ythread_create_main_sched(), ABTI_ythread_create_sched(), unit_create_from_task(), unit_create_from_thread(), and unit_get_task().
#define ABTI_UNUSED (a) (void)(a)
Definition at line 94 of file abti.h.
Referenced by ABT_init(), and pool_init().
#define ABTI_XSTREAM_REQ_CANCEL (1 << 2)
Definition at line 27 of file abti.h.
Referenced by ABT_xstream_cancel(), ABTI_xstream_check_events(), and ABTI_xstream_schedule().
#define ABTI_XSTREAM_REQ_EXIT (1 << 1)
Definition at line 26 of file abti.h.
Referenced by ABT_xstream_exit(), ABTI_xstream_check_events(), and ABTI_xstream_schedule().
#define ABTI_XSTREAM_REQ_JOIN (1 << 0)
Definition at line 25 of file abti.h.
Referenced by ABT_finalize(), ABTI_xstream_check_events(), ABTI_xstream_join(), and ABTI_xstream_schedule().
#define ABTI_XSTREAM_REQ_STOP (1 << 3)
Definition at line 28 of file abti.h.
Typedef Documentation
typedef struct ABTI_barrier ABTI_barrier
Definition at line 125 of file abti.h.
typedef struct ABTI_cond ABTI_cond
Definition at line 121 of file abti.h.
typedef struct ABTI_eventual ABTI_eventual
Definition at line 123 of file abti.h.
typedef struct ABTI_future ABTI_future
Definition at line 124 of file abti.h.
typedef struct ABTI_global ABTI_global
Definition at line 97 of file abti.h.
typedef struct ABTI_key ABTI_key
Definition at line 116 of file abti.h.
typedef struct ABTI_ktable ABTI_ktable
Definition at line 118 of file abti.h.
typedef struct ABTI_ktelem ABTI_ktelem
Definition at line 117 of file abti.h.
typedef struct ABTI_local_func ABTI_local_func
Definition at line 98 of file abti.h.
typedef struct ABTI_mutex ABTI_mutex
Definition at line 120 of file abti.h.
typedef struct ABTI_mutex_attr ABTI_mutex_attr
Definition at line 119 of file abti.h.
typedef struct ABTI_native_thread_id_opaque* ABTI_native_thread_id
Definition at line 133 of file abti.h.
typedef struct ABTI_pool ABTI_pool
Definition at line 106 of file abti.h.
typedef struct ABTI_rwlock ABTI_rwlock
Definition at line 122 of file abti.h.
typedef struct ABTI_sched ABTI_sched
Definition at line 101 of file abti.h.
typedef char* ABTI_sched_config
Definition at line 102 of file abti.h.
typedef void* ABTI_sched_id
Definition at line 104 of file abti.h.
typedef uintptr_t ABTI_sched_kind
Definition at line 105 of file abti.h.
typedef enum ABTI_sched_used ABTI_sched_used
Definition at line 103 of file abti.h.
typedef struct ABTI_spinlock ABTI_spinlock
Definition at line 142 of file abti.h.
typedef enum ABTI_stack_type ABTI_stack_type
Definition at line 111 of file abti.h.
typedef struct ABTI_thread ABTI_thread
Definition at line 107 of file abti.h.
typedef struct ABTI_thread_attr ABTI_thread_attr
Definition at line 108 of file abti.h.
typedef struct ABTI_thread_id_opaque* ABTI_thread_id
Definition at line 136 of file abti.h.
typedef struct ABTI_thread_mig_data ABTI_thread_mig_data
Definition at line 110 of file abti.h.
typedef enum ABTI_thread_state ABTI_thread_state
Definition at line 113 of file abti.h.
typedef uint32_t ABTI_thread_type
Definition at line 112 of file abti.h.
typedef struct ABTI_timer ABTI_timer
Definition at line 126 of file abti.h.
typedef struct ABTI_xstream ABTI_xstream
Definition at line 99 of file abti.h.
typedef enum ABTI_xstream_type ABTI_xstream_type
Definition at line 100 of file abti.h.
typedef struct ABTI_ythread ABTI_ythread
Definition at line 109 of file abti.h.
typedef struct ABTI_ythread_htable ABTI_ythread_htable
Definition at line 114 of file abti.h.
typedef struct ABTI_ythread_queue ABTI_ythread_queue
Definition at line 115 of file abti.h.
Enumeration Type Documentation
enum ABTI_mutex_attr_val
Enumerator
ABTI_MUTEX_ATTR_NONE
ABTI_MUTEX_ATTR_RECURSIVE
Definition at line 81 of file abti.h.
enum ABTI_sched_used
Enumerator
ABTI_SCHED_NOT_USED
ABTI_SCHED_MAIN
ABTI_SCHED_IN_POOL
Definition at line 60 of file abti.h.
enum ABTI_stack_type
Enumerator
ABTI_STACK_TYPE_MEMPOOL
ABTI_STACK_TYPE_MALLOC
ABTI_STACK_TYPE_USER
ABTI_STACK_TYPE_MAIN
Definition at line 86 of file abti.h.
enum ABTI_thread_state
Enumerator
ABTI_THREAD_STATE_READY
ABTI_THREAD_STATE_RUNNING
ABTI_THREAD_STATE_BLOCKED
ABTI_THREAD_STATE_TERMINATED
Definition at line 74 of file abti.h.
enum ABTI_xstream_type
Enumerator
ABTI_XSTREAM_TYPE_PRIMARY
ABTI_XSTREAM_TYPE_SECONDARY
Definition at line 55 of file abti.h.
Function Documentation
void ABTI_global_update_max_xstreams (int new_size)
Definition at line 271 of file global.c.
Referenced by ABTI_xstream_set_new_rank(), and ABTI_xstream_take_rank().
void ABTI_info_check_print_all_thread_stacks (void)
Definition at line 702 of file info.c.
Referenced by ABTI_xstream_check_events().
int ABTI_info_print_config (FILE * fp)
Definition at line 794 of file info.c.
Referenced by ABT_info_print_config(), and ABT_init().
void ABTI_ktable_free (ABTI_xstream * p_local_xstream, ABTI_ktable * p_ktable)
Definition at line 161 of file key.c.
Referenced by ABTI_thread_free(), ABTI_ythread_free_main(), and ABTI_ythread_free_main_sched().
void ABTI_mutex_attr_get_str (ABTI_mutex_attr * p_attr, char * p_buf)
Definition at line 128 of file mutex_attr.c.
Referenced by ABTI_mutex_attr_print().
void ABTI_mutex_attr_print (ABTI_mutex_attr * p_attr, FILE * p_os, int indent)
Definition at line 117 of file mutex_attr.c.
void ABTI_mutex_wait (ABTI_xstream ** pp_local_xstream, ABTI_mutex * p_mutex, int val)
Definition at line 690 of file mutex.c.
Referenced by ABTI_mutex_lock().
void ABTI_mutex_wait_low (ABTI_xstream ** pp_local_xstream, ABTI_mutex * p_mutex, int val)
Definition at line 726 of file mutex.c.
Referenced by ABTI_mutex_lock_low().
void ABTI_mutex_wake_de (ABTI_xstream * p_local_xstream, ABTI_mutex * p_mutex)
Definition at line 762 of file mutex.c.
Referenced by ABTI_mutex_unlock(), and ABTI_mutex_unlock_se().
void ABTI_mutex_wake_se (ABTI_mutex * p_mutex, int num)
int ABTI_pool_accept_migration (ABTI_pool * p_pool, ABTI_pool * source)
Definition at line 860 of file pool.c.
Referenced by ABTI_sched_get_migration_pool(), and ABTI_thread_migrate_to_pool().
int ABTI_pool_create (ABT_pool_def * def, ABT_pool_config config, ABT_bool automatic, ABTI_pool ** pp_newpool)
Definition at line 581 of file pool.c.
Referenced by ABT_pool_create(), and ABTI_pool_create_basic().
int ABTI_pool_create_basic (ABT_pool_kind kind, ABT_pool_access access, ABT_bool automatic, ABTI_pool ** pp_newpool)
Definition at line 639 of file pool.c.
Referenced by ABT_pool_create_basic(), ABTI_sched_create(), and ABTI_sched_create_basic().
void ABTI_pool_free (ABTI_pool * p_pool)
Definition at line 670 of file pool.c.
Referenced by ABT_pool_free(), and ABTI_sched_free().
int ABTI_pool_get_fifo_def (ABT_pool_access access, ABT_pool_def * p_def)
Definition at line 47 of file fifo.c.
Referenced by ABTI_pool_create_basic().
int ABTI_pool_get_fifo_wait_def (ABT_pool_access access, ABT_pool_def * p_def)
Definition at line 42 of file fifo_wait.c.
Referenced by ABTI_pool_create_basic().
void ABTI_pool_print (ABTI_pool * p_pool, FILE * p_os, int indent)
Definition at line 678 of file pool.c.
Referenced by ABT_info_print_pool(), and ABTI_sched_print().
void ABTI_pool_reset_id (void)
Definition at line 885 of file pool.c.
Referenced by ABT_init().
int ABTI_pool_set_consumer (ABTI_pool * p_pool, ABTI_native_thread_id consumer_id)
Definition at line 751 of file pool.c.
Referenced by ABT_pool_add_sched(), ABTI_pool_remove(), ABTI_xstream_init_main_sched(), and ABTI_xstream_update_main_sched().
int ABTI_pool_set_producer (ABTI_pool * p_pool, ABTI_native_thread_id producer_id)
Definition at line 807 of file pool.c.
Referenced by ABTI_pool_push().
int ABTI_sched_config_read (ABT_sched_config config, int type, int num_vars, void ** variables)
Definition at line 253 of file config.c.
Referenced by ABT_sched_config_read(), ABTI_sched_config_read_global(), and sched_init().
int ABTI_sched_config_read_global (ABT_sched_config config, ABT_pool_access * access, ABT_bool * automatic)
Definition at line 222 of file config.c.
Referenced by ABTI_sched_create_basic().
size_t ABTI_sched_config_type_size (ABT_sched_config_type type)
Definition at line 207 of file config.c.
Referenced by ABT_sched_config_create().
int ABTI_sched_create (ABT_sched_def * def, int num_pools, ABT_pool * pools, ABT_sched_config config, ABT_bool automatic, ABTI_sched ** pp_newsched)
Definition at line 562 of file sched.c.
Referenced by ABT_sched_create(), and ABTI_sched_create_basic().
int ABTI_sched_create_basic (ABT_sched_predef predef, int num_pools, ABT_pool * pools, ABT_sched_config config, ABTI_sched ** pp_newsched)
Definition at line 627 of file sched.c.
Referenced by ABT_sched_create_basic(), ABT_xstream_create(), ABT_xstream_create_basic(), ABT_xstream_create_with_rank(), ABT_xstream_set_main_sched(), ABT_xstream_set_main_sched_basic(), and ABTI_xstream_create_primary().
void ABTI_sched_exit (ABTI_sched * p_sched)
Definition at line 557 of file sched.c.
Referenced by ABT_sched_exit(), and ABTI_xstream_check_events().
void ABTI_sched_finish (ABTI_sched * p_sched)
Definition at line 552 of file sched.c.
Referenced by ABT_sched_finish(), and ABTI_xstream_check_events().
int ABTI_sched_free (ABTI_xstream * p_local_xstream, ABTI_sched * p_sched, ABT_bool force_free)
Definition at line 774 of file sched.c.
Referenced by ABT_sched_free(), ABTI_sched_discard_and_free(), and key_destructor_stackable_sched().
ABT_sched_def* ABTI_sched_get_basic_def (void)
Definition at line 37 of file basic.c.
Referenced by ABTI_sched_create_basic(), and ABTI_sched_print().
ABT_sched_def* ABTI_sched_get_basic_wait_def (void)
Definition at line 35 of file basic_wait.c.
Referenced by ABTI_sched_create_basic(), and ABTI_sched_print().
size_t ABTI_sched_get_effective_size (ABTI_xstream * p_local_xstream, ABTI_sched * p_sched)
Definition at line 502 of file sched.c.
Referenced by ABT_xstream_set_main_sched(), ABTI_sched_has_to_stop(), and ABTI_xstream_schedule().
ABTI_sched_kind ABTI_sched_get_kind (ABT_sched_def * def)
Definition at line 863 of file sched.c.
Referenced by ABTI_sched_create(), and ABTI_sched_print().
int ABTI_sched_get_migration_pool (ABTI_sched * , ABTI_pool * , ABTI_pool **)
Definition at line 831 of file sched.c.
Referenced by ABT_thread_migrate_to_sched(), and ABTI_thread_migrate_to_xstream().
ABT_sched_def* ABTI_sched_get_prio_def (void)
Definition at line 27 of file prio.c.
Referenced by ABTI_sched_create_basic(), and ABTI_sched_print().
ABT_sched_def* ABTI_sched_get_randws_def (void)
Definition at line 29 of file randws.c.
Referenced by ABTI_sched_create_basic().
size_t ABTI_sched_get_size (ABTI_sched * p_sched)
Definition at line 441 of file sched.c.
Referenced by ABT_sched_get_size(), and ABTI_sched_print().
size_t ABTI_sched_get_total_size (ABTI_sched * p_sched)
Definition at line 484 of file sched.c.
Referenced by ABT_sched_get_total_size(), and ABTI_sched_print().
ABT_bool ABTI_sched_has_to_stop (ABTI_xstream ** pp_local_xstream, ABTI_sched * p_sched)
Definition at line 311 of file sched.c.
Referenced by ABT_sched_has_to_stop(), and sched_run().
void ABTI_sched_print (ABTI_sched * p_sched, FILE * p_os, int indent, ABT_bool print_sub)
Definition at line 868 of file sched.c.
Referenced by ABT_info_print_sched(), and ABTI_xstream_print().
void ABTI_sched_reset_id (void)
Definition at line 973 of file sched.c.
Referenced by ABT_init().
ABTI_thread_attr* ABTI_thread_attr_dup (ABTI_thread_attr * p_attr)
Definition at line 363 of file thread_attr.c.
Referenced by ABT_thread_get_attr().
void ABTI_thread_attr_get_str (ABTI_thread_attr * p_attr, char * p_buf)
Definition at line 314 of file thread_attr.c.
Referenced by ABTI_thread_attr_print().
void ABTI_thread_attr_print (ABTI_thread_attr * p_attr, FILE * p_os, int indent)
Definition at line 303 of file thread_attr.c.
Referenced by ABT_info_print_thread_attr().
void ABTI_thread_free (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread)
Definition at line 1923 of file thread.c.
Referenced by ABT_thread_free(), ABT_thread_free_many(), ABTI_sched_free(), ABTI_task_create(), ABTI_xstream_terminate_thread(), and ABTI_ythread_create_internal().
ABT_unit_id ABTI_thread_get_id (ABTI_thread * p_thread)
Definition at line 2090 of file thread.c.
Referenced by ABT_finalize(), ABT_task_self_id(), ABT_thread_get_id(), ABT_thread_self_id(), ABT_thread_yield_to(), ABTD_ythread_terminate(), ABTI_info_print_unit(), ABTI_mutex_unlock_se(), ABTI_mutex_wake_de(), ABTI_task_create(), ABTI_thread_free(), ABTI_thread_join(), ABTI_thread_print(), ABTI_thread_revive(), ABTI_xstream_migrate_thread(), ABTI_xstream_schedule_task(), ABTI_xstream_schedule_ythread(), ABTI_xstream_start_primary(), ABTI_xstream_terminate_thread(), ABTI_ythread_context_switch_to_child_internal(), ABTI_ythread_create_internal(), ABTI_ythread_dynamic_promote_ythread(), ABTI_ythread_free_main(), ABTI_ythread_free_main_sched(), ABTI_ythread_htable_switch_low(), ABTI_ythread_set_blocked(), ABTI_ythread_set_ready(), ABTI_ythread_suspend(), and ABTI_ythread_yield().
ABTI_thread_mig_data* ABTI_thread_get_mig_data (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread)
Definition at line 1787 of file thread.c.
Referenced by ABT_thread_set_callback(), ABTI_thread_migrate_to_pool(), and ABTI_xstream_migrate_thread().
int ABTI_thread_migrate_to_pool (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_thread, ABTI_pool * p_pool)
Definition at line 1733 of file thread.c.
Referenced by ABT_thread_migrate_to_pool(), ABT_thread_migrate_to_sched(), and ABTI_thread_migrate_to_xstream().
void ABTI_thread_print (ABTI_thread * p_thread, FILE * p_os, int indent)
Definition at line 2017 of file thread.c.
Referenced by ABT_info_print_thread().
void ABTI_thread_reset_id (void)
Definition at line 2085 of file thread.c.
Referenced by ABT_init().
void ABTI_unit_set_associated_pool (ABT_unit unit, ABTI_pool * p_pool)
Definition at line 48 of file unit.c.
Referenced by ABT_unit_set_associated_pool(), and sched_run().
int ABTI_xstream_check_events (ABTI_xstream * p_xstream, ABT_sched sched)
Definition at line 1065 of file stream.c.
Referenced by ABT_xstream_check_events(), and sched_run().
int ABTI_xstream_create (ABTI_sched * p_sched, ABTI_xstream ** pp_xstream)
Definition at line 63 of file stream.c.
Referenced by ABT_xstream_create(), ABT_xstream_create_basic(), and ABTI_xstream_create_primary().
int ABTI_xstream_create_primary (ABTI_xstream ** pp_xstream)
Definition at line 99 of file stream.c.
Referenced by ABT_init().
int ABTI_xstream_free (ABTI_xstream * p_local_xstream, ABTI_xstream * p_xstream, ABT_bool force_free)
Definition at line 1344 of file stream.c.
Referenced by ABT_finalize(), and ABT_xstream_free().
int ABTI_xstream_init_main_sched (ABTI_xstream * p_xstream, ABTI_sched * p_sched)
Definition at line 1662 of file stream.c.
Referenced by ABT_xstream_create_with_rank(), and ABTI_xstream_create().
int ABTI_xstream_join (ABTI_xstream ** pp_local_xstream, ABTI_xstream * p_xstream)
Definition at line 1256 of file stream.c.
Referenced by ABT_xstream_free(), and ABT_xstream_join().
void* ABTI_xstream_launch_main_sched (void * p_arg)
Definition at line 1876 of file stream.c.
Referenced by ABTI_xstream_start().
int ABTI_xstream_migrate_thread (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread)
Definition at line 1609 of file stream.c.
Referenced by ABTI_xstream_schedule_ythread().
void ABTI_xstream_print (ABTI_xstream * p_xstream, FILE * p_os, int indent, ABT_bool print_sub)
Definition at line 1819 of file stream.c.
Referenced by ABT_info_print_all_xstreams(), and ABT_info_print_xstream().
int ABTI_xstream_run_unit (ABTI_xstream ** pp_local_xstream, ABT_unit unit, ABTI_pool * p_pool)
Definition at line 993 of file stream.c.
Referenced by ABT_xstream_run_unit(), and sched_run().
void ABTI_xstream_schedule (void * p_arg)
Definition at line 1386 of file stream.c.
Referenced by ABTI_xstream_launch_main_sched(), and ABTI_ythread_create_main_sched().
void ABTI_xstream_schedule_task (ABTI_xstream * p_local_xstream, ABTI_thread * p_task)
Definition at line 1566 of file stream.c.
Referenced by ABTI_xstream_run_unit().
int ABTI_xstream_schedule_ythread (ABTI_xstream ** pp_local_xstream, ABTI_ythread * p_ythread)
Definition at line 1445 of file stream.c.
Referenced by ABTI_xstream_run_unit().
int ABTI_xstream_start (ABTI_xstream * p_local_xstream, ABTI_xstream * p_xstream)
Definition at line 245 of file stream.c.
Referenced by ABT_xstream_create(), ABT_xstream_create_basic(), and ABT_xstream_create_with_rank().
int ABTI_xstream_start_primary (ABTI_xstream ** pp_local_xstream, ABTI_xstream * p_xstream, ABTI_ythread * p_ythread)
Definition at line 316 of file stream.c.
Referenced by ABT_init(), and ABTI_xstream_update_main_sched().
int ABTI_xstream_update_main_sched (ABTI_xstream ** pp_local_xstream, ABTI_xstream * p_xstream, ABTI_sched * p_sched)
Definition at line 1702 of file stream.c.
Referenced by ABT_xstream_set_main_sched(), and ABT_xstream_set_main_sched_basic().
int ABTI_ythread_create (ABTI_xstream * p_local_xstream, ABTI_pool * p_pool, void(*)(void *) thread_func, void * arg, ABTI_thread_attr * p_attr, ABTI_ythread ** pp_newthread)
Definition at line 1717 of file thread.c.
int ABTI_ythread_create_main (ABTI_xstream * p_local_xstream, ABTI_xstream * p_xstream, ABTI_ythread ** p_ythread)
Definition at line 1803 of file thread.c.
Referenced by ABT_init().
int ABTI_ythread_create_main_sched (ABTI_xstream * p_local_xstream, ABTI_xstream * p_xstream, ABTI_sched * p_sched)
Definition at line 1843 of file thread.c.
Referenced by ABTI_xstream_launch_main_sched(), ABTI_xstream_start(), and ABTI_xstream_start_primary().
int ABTI_ythread_create_sched (ABTI_xstream * p_local_xstream, ABTI_pool * p_pool, ABTI_sched * p_sched)
Definition at line 1897 of file thread.c.
Referenced by ABT_pool_add_sched().
void ABTI_ythread_free_main (ABTI_xstream * p_local_xstream, ABTI_ythread * p_ythread)
Definition at line 1953 of file thread.c.
Referenced by ABT_finalize(), and ABTI_ythread_create_internal().
void ABTI_ythread_free_main_sched (ABTI_xstream * p_local_xstream, ABTI_ythread * p_ythread)
Definition at line 1977 of file thread.c.
Referenced by ABTI_sched_free(), and ABTI_ythread_create_internal().
ABT_bool ABTI_ythread_htable_add (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 94 of file ythread_htable.c.
ABT_bool ABTI_ythread_htable_add_low (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 158 of file ythread_htable.c.
ABTI_ythread_htable* ABTI_ythread_htable_create (uint32_t num_rows)
Definition at line 9 of file ythread_htable.c.
Referenced by ABTI_mutex_init().
void ABTI_ythread_htable_free (ABTI_ythread_htable * p_htable)
Definition at line 37 of file ythread_htable.c.
Referenced by ABTI_mutex_fini().
ABTI_ythread* ABTI_ythread_htable_pop (ABTI_ythread_htable * p_htable, ABTI_ythread_queue * p_queue)
Definition at line 183 of file ythread_htable.c.
Referenced by ABTI_mutex_unlock_se(), and ABTI_mutex_wake_de().
ABTI_ythread* ABTI_ythread_htable_pop_low (ABTI_ythread_htable * p_htable, ABTI_ythread_queue * p_queue)
Definition at line 206 of file ythread_htable.c.
Referenced by ABTI_mutex_unlock_se(), and ABTI_mutex_wake_de().
void ABTI_ythread_htable_push (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 55 of file ythread_htable.c.
Referenced by ABTI_mutex_wait().
void ABTI_ythread_htable_push_low (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 119 of file ythread_htable.c.
Referenced by ABTI_mutex_wait_low().
ABT_bool ABTI_ythread_htable_switch_low (ABTI_xstream ** pp_local_xstream, ABTI_ythread_queue * p_queue, ABTI_ythread * p_ythread, ABTI_ythread_htable * p_htable, ABT_sync_event_type sync_event_type, void * p_sync)
Definition at line 230 of file ythread_htable.c.
Referenced by ABTI_mutex_lock_low().
int ABTI_ythread_print_stack (ABTI_ythread * p_ythread, FILE * p_os)
Definition at line 105 of file ythread.c.
Referenced by ABT_info_print_thread_stack(), and ABTI_info_print_unit().
int ABTI_ythread_set_blocked (ABTI_ythread * p_ythread)
Definition at line 8 of file ythread.c.
Referenced by ABT_barrier_wait(), ABT_eventual_wait(), ABT_future_wait(), ABT_self_suspend(), ABTI_cond_wait(), ABTI_mutex_wait(), ABTI_mutex_wait_low(), ABTI_thread_join(), ABTI_xstream_join(), ABTI_ythread_htable_add(), and ABTI_ythread_htable_add_low().
int ABTI_ythread_set_ready (ABTI_xstream * p_local_xstream, ABTI_ythread * p_ythread)
Definition at line 60 of file ythread.c.
Referenced by ABT_barrier_wait(), ABT_cond_signal(), ABT_eventual_set(), ABT_future_set(), ABT_thread_resume(), ABTD_ythread_cancel(), ABTD_ythread_terminate(), ABTI_cond_broadcast(), ABTI_mutex_wake_de(), ABTI_xstream_schedule(), and ABTI_ythread_context_switch_to_child_internal().
void ABTI_ythread_suspend (ABTI_xstream ** pp_local_xstream, ABTI_ythread * p_ythread, ABT_sync_event_type sync_event_type, void * p_sync)
Definition at line 40 of file ythread.c.
Referenced by ABT_barrier_wait(), ABT_eventual_wait(), ABT_future_wait(), ABT_self_suspend(), ABTI_cond_wait(), ABTI_mutex_wait(), ABTI_mutex_wait_low(), ABTI_thread_join(), and ABTI_xstream_join().
Variable Documentation
ABTI_global* gp_ABTI_global
Definition at line 14 of file global.c.
Referenced by ABT_info_print_all_xstreams(), ABT_info_query_config(), ABT_self_get_arg(), ABT_self_get_last_pool_id(), ABT_self_get_type(), ABT_self_is_primary(), ABT_self_on_primary_xstream(), ABT_self_set_arg(), ABT_task_self(), ABT_task_self_id(), ABT_thread_exit(), ABT_thread_migrate(), ABT_thread_self(), ABT_thread_self_id(), ABT_xstream_check_events(), ABT_xstream_exit(), ABT_xstream_get_num(), ABT_xstream_self(), ABT_xstream_self_rank(), ABT_xstream_set_rank(), ABTD_affinity_cpuset_apply_default(), ABTD_affinity_finalize(), ABTD_affinity_init(), ABTI_global_get_main(), ABTI_global_get_mutex_max_handovers(), ABTI_global_get_mutex_max_wakeups(), ABTI_global_get_sched_event_freq(), ABTI_global_get_sched_sleep_nsec(), ABTI_global_get_sched_stacksize(), ABTI_global_get_thread_stacksize(), ABTI_info_check_print_all_thread_stacks(), ABTI_info_print_config(), ABTI_ktable_create(), ABTI_mem_free_desc(), ABTI_mem_free_ythread(), ABTI_mutex_init(), ABTI_self_get_type(), ABTI_tool_event_task_update_callback(), ABTI_tool_event_thread_impl(), ABTI_tool_event_thread_update_callback(), ABTI_xstream_return_rank(), ABTI_xstream_set_new_rank(), ABTI_xstream_start(), ABTI_xstream_start_primary(), and ABTI_xstream_take_rank().
ABTI_local_func gp_ABTI_local_func
Definition at line 27 of file local.c.
Referenced by ABTI_local_get_local_ptr(), ABTI_local_get_xstream_uninlined(), and ABTI_local_set_xstream().
ABTD_XSTREAM_LOCAL ABTI_xstream* lp_ABTI_xstream
Definition at line 33 of file local.c.
Referenced by ABTI_local_get_local_ptr_internal(), ABTI_local_get_xstream(), ABTI_local_get_xstream_internal(), and ABTI_local_set_xstream_internal().