ARGOBOTS: src/info.c File Reference
info.c File Reference
#include "abti.h"
Data Structures
struct info_print_unit_arg_t
struct info_pool_set_t
Macros
#define PRINT_STACK_FLAG_UNSET 0
#define PRINT_STACK_FLAG_INITIALIZE 1
#define PRINT_STACK_FLAG_WAIT 2
#define PRINT_STACK_FLAG_FINALIZE 3
Functions
static ABTU_ret_err int info_print_thread_stacks_in_pool (FILE *fp, ABTI_pool *p_pool)
static void info_trigger_print_all_thread_stacks (FILE *fp, double timeout, void(*cb_func)(ABT_bool, void *), void *arg)
int ABT_info_query_config (ABT_info_query_kind query_kind, void *val)
Get the configuration information associated with query_kind.
int ABT_info_print_config (FILE *fp)
Write the configuration information to the output stream.
int ABT_info_print_all_xstreams (FILE *fp)
Write the information of all created ESs to the output stream.
int ABT_info_print_xstream (FILE *fp, ABT_xstream xstream)
Write the information of the target ES to the output stream.
int ABT_info_print_sched (FILE *fp, ABT_sched sched)
Write the information of the target scheduler to the output stream.
int ABT_info_print_pool (FILE *fp, ABT_pool pool)
Write the information of the target pool to the output stream.
int ABT_info_print_thread (FILE *fp, ABT_thread thread)
Write the information of the target ULT to the output stream.
int ABT_info_print_thread_attr (FILE *fp, ABT_thread_attr attr)
Write the information of the target ULT attribute to the output stream.
int ABT_info_print_task (FILE *fp, ABT_task task)
Write the information of the target tasklet to the output stream.
int ABT_info_print_thread_stack (FILE *fp, ABT_thread thread)
Dump the stack of the target thread to the output stream.
int ABT_info_print_thread_stacks_in_pool (FILE *fp, ABT_pool pool)
Dump stack information of all the threads in the target pool.
int ABT_info_trigger_print_all_thread_stacks (FILE *fp, double timeout, void(*cb_func)(ABT_bool, void *), void *arg)
Dump stacks of threads in pools existing in Argobots.
static ABTU_ret_err int print_all_thread_stacks (FILE *fp)
void ABTI_info_check_print_all_thread_stacks (void)
void ABTI_info_print_config (FILE *fp)
static void info_print_unit (void *arg, ABT_unit unit)
static ABTU_ret_err int info_initialize_pool_set (struct info_pool_set_t *p_set)
static void info_finalize_pool_set (struct info_pool_set_t *p_set)
static ABTU_ret_err int info_add_pool_set (ABT_pool pool, struct info_pool_set_t *p_set)
Variables
static ABTD_atomic_int print_stack_flag
static FILE * print_stack_fp = NULL
static double print_stack_timeout = 0.0
static void(* print_cb_func)(ABT_bool, void *) = NULL
static void * print_arg = NULL
static ABTD_atomic_int print_stack_barrier
Macro Definition Documentation
#define PRINT_STACK_FLAG_FINALIZE 3
Definition at line 537 of file info.c.
Referenced by ABTI_info_check_print_all_thread_stacks().
#define PRINT_STACK_FLAG_INITIALIZE 1
Definition at line 535 of file info.c.
Referenced by info_trigger_print_all_thread_stacks().
#define PRINT_STACK_FLAG_UNSET 0
Definition at line 534 of file info.c.
Referenced by ABTI_info_check_print_all_thread_stacks(), and info_trigger_print_all_thread_stacks().
#define PRINT_STACK_FLAG_WAIT 2
Definition at line 536 of file info.c.
Referenced by ABTI_info_check_print_all_thread_stacks(), and info_trigger_print_all_thread_stacks().
Function Documentation
void ABTI_info_check_print_all_thread_stacks (void)
Definition at line 548 of file info.c.
Referenced by ABTI_xstream_check_events().
void ABTI_info_print_config (FILE * fp)
Definition at line 618 of file info.c.
Referenced by ABT_info_print_config(), and init_library().
static ABTU_ret_err int info_add_pool_set (ABT_pool pool, struct info_pool_set_t * p_set) inline static
Definition at line 856 of file info.c.
Referenced by print_all_thread_stacks().
static void info_finalize_pool_set (struct info_pool_set_t * p_set) inline static
Definition at line 851 of file info.c.
Referenced by print_all_thread_stacks().
static ABTU_ret_err int info_initialize_pool_set (struct info_pool_set_t * p_set) inline static
Definition at line 840 of file info.c.
Referenced by print_all_thread_stacks().
static ABTU_ret_err int info_print_thread_stacks_in_pool (FILE * fp, ABTI_pool * p_pool) static
Definition at line 816 of file info.c.
Referenced by ABT_info_print_thread_stacks_in_pool(), and print_all_thread_stacks().
static void info_print_unit (void * arg, ABT_unit unit) static
Definition at line 783 of file info.c.
Referenced by info_print_thread_stacks_in_pool().
static void info_trigger_print_all_thread_stacks (FILE * fp, double timeout, void(*)(ABT_bool, void *) cb_func, void * arg) static
Definition at line 877 of file info.c.
Referenced by ABT_info_trigger_print_all_thread_stacks().
static ABTU_ret_err int print_all_thread_stacks (FILE * fp) static
Definition at line 901 of file info.c.
Referenced by ABTI_info_check_print_all_thread_stacks().
Variable Documentation
void* print_arg = NULL static
Definition at line 544 of file info.c.
void(* print_cb_func)(ABT_bool, void *) = NULL static
Definition at line 543 of file info.c.
Referenced by ABTI_info_check_print_all_thread_stacks(), and info_trigger_print_all_thread_stacks().
ABTD_atomic_int print_stack_barrier static
Initial value:
=
    ABTD_ATOMIC_INT_STATIC_INITIALIZER(0)
Definition at line 545 of file info.c.
ABTD_atomic_int print_stack_flag static
Initial value:
=
    ABTD_ATOMIC_INT_STATIC_INITIALIZER(PRINT_STACK_FLAG_UNSET)
Definition at line 539 of file info.c.
FILE* print_stack_fp = NULL static
Definition at line 541 of file info.c.
double print_stack_timeout = 0.0 static
Definition at line 542 of file info.c.