ARGOBOTS: src/sched/prio.c File Reference
prio.c File Reference
#include "abti.h"
Data Structures
struct sched_data
Functions
static int sched_init (ABT_sched sched, ABT_sched_config config)
static void sched_run (ABT_sched sched)
static int sched_free (ABT_sched)
ABT_sched_def * ABTI_sched_get_prio_def (void)
static sched_data * sched_data_get_ptr (void *data)
Variables
static ABT_sched_def sched_prio_def
Function Documentation
ABTI_sched_get_prio_def()
ABT_sched_def* ABTI_sched_get_prio_def (void)
Definition at line 29 of file prio.c.
Referenced by ABTI_sched_create_basic(), and ABTI_sched_print().
sched_data_get_ptr()
static sched_data* sched_data_get_ptr (void * data) inline static
Definition at line 34 of file prio.c.
Referenced by sched_free(), and sched_run().
sched_free()
static int sched_free (ABT_sched sched) static
Definition at line 134 of file prio.c.
sched_init()
static int sched_init (ABT_sched sched, ABT_sched_config config) static
Definition at line 39 of file prio.c.
sched_run()
static void sched_run (ABT_sched sched) static
Definition at line 85 of file prio.c.
Variable Documentation
sched_prio_def
ABT_sched_def sched_prio_def static
Initial value:
= { .type = ABT_SCHED_TYPE_ULT,
                                        .init = sched_init,
                                        .run = sched_run,
                                        .free = sched_free,
                                        .get_migr_pool = NULL }
Definition at line 14 of file prio.c.
Referenced by ABTI_sched_get_prio_def().