ARGOBOTS: src/include/abti_stream_barrier.h File Reference
abti_stream_barrier.h File Reference
Functions
static ABTI_xstream_barrier * ABTI_xstream_barrier_get_ptr (ABT_xstream_barrier barrier)
static ABT_xstream_barrier ABTI_xstream_barrier_get_handle (ABTI_xstream_barrier *p_barrier)
Function Documentation
ABTI_xstream_barrier_get_handle()
static ABT_xstream_barrier ABTI_xstream_barrier_get_handle (ABTI_xstream_barrier * p_barrier) inline static
Definition at line 26 of file abti_stream_barrier.h.
Referenced by ABT_xstream_barrier_create().
ABTI_xstream_barrier_get_ptr()
static ABTI_xstream_barrier* ABTI_xstream_barrier_get_ptr (ABT_xstream_barrier barrier) inline static
Definition at line 10 of file abti_stream_barrier.h.
Referenced by ABT_xstream_barrier_free(), and ABT_xstream_barrier_wait().