ARGOBOTS: src/sched/basic.c File Reference
basic.c File Reference
#include "abti.h"
Data Structures
struct sched_data
Functions
static int sched_init (ABT_sched sched, ABT_sched_config config)
static void sched_run (ABT_sched sched)
static int sched_free (ABT_sched)
static void sched_sort_pools (int num_pools, ABT_pool *pools)
ABT_sched_def * ABTI_sched_get_basic_def (void)
static sched_data * sched_data_get_ptr (void *data)
static int pool_get_access_num (ABT_pool *p_pool)
static int sched_cmp_pools (const void *p1, const void *p2)
Variables
static ABT_sched_def sched_basic_def
ABT_sched_config_var ABT_sched_basic_freq
Function Documentation
ABT_sched_def* ABTI_sched_get_basic_def (void)
Definition at line 37 of file basic.c.
Referenced by ABTI_sched_create_basic(), and ABTI_sched_print().
static int pool_get_access_num (ABT_pool * p_pool) static
Definition at line 139 of file basic.c.
Referenced by sched_cmp_pools().
static int sched_cmp_pools (const void * p1, const void * p2) static
Definition at line 165 of file basic.c.
Referenced by sched_sort_pools().
static sched_data* sched_data_get_ptr (void * data) inline static
Definition at line 42 of file basic.c.
Referenced by sched_free(), and sched_run().
static int sched_free (ABT_sched sched) static
Definition at line 128 of file basic.c.
static int sched_init (ABT_sched sched, ABT_sched_config config) static
Definition at line 47 of file basic.c.
static void sched_run (ABT_sched sched) static
Definition at line 89 of file basic.c.
static void sched_sort_pools (int num_pools, ABT_pool * pools) static
Definition at line 181 of file basic.c.
Referenced by sched_init().
Variable Documentation
ABT_sched_config_var ABT_sched_basic_freq
Initial value:
= { .idx = 0,
                                              .type = ABT_SCHED_CONFIG_INT }
Definition at line 34 of file basic.c.
ABT_sched_def sched_basic_def static
Initial value:
= {
    .type = ABT_SCHED_TYPE_TASK,
    .init = sched_init,
    .run = sched_run,
    .free = sched_free,
    .get_migr_pool = NULL,
}
Definition at line 17 of file basic.c.
Referenced by ABTI_sched_get_basic_def().