ARGOBOTS: src/include/abti_cond.h File Reference
abti_cond.h File Reference
#include "abti_mutex.h"
Functions
static void ABTI_cond_init (ABTI_cond *p_cond)
static void ABTI_cond_fini (ABTI_cond *p_cond)
static ABTI_cond * ABTI_cond_get_ptr (ABT_cond cond)
static ABT_cond ABTI_cond_get_handle (ABTI_cond *p_cond)
static ABTU_ret_err int ABTI_cond_wait (ABTI_local **pp_local, ABTI_cond *p_cond, ABTI_mutex *p_mutex)
static void ABTI_cond_broadcast (ABTI_local *p_local, ABTI_cond *p_cond)
Function Documentation
ABTI_cond_broadcast()
static void ABTI_cond_broadcast (ABTI_local * p_local, ABTI_cond * p_cond) inline static
Definition at line 81 of file abti_cond.h.
Referenced by ABT_cond_broadcast(), and ABT_rwlock_unlock().
ABTI_cond_fini()
static void ABTI_cond_fini (ABTI_cond * p_cond) inline static
Definition at line 20 of file abti_cond.h.
Referenced by ABT_cond_free(), and ABT_rwlock_free().
ABTI_cond_get_handle()
static ABT_cond ABTI_cond_get_handle (ABTI_cond * p_cond) inline static
Definition at line 43 of file abti_cond.h.
Referenced by ABT_cond_create(), and tool_query().
ABTI_cond_get_ptr()
static ABTI_cond* ABTI_cond_get_ptr (ABT_cond cond) inline static
Definition at line 28 of file abti_cond.h.
Referenced by ABT_cond_broadcast(), ABT_cond_free(), ABT_cond_signal(), ABT_cond_timedwait(), and ABT_cond_wait().
ABTI_cond_init()
static void ABTI_cond_init (ABTI_cond * p_cond) inline static
Definition at line 13 of file abti_cond.h.
Referenced by ABT_cond_create(), and ABT_rwlock_create().
ABTI_cond_wait()
static ABTU_ret_err int ABTI_cond_wait (ABTI_local ** pp_local, ABTI_cond * p_cond, ABTI_mutex * p_mutex) inline static
Definition at line 59 of file abti_cond.h.
Referenced by ABT_cond_wait(), ABT_rwlock_rdlock(), and ABT_rwlock_wrlock().