ARGOBOTS: src/include/abti_stream.h File Reference
abti_stream.h File Reference
Functions
static ABTI_xstream * ABTI_xstream_get_ptr (ABT_xstream xstream)
static ABT_xstream ABTI_xstream_get_handle (ABTI_xstream *p_xstream)
static void ABTI_xstream_set_request (ABTI_xstream *p_xstream, uint32_t req)
static void ABTI_xstream_unset_request (ABTI_xstream *p_xstream, uint32_t req)
static ABTI_pool * ABTI_xstream_get_main_pool (ABTI_xstream *p_xstream)
static void ABTI_xstream_terminate_thread (ABTI_local *p_local, ABTI_thread *p_thread)
static ABTI_native_thread_id ABTI_xstream_get_native_thread_id (ABTI_xstream *p_xstream)
static ABTI_local * ABTI_xstream_get_local (ABTI_xstream *p_xstream)
Function Documentation
static ABT_xstream ABTI_xstream_get_handle (ABTI_xstream * p_xstream) inline static
Definition at line 26 of file abti_stream.h.
Referenced by ABT_thread_get_last_xstream(), ABT_xstream_create(), ABT_xstream_create_basic(), ABT_xstream_create_with_rank(), ABT_xstream_self(), ABTI_tool_event_thread_impl(), and ABTI_tool_query().
static ABTI_local* ABTI_xstream_get_local (ABTI_xstream * p_xstream) inline static
Definition at line 86 of file abti_stream.h.
Referenced by ABT_cond_timedwait(), ABT_finalize(), ABT_init(), ABT_key_set(), ABT_xstream_set_main_sched(), ABTD_ythread_cancel(), ABTD_ythread_terminate(), ABTI_cond_wait(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_mutex_unlock_se(), ABTI_sched_has_to_stop(), ABTI_thread_join(), ABTI_thread_migrate_to_pool(), ABTI_tool_event_thread_cancel_impl(), ABTI_tool_event_thread_finish_impl(), ABTI_tool_event_thread_run_impl(), ABTI_tool_event_ythread_suspend_impl(), ABTI_tool_event_ythread_yield_impl(), ABTI_xstream_join(), ABTI_xstream_launch_main_sched(), ABTI_xstream_schedule_task(), ABTI_xstream_schedule_ythread(), ABTI_xstream_start_primary(), ABTI_xstream_update_main_sched(), ABTI_ythread_context_switch_to_child_internal(), ABTI_ythread_htable_switch_low(), and sched_run().
static ABTI_pool* ABTI_xstream_get_main_pool (ABTI_xstream * p_xstream) inline static
Definition at line 54 of file abti_stream.h.
Referenced by ABT_task_create_on_xstream(), and ABT_thread_create_on_xstream().
static ABTI_native_thread_id ABTI_xstream_get_native_thread_id (ABTI_xstream * p_xstream) inline static
Definition at line 81 of file abti_stream.h.
Referenced by ABT_thread_yield_to(), ABTI_thread_join(), ABTI_xstream_init_main_sched(), ABTI_xstream_schedule_ythread(), and ABTI_xstream_update_main_sched().
static ABTI_xstream* ABTI_xstream_get_ptr (ABT_xstream xstream) inline static
Definition at line 11 of file abti_stream.h.
Referenced by ABT_info_print_xstream(), ABT_task_create_on_xstream(), ABT_thread_create_on_xstream(), ABT_thread_migrate_to_xstream(), ABT_xstream_cancel(), ABT_xstream_equal(), ABT_xstream_free(), ABT_xstream_get_affinity(), ABT_xstream_get_cpubind(), ABT_xstream_get_main_pools(), ABT_xstream_get_main_sched(), ABT_xstream_get_rank(), ABT_xstream_get_state(), ABT_xstream_is_primary(), ABT_xstream_join(), ABT_xstream_revive(), ABT_xstream_set_affinity(), ABT_xstream_set_cpubind(), ABT_xstream_set_main_sched(), ABT_xstream_set_main_sched_basic(), and ABT_xstream_set_rank().
static void ABTI_xstream_set_request (ABTI_xstream * p_xstream, uint32_t req) inline static
Definition at line 41 of file abti_stream.h.
Referenced by ABT_finalize(), ABT_xstream_cancel(), ABT_xstream_exit(), and ABTI_xstream_join().
static void ABTI_xstream_terminate_thread (ABTI_local * p_local, ABTI_thread * p_thread) inline static
Definition at line 60 of file abti_stream.h.
Referenced by ABTI_xstream_schedule_task(), and ABTI_xstream_schedule_ythread().
static void ABTI_xstream_unset_request (ABTI_xstream * p_xstream, uint32_t req) inline static
Definition at line 47 of file abti_stream.h.