ARGOBOTS: src/include/abti_mutex_attr.h File Reference
abti_mutex_attr.h File Reference
Functions
static ABTI_mutex_attr * ABTI_mutex_attr_get_ptr (ABT_mutex_attr attr)
static ABT_mutex_attr ABTI_mutex_attr_get_handle (ABTI_mutex_attr *p_attr)
Function Documentation
static ABT_mutex_attr ABTI_mutex_attr_get_handle (ABTI_mutex_attr * p_attr) inline static
Definition at line 26 of file abti_mutex_attr.h.
Referenced by ABT_mutex_attr_create().
static ABTI_mutex_attr* ABTI_mutex_attr_get_ptr (ABT_mutex_attr attr) inline static
Definition at line 11 of file abti_mutex_attr.h.
Referenced by ABT_mutex_attr_free(), ABT_mutex_attr_set_recursive(), and ABT_mutex_create_with_attr().