ARGOBOTS: src/thread_htable.c File Reference
thread_htable.c File Reference
#include "abti.h"
#include "abti_thread_htable.h"
Functions
ABTI_thread_htable * ABTI_thread_htable_create (uint32_t num_rows)
void ABTI_thread_htable_free (ABTI_thread_htable *p_htable)
void ABTI_thread_htable_push (ABTI_thread_htable *p_htable, int idx, ABTI_thread *p_thread)
ABT_bool ABTI_thread_htable_add (ABTI_thread_htable *p_htable, int idx, ABTI_thread *p_thread)
void ABTI_thread_htable_push_low (ABTI_thread_htable *p_htable, int idx, ABTI_thread *p_thread)
ABT_bool ABTI_thread_htable_add_low (ABTI_thread_htable *p_htable, int idx, ABTI_thread *p_thread)
ABTI_thread * ABTI_thread_htable_pop (ABTI_thread_htable *p_htable, ABTI_thread_queue *p_queue)
ABTI_thread * ABTI_thread_htable_pop_low (ABTI_thread_htable *p_htable, ABTI_thread_queue *p_queue)
ABT_bool ABTI_thread_htable_switch_low (ABTI_xstream **pp_local_xstream, ABTI_thread_queue *p_queue, ABTI_thread *p_thread, ABTI_thread_htable *p_htable, ABT_sync_event_type sync_event_type, void *p_sync)
Function Documentation
ABT_bool ABTI_thread_htable_add (ABTI_thread_htable * p_htable, int idx, ABTI_thread * p_thread)
Definition at line 91 of file thread_htable.c.
ABT_bool ABTI_thread_htable_add_low (ABTI_thread_htable * p_htable, int idx, ABTI_thread * p_thread)
Definition at line 152 of file thread_htable.c.
ABTI_thread_htable* ABTI_thread_htable_create (uint32_t num_rows)
Definition at line 9 of file thread_htable.c.
Referenced by ABTI_mutex_init().
void ABTI_thread_htable_free (ABTI_thread_htable * p_htable)
Definition at line 37 of file thread_htable.c.
Referenced by ABTI_mutex_fini().
ABTI_thread* ABTI_thread_htable_pop (ABTI_thread_htable * p_htable, ABTI_thread_queue * p_queue)
Definition at line 177 of file thread_htable.c.
Referenced by ABTI_mutex_unlock_se(), and ABTI_mutex_wake_de().
ABTI_thread* ABTI_thread_htable_pop_low (ABTI_thread_htable * p_htable, ABTI_thread_queue * p_queue)
Definition at line 200 of file thread_htable.c.
Referenced by ABTI_mutex_unlock_se(), and ABTI_mutex_wake_de().
void ABTI_thread_htable_push (ABTI_thread_htable * p_htable, int idx, ABTI_thread * p_thread)
Definition at line 55 of file thread_htable.c.
Referenced by ABTI_mutex_wait().
void ABTI_thread_htable_push_low (ABTI_thread_htable * p_htable, int idx, ABTI_thread * p_thread)
Definition at line 116 of file thread_htable.c.
Referenced by ABTI_mutex_wait_low().
ABT_bool ABTI_thread_htable_switch_low (ABTI_xstream ** pp_local_xstream, ABTI_thread_queue * p_queue, ABTI_thread * p_thread, ABTI_thread_htable * p_htable, ABT_sync_event_type sync_event_type, void * p_sync)
Definition at line 223 of file thread_htable.c.
Referenced by ABTI_mutex_lock_low().