ARGOBOTS: src/ythread_htable.c File Reference
ythread_htable.c File Reference
#include "abti.h"
#include "abti_ythread_htable.h"
Functions
ABTI_ythread_htable * ABTI_ythread_htable_create (uint32_t num_rows)
void ABTI_ythread_htable_free (ABTI_ythread_htable *p_htable)
void ABTI_ythread_htable_push (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
ABT_bool ABTI_ythread_htable_add (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
void ABTI_ythread_htable_push_low (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
ABT_bool ABTI_ythread_htable_add_low (ABTI_ythread_htable *p_htable, int idx, ABTI_ythread *p_ythread)
ABTI_ythread * ABTI_ythread_htable_pop (ABTI_ythread_htable *p_htable, ABTI_ythread_queue *p_queue)
ABTI_ythread * ABTI_ythread_htable_pop_low (ABTI_ythread_htable *p_htable, ABTI_ythread_queue *p_queue)
ABT_bool ABTI_ythread_htable_switch_low (ABTI_xstream **pp_local_xstream, ABTI_ythread_queue *p_queue, ABTI_ythread *p_ythread, ABTI_ythread_htable *p_htable, ABT_sync_event_type sync_event_type, void *p_sync)
Function Documentation
ABT_bool ABTI_ythread_htable_add (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 94 of file ythread_htable.c.
ABT_bool ABTI_ythread_htable_add_low (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 158 of file ythread_htable.c.
ABTI_ythread_htable* ABTI_ythread_htable_create (uint32_t num_rows)
Definition at line 9 of file ythread_htable.c.
Referenced by ABTI_mutex_init().
void ABTI_ythread_htable_free (ABTI_ythread_htable * p_htable)
Definition at line 37 of file ythread_htable.c.
Referenced by ABTI_mutex_fini().
ABTI_ythread* ABTI_ythread_htable_pop (ABTI_ythread_htable * p_htable, ABTI_ythread_queue * p_queue)
Definition at line 183 of file ythread_htable.c.
Referenced by ABTI_mutex_unlock_se(), and ABTI_mutex_wake_de().
ABTI_ythread* ABTI_ythread_htable_pop_low (ABTI_ythread_htable * p_htable, ABTI_ythread_queue * p_queue)
Definition at line 206 of file ythread_htable.c.
Referenced by ABTI_mutex_unlock_se(), and ABTI_mutex_wake_de().
void ABTI_ythread_htable_push (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 55 of file ythread_htable.c.
Referenced by ABTI_mutex_wait().
void ABTI_ythread_htable_push_low (ABTI_ythread_htable * p_htable, int idx, ABTI_ythread * p_ythread)
Definition at line 119 of file ythread_htable.c.
Referenced by ABTI_mutex_wait_low().
ABT_bool ABTI_ythread_htable_switch_low (ABTI_xstream ** pp_local_xstream, ABTI_ythread_queue * p_queue, ABTI_ythread * p_ythread, ABTI_ythread_htable * p_htable, ABT_sync_event_type sync_event_type, void * p_sync)
Definition at line 230 of file ythread_htable.c.
Referenced by ABTI_mutex_lock_low().