ARGOBOTS: ULT Attributes (Private)
ULT Attributes (Private)
Functions
static ABTI_thread_attr * ABTI_thread_attr_get_ptr (ABT_thread_attr attr)
Get ABTI_thread_attr pointer from ABT_thread_attr handle.
static ABT_thread_attr ABTI_thread_attr_get_handle (ABTI_thread_attr *p_attr)
Get ABT_thread_attr handle from ABTI_thread_attr pointer.
void ABTI_thread_attr_print (ABTI_thread_attr *p_attr, FILE *p_os, int indent)
Print field values of ABTI_thread_attr.
Detailed Description
This group combines private APIs for ULT attributes.
Function Documentation
static ABT_thread_attr ABTI_thread_attr_get_handle (ABTI_thread_attr * p_attr) inline static
Get ABT_thread_attr handle from ABTI_thread_attr pointer.
ABTI_thread_attr_get_handle() returns ABT_thread_attr handle corresponding to ABTI_thread_attr pointer attr. If attr is NULL, ABT_THREAD_NULL is returned.
Parameters
[in] p_attr pointer to ABTI_thread_attr
Returns
ABT_thread_attr handle
Definition at line 49 of file abti_thread_attr.h.
Referenced by ABT_thread_attr_create(), and ABT_thread_get_attr().
static ABTI_thread_attr* ABTI_thread_attr_get_ptr (ABT_thread_attr attr) inline static
Get ABTI_thread_attr pointer from ABT_thread_attr handle.
ABTI_thread_attr_get_ptr() returns ABTI_thread_attr pointer corresponding to ABT_thread_attr handle attr. If attr is ABT_THREAD_NULL, NULL is returned.
Parameters
[in] attr handle to the ULT attribute
Returns
ABTI_thread_attr pointer
Definition at line 22 of file abti_thread_attr.h.
Referenced by ABT_info_print_thread_attr(), ABT_thread_attr_free(), ABT_thread_attr_get_stack(), ABT_thread_attr_get_stacksize(), ABT_thread_attr_set_callback(), ABT_thread_attr_set_migratable(), ABT_thread_attr_set_stack(), ABT_thread_attr_set_stacksize(), ABT_thread_create(), ABT_thread_create_many(), and ABT_thread_create_on_xstream().
void ABTI_thread_attr_print (ABTI_thread_attr * p_attr, FILE * p_os, int indent)
Print field values of ABTI_thread_attr.
ABTI_thread_attr_print() prints out values of all fields in ABTI_thread_attr struct.
Parameters
[in] p_attr pointer to ABTI_thread_attr
[in] p_os pointer to a FILE object (output stream)
[in] indent amount of space to indent
Returns
Error code
Return values
ABT_SUCCESS on success
Definition at line 320 of file thread_attr.c.
Referenced by ABT_info_print_thread_attr().