ARGOBOTS: src/pool/pool_config.c File Reference
pool_config.c File Reference
#include "abti.h"
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
Data Structures
struct pool_config_element
Macros
#define POOL_CONFIG_HTABLE_SIZE 8
Functions
static void pool_config_create_element_int (pool_config_element *p_elem, int val)
static void pool_config_create_element_double (pool_config_element *p_elem, double val)
static void pool_config_create_element_ptr (pool_config_element *p_elem, void *ptr)
static ABTU_ret_err int pool_config_create_element_typed (pool_config_element *p_elem, ABT_pool_config_type type, const void *p_val)
static void pool_config_read_element (const pool_config_element *p_elem, void *ptr)
int ABT_pool_config_create (ABT_pool_config *config)
Create a new pool configuration.
int ABT_pool_config_free (ABT_pool_config *config)
Free a pool configuration.
int ABT_pool_config_set (ABT_pool_config config, int key, ABT_pool_config_type type, const void *val)
Register a value to a pool configuration.
int ABT_pool_config_get (ABT_pool_config config, int key, ABT_pool_config_type *type, void *val)
Retrieve a value from a pool configuration.
Variables
const ABT_pool_config_var ABT_pool_config_automatic
Predefined ABT_pool_config_var to configure whether the pool is freed automatically or not.
Macro Definition Documentation
POOL_CONFIG_HTABLE_SIZE
#define POOL_CONFIG_HTABLE_SIZE 8
Definition at line 12 of file pool_config.c.
Function Documentation
pool_config_create_element_double()
static void pool_config_create_element_double (pool_config_element * p_elem, double val) static
Definition at line 297 of file pool_config.c.
Referenced by pool_config_create_element_typed().
pool_config_create_element_int()
static void pool_config_create_element_int (pool_config_element * p_elem, int val) static
Definition at line 290 of file pool_config.c.
Referenced by pool_config_create_element_typed().
pool_config_create_element_ptr()
static void pool_config_create_element_ptr (pool_config_element * p_elem, void * ptr) static
Definition at line 305 of file pool_config.c.
Referenced by pool_config_create_element_typed().
pool_config_create_element_typed()
static ABTU_ret_err int pool_config_create_element_typed (pool_config_element * p_elem, ABT_pool_config_type type, const void * p_val) static
Definition at line 314 of file pool_config.c.
pool_config_read_element()
static void pool_config_read_element (const pool_config_element * p_elem, void * ptr) static
Definition at line 336 of file pool_config.c.