ARGOBOTS: src/include/abti_self.h File Reference
abti_self.h File Reference
Functions
static ABTI_native_thread_id ABTI_self_get_native_thread_id (ABTI_xstream *p_local_xstream)
static ABTI_unit_id ABTI_self_get_unit_id (ABTI_xstream *p_local_xstream)
static ABTI_unit_type ABTI_self_get_type (ABTI_xstream *p_local_xstream)
Function Documentation
static ABTI_native_thread_id ABTI_self_get_native_thread_id (ABTI_xstream * p_local_xstream) inline static
Definition at line 10 of file abti_self.h.
Referenced by ABT_pool_push(), ABT_pool_remove(), ABT_thread_yield_to(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_sched_get_effective_size(), ABTI_task_create(), ABTI_task_revive(), ABTI_thread_create_internal(), ABTI_thread_join(), ABTI_thread_revive(), ABTI_thread_set_ready(), ABTI_xstream_join(), ABTI_xstream_migrate_thread(), ABTI_xstream_schedule_thread(), and ABTI_xstream_update_main_sched().
static ABTI_unit_type ABTI_self_get_type (ABTI_xstream * p_local_xstream) inline static
Definition at line 36 of file abti_self.h.
Referenced by ABT_cond_timedwait(), ABT_self_get_type(), ABT_task_free(), ABT_task_join(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_mutex_unlock_se(), ABTI_thread_join(), and ABTI_xstream_join().
static ABTI_unit_id ABTI_self_get_unit_id (ABTI_xstream * p_local_xstream) inline static
Definition at line 23 of file abti_self.h.
Referenced by ABT_mutex_lock(), ABT_mutex_lock_low(), ABT_mutex_spinlock(), ABT_mutex_trylock(), ABT_mutex_unlock(), and ABT_mutex_unlock_se().