ARGOBOTS: src/include/abtd_spinlock.h File Reference
abtd_spinlock.h File Reference
Data Structures
struct ABTD_spinlock
Macros
#define ABTD_SPINLOCK_STATIC_INITIALIZER()
Typedefs
typedef struct ABTD_spinlock ABTD_spinlock
Functions
static ABT_bool ABTD_spinlock_is_locked (const ABTD_spinlock *p_lock)
static void ABTD_spinlock_clear (ABTD_spinlock *p_lock)
static void ABTD_spinlock_acquire (ABTD_spinlock *p_lock)
static ABT_bool ABTD_spinlock_try_acquire (ABTD_spinlock *p_lock)
static void ABTD_spinlock_release (ABTD_spinlock *p_lock)
Macro Definition Documentation
ABTD_SPINLOCK_STATIC_INITIALIZER
#define ABTD_SPINLOCK_STATIC_INITIALIZER ()
Value:
    {                                                                          \
        ABTD_ATOMIC_BOOL_STATIC_INITIALIZER(0)                                 \
    }
Definition at line 13 of file abtd_spinlock.h.
Typedef Documentation
ABTD_spinlock
typedef struct ABTD_spinlock ABTD_spinlock
Function Documentation
ABTD_spinlock_acquire()
static void ABTD_spinlock_acquire (ABTD_spinlock * p_lock) inline static
Definition at line 28 of file abtd_spinlock.h.
Referenced by ABT_barrier_free(), ABT_barrier_wait(), ABT_cond_signal(), ABT_cond_timedwait(), ABT_eventual_free(), ABT_eventual_test(), ABT_eventual_wait(), ABT_finalize(), ABT_future_free(), ABT_future_reset(), ABT_future_set(), ABT_future_wait(), ABT_info_print_all_xstreams(), ABT_init(), ABT_xstream_barrier_wait(), ABTD_futex_timedwait_and_unlock(), ABTI_cond_broadcast(), ABTI_cond_fini(), ABTI_cond_wait(), ABTI_ktable_set_impl(), ABTI_mem_free_desc(), ABTI_mem_free_nythread_mempool_impl(), ABTI_mem_free_thread(), ABTI_mem_free_ythread_desc_mempool_impl(), ABTI_mutex_fini(), ABTI_mutex_lock_no_recursion(), ABTI_mutex_spinlock_no_recursion(), ABTI_mutex_unlock_no_recursion(), ABTI_sync_lifo_pop(), ABTI_sync_lifo_push(), ABTI_tool_event_thread_update_callback(), ABTI_waitlist_wait_and_unlock(), ABTI_waitlist_wait_timedout_and_unlock(), mem_pool_return_partial_bucket(), pool_print_all(), pool_push_many_shared(), pool_push_shared(), pool_remove_shared(), unit_map_thread(), and unit_unmap_thread().
ABTD_spinlock_clear()
static void ABTD_spinlock_clear (ABTD_spinlock * p_lock) inline static
Definition at line 23 of file abtd_spinlock.h.
Referenced by ABT_barrier_create(), ABT_eventual_create(), ABT_future_create(), ABT_xstream_barrier_create(), ABTI_cond_init(), ABTI_ktable_create(), ABTI_mem_pool_init_global_pool(), ABTI_mutex_init(), ABTI_sync_lifo_init(), init_library(), pool_init(), and unit_init_hash_table().
ABTD_spinlock_is_locked()
static ABT_bool ABTD_spinlock_is_locked (const ABTD_spinlock * p_lock) inline static
Definition at line 18 of file abtd_spinlock.h.
Referenced by ABTD_spinlock_acquire(), ABTI_mutex_is_locked(), ABTI_waitlist_wait_and_unlock(), ABTI_waitlist_wait_timedout_and_unlock(), thread_queue_acquire_spinlock_if_not_empty(), and unit_finalize_hash_table().
ABTD_spinlock_release()
static void ABTD_spinlock_release (ABTD_spinlock * p_lock) inline static
Definition at line 42 of file abtd_spinlock.h.
Referenced by ABT_barrier_wait(), ABT_cond_signal(), ABT_cond_timedwait(), ABT_eventual_test(), ABT_eventual_wait(), ABT_finalize(), ABT_future_reset(), ABT_future_set(), ABT_future_wait(), ABT_info_print_all_xstreams(), ABT_init(), ABT_xstream_barrier_wait(), ABTD_futex_timedwait_and_unlock(), ABTD_futex_wait_and_unlock(), ABTI_cond_broadcast(), ABTI_cond_wait(), ABTI_ktable_set_impl(), ABTI_mem_free_desc(), ABTI_mem_free_nythread_mempool_impl(), ABTI_mem_free_thread(), ABTI_mem_free_ythread_desc_mempool_impl(), ABTI_mutex_lock_no_recursion(), ABTI_mutex_unlock_no_recursion(), ABTI_sync_lifo_pop(), ABTI_sync_lifo_push(), ABTI_tool_event_thread_update_callback(), ABTI_waitlist_wait_and_unlock(), ABTI_waitlist_wait_timedout_and_unlock(), ABTI_ythread_callback_suspend_unlock(), mem_pool_return_partial_bucket(), pool_pop_many_shared(), pool_pop_shared(), pool_pop_timedwait(), pool_pop_wait(), pool_print_all(), pool_push_many_shared(), pool_push_shared(), pool_remove_shared(), unit_map_thread(), and unit_unmap_thread().
ABTD_spinlock_try_acquire()
static ABT_bool ABTD_spinlock_try_acquire (ABTD_spinlock * p_lock) inline static
Definition at line 37 of file abtd_spinlock.h.
Referenced by ABTI_mutex_lock_no_recursion(), ABTI_mutex_trylock_no_recursion(), and thread_queue_acquire_spinlock_if_not_empty().