ARGOBOTS: src/include/abtu.h File Reference
abtu.h File Reference
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "abt_config.h"
Data Structures
struct ABTU_hashtable_element
struct ABTU_hashtable
Macros
#define ABTU_likely(cond) __builtin_expect(!!(cond), 1)
#define ABTU_unlikely(cond) __builtin_expect(!!(cond), 0)
#define ABTU_noreturn __attribute__((noreturn))
#define ABTU_unreachable() __builtin_unreachable()
#define ABTU_alignof(type) (__alignof__(type))
#define ABTU_MAX_ALIGNMENT ABTU_max_size(ABTU_alignof(long double), ABTU_alignof(long long))
#define ABTU_ret_err __attribute__((warn_unused_result))
#define ABTU_align_member_var(size) __attribute__((aligned(size)))
#define ABTU_no_sanitize_address
Typedefs
typedef enum ABTU_MEM_LARGEPAGE_TYPE ABTU_MEM_LARGEPAGE_TYPE
typedef struct ABTU_hashtable_element ABTU_hashtable_element
typedef struct ABTU_hashtable ABTU_hashtable
Enumerations
enum ABTU_MEM_LARGEPAGE_TYPE { ABTU_MEM_LARGEPAGE_MALLOC, ABTU_MEM_LARGEPAGE_MEMALIGN, ABTU_MEM_LARGEPAGE_MMAP, ABTU_MEM_LARGEPAGE_MMAP_HUGEPAGE }
Functions
static int ABTU_max_int (int a, int b)
static int32_t ABTU_max_int32 (int32_t a, int32_t b)
static uint32_t ABTU_max_uint32 (uint32_t a, uint32_t b)
static int64_t ABTU_max_int64 (int64_t a, int64_t b)
static uint64_t ABTU_max_uint64 (uint64_t a, uint64_t b)
static size_t ABTU_max_size (size_t a, size_t b)
static int ABTU_min_int (int a, int b)
static int32_t ABTU_min_int32 (int32_t a, int32_t b)
static uint32_t ABTU_min_uint32 (uint32_t a, uint32_t b)
static int64_t ABTU_min_int64 (int64_t a, int64_t b)
static uint64_t ABTU_min_uint64 (uint64_t a, uint64_t b)
static size_t ABTU_min_size (size_t a, size_t b)
static uint32_t ABTU_roundup_uint32 (uint32_t val, uint32_t multiple)
static uint64_t ABTU_roundup_uint64 (uint64_t val, uint64_t multiple)
static size_t ABTU_roundup_size (size_t val, size_t multiple)
static void * ABTU_roundup_ptr (void *ptr, size_t multiple)
static ABTU_ret_err int ABTU_memalign (size_t alignment, size_t size, void **p_ptr)
static void ABTU_free (void *ptr)
static ABTU_ret_err int ABTU_malloc (size_t size, void **p_ptr)
static ABTU_ret_err int ABTU_calloc (size_t num, size_t size, void **p_ptr)
static ABTU_ret_err int ABTU_realloc (size_t old_size, size_t new_size, void **p_ptr)
int ABTU_is_supported_largepage_type (size_t size, size_t alignment_hint, ABTU_MEM_LARGEPAGE_TYPE requested)
ABTU_ret_err int ABTU_alloc_largepage (size_t size, size_t alignment_hint, const ABTU_MEM_LARGEPAGE_TYPE *requested_types, int num_requested_types, ABTU_MEM_LARGEPAGE_TYPE *p_actual, void **p_ptr)
void ABTU_free_largepage (void *ptr, size_t size, ABTU_MEM_LARGEPAGE_TYPE type)
ABTU_ret_err int ABTU_mprotect (void *addr, size_t size, ABT_bool protect)
ABTU_ret_err int ABTU_atoi (const char *str, int *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atoui32 (const char *str, uint32_t *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atoui64 (const char *str, uint64_t *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_atosz (const char *str, size_t *p_val, ABT_bool *p_overflow)
ABTU_ret_err int ABTU_hashtable_create (size_t num_entries, size_t data_size, ABTU_hashtable **pp_hashtable)
void ABTU_hashtable_free (ABTU_hashtable *p_hashtable)
void ABTU_hashtable_get (const ABTU_hashtable *p_hashtable, int key, void *data, int *found)
ABTU_ret_err int ABTU_hashtable_set (ABTU_hashtable *p_hashtable, int key, const void *data, int *overwritten)
void ABTU_hashtable_delete (ABTU_hashtable *p_hashtable, int key, int *deleted)
Macro Definition Documentation
ABTU_align_member_var
#define ABTU_align_member_var (size) __attribute__((aligned(size)))
Definition at line 170 of file abtu.h.
ABTU_alignof
#define ABTU_alignof (type) (__alignof__(type))
Definition at line 145 of file abtu.h.
ABTU_likely
#define ABTU_likely (cond) __builtin_expect(!!(cond), 1)
Definition at line 119 of file abtu.h.
ABTU_MAX_ALIGNMENT
#define ABTU_MAX_ALIGNMENT ABTU_max_size(ABTU_alignof(long double), ABTU_alignof(long long))
Definition at line 151 of file abtu.h.
ABTU_no_sanitize_address
#define ABTU_no_sanitize_address
Definition at line 211 of file abtu.h.
ABTU_noreturn
#define ABTU_noreturn __attribute__((noreturn))
Definition at line 127 of file abtu.h.
ABTU_ret_err
#define ABTU_ret_err __attribute__((warn_unused_result))
Definition at line 155 of file abtu.h.
ABTU_unlikely
#define ABTU_unlikely (cond) __builtin_expect(!!(cond), 0)
Definition at line 120 of file abtu.h.
ABTU_unreachable
#define ABTU_unreachable () __builtin_unreachable()
Definition at line 133 of file abtu.h.
Typedef Documentation
ABTU_hashtable
typedef struct ABTU_hashtable ABTU_hashtable
ABTU_hashtable_element
typedef struct ABTU_hashtable_element ABTU_hashtable_element
ABTU_MEM_LARGEPAGE_TYPE
typedef enum ABTU_MEM_LARGEPAGE_TYPE ABTU_MEM_LARGEPAGE_TYPE
Enumeration Type Documentation
ABTU_MEM_LARGEPAGE_TYPE
enum ABTU_MEM_LARGEPAGE_TYPE
Enumerator
ABTU_MEM_LARGEPAGE_MALLOC
ABTU_MEM_LARGEPAGE_MEMALIGN
ABTU_MEM_LARGEPAGE_MMAP
ABTU_MEM_LARGEPAGE_MMAP_HUGEPAGE
Definition at line 308 of file abtu.h.
Function Documentation
ABTU_alloc_largepage()
ABTU_ret_err int ABTU_alloc_largepage (size_t size, size_t alignment_hint, const ABTU_MEM_LARGEPAGE_TYPE * requested_types, int num_requested_types, ABTU_MEM_LARGEPAGE_TYPE * p_actual, void ** p_ptr)
Definition at line 90 of file largepage.c.
Referenced by ABTI_mem_pool_take_bucket().
ABTU_atoi()
ABTU_ret_err int ABTU_atoi (const char * str, int * p_val, ABT_bool * p_overflow)
Definition at line 11 of file atoi.c.
Referenced by load_env_int().
ABTU_atosz()
ABTU_ret_err int ABTU_atosz (const char * str, size_t * p_val, ABT_bool * p_overflow)
Definition at line 85 of file atoi.c.
Referenced by load_env_size().
ABTU_atoui32()
ABTU_ret_err int ABTU_atoui32 (const char * str, uint32_t * p_val, ABT_bool * p_overflow)
Definition at line 39 of file atoi.c.
Referenced by ABTU_atosz(), and load_env_uint32().
ABTU_atoui64()
ABTU_ret_err int ABTU_atoui64 (const char * str, uint64_t * p_val, ABT_bool * p_overflow)
Definition at line 65 of file atoi.c.
Referenced by ABTU_atosz(), and load_env_uint64().
ABTU_calloc()
static ABTU_ret_err int ABTU_calloc (size_t num, size_t size, void ** p_ptr) inline static
Definition at line 244 of file abtu.h.
Referenced by ABT_pool_config_create(), ABT_pool_user_def_create(), ABT_sched_config_create(), ABTD_affinity_init(), ABTI_thread_get_mig_data(), ABTU_hashtable_create(), ABTU_hashtable_set(), list_calloc(), and ythread_create().
ABTU_free()
static void ABTU_free (void * ptr) inline static
Definition at line 228 of file abtu.h.
Referenced by ABT_barrier_free(), ABT_cond_free(), ABT_eventual_create(), ABT_eventual_free(), ABT_future_create(), ABT_future_free(), ABT_key_free(), ABT_mutex_attr_free(), ABT_mutex_free(), ABT_pool_config_create(), ABT_pool_config_free(), ABT_pool_user_def_free(), ABT_rwlock_free(), ABT_sched_config_create(), ABT_sched_config_free(), ABT_thread_attr_free(), ABT_xstream_barrier_create(), ABT_xstream_barrier_free(), ABTD_affinity_cpuset_destroy(), ABTD_affinity_finalize(), ABTD_affinity_init(), ABTI_ktable_free(), ABTI_mem_free_desc(), ABTI_mem_free_thread(), ABTI_pool_free(), ABTI_sched_create_basic(), ABTI_sched_free(), ABTI_thread_get_mig_data(), ABTU_free_largepage(), ABTU_hashtable_delete(), ABTU_hashtable_free(), ABTU_is_supported_largepage_type(), ABTU_realloc(), finailze_library(), init_library(), list_free_all(), pool_create(), pool_free(), pool_init(), pool_push_threads_ex(), sched_create(), sched_free(), sched_init(), unit_finalize_hash_table(), xstream_create(), xstream_update_max_xstreams(), and ythread_create().
ABTU_free_largepage()
void ABTU_free_largepage (void * ptr, size_t size, ABTU_MEM_LARGEPAGE_TYPE type)
Definition at line 132 of file largepage.c.
Referenced by ABTI_mem_pool_destroy_global_pool().
ABTU_hashtable_create()
ABTU_ret_err int ABTU_hashtable_create (size_t num_entries, size_t data_size, ABTU_hashtable ** pp_hashtable)
Definition at line 21 of file hashtable.c.
Referenced by ABT_pool_config_create(), and ABT_sched_config_create().
ABTU_hashtable_delete()
void ABTU_hashtable_delete (ABTU_hashtable * p_hashtable, int key, int * deleted)
Definition at line 144 of file hashtable.c.
Referenced by ABT_pool_config_set(), and ABT_sched_config_set().
ABTU_hashtable_free()
void ABTU_hashtable_free (ABTU_hashtable * p_hashtable)
Definition at line 42 of file hashtable.c.
Referenced by ABT_pool_config_free(), ABT_sched_config_create(), and ABT_sched_config_free().
ABTU_hashtable_get()
void ABTU_hashtable_get (const ABTU_hashtable * p_hashtable, int key, void * data, int * found)
Definition at line 56 of file hashtable.c.
Referenced by ABT_pool_config_get(), ABT_sched_config_get(), ABT_sched_config_read(), ABTI_pool_config_read(), and ABTI_sched_config_read().
ABTU_hashtable_set()
ABTU_ret_err int ABTU_hashtable_set (ABTU_hashtable * p_hashtable, int key, const void * data, int * overwritten)
Definition at line 91 of file hashtable.c.
Referenced by ABT_pool_config_set(), ABT_sched_config_create(), and ABT_sched_config_set().
ABTU_is_supported_largepage_type()
int ABTU_is_supported_largepage_type (size_t size, size_t alignment_hint, ABTU_MEM_LARGEPAGE_TYPE requested)
Definition at line 59 of file largepage.c.
ABTU_malloc()
static ABTU_ret_err int ABTU_malloc (size_t size, void ** p_ptr) inline static
Definition at line 235 of file abtu.h.
Referenced by ABT_barrier_create(), ABT_cond_create(), ABT_eventual_create(), ABT_future_create(), ABT_key_create(), ABT_mutex_attr_create(), ABT_mutex_create(), ABT_mutex_create_with_attr(), ABT_mutex_get_attr(), ABT_rwlock_create(), ABT_thread_attr_create(), ABT_xstream_barrier_create(), ABTD_affinity_init(), ABTI_ktable_alloc_elem(), ABTI_ktable_create(), ABTI_mem_alloc_desc(), ABTI_mem_alloc_nythread(), ABTI_mem_alloc_ythread_desc_impl(), ABTI_mem_alloc_ythread_malloc_desc_stack_impl(), ABTI_sched_create_basic(), ABTI_thread_attr_dup(), ABTU_alloc_largepage(), ABTU_calloc(), ABTU_realloc(), create_cpuset(), init_library(), pool_create(), pool_init(), pool_push_threads_ex(), sched_create(), sched_init(), unit_map_thread(), xstream_create(), and xstream_update_max_xstreams().
ABTU_max_int()
static int ABTU_max_int (int a, int b) inline static
Definition at line 15 of file abtu.h.
Referenced by load_env_int().
ABTU_max_int32()
static int32_t ABTU_max_int32 (int32_t a, int32_t b) inline static
Definition at line 20 of file abtu.h.
ABTU_max_int64()
static int64_t ABTU_max_int64 (int64_t a, int64_t b) inline static
Definition at line 30 of file abtu.h.
ABTU_max_size()
static size_t ABTU_max_size (size_t a, size_t b) inline static
Definition at line 40 of file abtu.h.
Referenced by load_env_size().
ABTU_max_uint32()
static uint32_t ABTU_max_uint32 (uint32_t a, uint32_t b) inline static
Definition at line 25 of file abtu.h.
Referenced by load_env_uint32().
ABTU_max_uint64()
static uint64_t ABTU_max_uint64 (uint64_t a, uint64_t b) inline static
Definition at line 35 of file abtu.h.
Referenced by load_env_uint64().
ABTU_memalign()
static ABTU_ret_err int ABTU_memalign (size_t alignment, size_t size, void ** p_ptr) inline static
Definition at line 216 of file abtu.h.
Referenced by ABTU_alloc_largepage(), ABTU_is_supported_largepage_type(), and ABTU_malloc().
ABTU_min_int()
static int ABTU_min_int (int a, int b) inline static
Definition at line 45 of file abtu.h.
Referenced by load_env_int().
ABTU_min_int32()
static int32_t ABTU_min_int32 (int32_t a, int32_t b) inline static
Definition at line 50 of file abtu.h.
ABTU_min_int64()
static int64_t ABTU_min_int64 (int64_t a, int64_t b) inline static
Definition at line 60 of file abtu.h.
ABTU_min_size()
static size_t ABTU_min_size (size_t a, size_t b) inline static
Definition at line 70 of file abtu.h.
Referenced by ABTU_realloc(), and load_env_size().
ABTU_min_uint32()
static uint32_t ABTU_min_uint32 (uint32_t a, uint32_t b) inline static
Definition at line 55 of file abtu.h.
Referenced by ABTD_env_init(), and load_env_uint32().
ABTU_min_uint64()
static uint64_t ABTU_min_uint64 (uint64_t a, uint64_t b) inline static
Definition at line 65 of file abtu.h.
Referenced by load_env_uint64().
ABTU_mprotect()
ABTU_ret_err int ABTU_mprotect (void * addr, size_t size, ABT_bool protect)
Definition at line 9 of file mprotect.c.
Referenced by ABTI_mem_register_stack(), ABTI_mem_unregister_stack(), and protect_memory().
ABTU_realloc()
static ABTU_ret_err int ABTU_realloc (size_t old_size, size_t new_size, void ** p_ptr) inline static
Definition at line 257 of file abtu.h.
Referenced by ABTD_affinity_init(), and list_realloc().
ABTU_roundup_ptr()
static void* ABTU_roundup_ptr (void * ptr, size_t multiple) inline static
Definition at line 105 of file abtu.h.
Referenced by ABTI_mem_register_stack(), ABTI_mem_unregister_stack(), and protect_memory().
ABTU_roundup_size()
static size_t ABTU_roundup_size (size_t val, size_t multiple) inline static
Definition at line 95 of file abtu.h.
Referenced by ABTD_env_get_sched_stacksize(), ABTD_env_get_thread_stacksize(), ABTD_env_init(), ABTI_ktable_create(), ABTI_mem_alloc_ythread_malloc_desc_stack_impl(), ABTU_hashtable_create(), ABTU_hashtable_delete(), ABTU_hashtable_set(), ABTU_malloc(), and get_element().
ABTU_roundup_uint32()
static uint32_t ABTU_roundup_uint32 (uint32_t val, uint32_t multiple) inline static
Definition at line 75 of file abtu.h.
Referenced by ABTD_env_init().
ABTU_roundup_uint64()
static uint64_t ABTU_roundup_uint64 (uint64_t val, uint64_t multiple) inline static
Definition at line 85 of file abtu.h.
Referenced by ABTI_mem_check_stack_canary(), and ABTI_mem_write_stack_canary().