ARGOBOTS: src/arch/abtd_stream.c File Reference
abtd_stream.c File Reference
#include "abti.h"
Functions
static void * xstream_context_thread_func (void *arg)
ABTU_ret_err int ABTD_xstream_context_create (void *(*f_xstream)(void *), void *p_arg, ABTD_xstream_context *p_ctx)
void ABTD_xstream_context_free (ABTD_xstream_context *p_ctx)
void ABTD_xstream_context_join (ABTD_xstream_context *p_ctx)
void ABTD_xstream_context_revive (ABTD_xstream_context *p_ctx)
void ABTD_xstream_context_set_self (ABTD_xstream_context *p_ctx)
void ABTD_xstream_context_print (ABTD_xstream_context *p_ctx, FILE *p_os, int indent)
Function Documentation
ABTU_ret_err int ABTD_xstream_context_create (void *(*)(void *) f_xstream, void * p_arg, ABTD_xstream_context * p_ctx)
Definition at line 48 of file abtd_stream.c.
Referenced by xstream_start().
void ABTD_xstream_context_free (ABTD_xstream_context * p_ctx)
Definition at line 66 of file abtd_stream.c.
Referenced by ABTI_xstream_free().
void ABTD_xstream_context_join (ABTD_xstream_context * p_ctx)
Definition at line 81 of file abtd_stream.c.
Referenced by xstream_join().
void ABTD_xstream_context_print (ABTD_xstream_context * p_ctx, FILE * p_os, int indent)
Definition at line 112 of file abtd_stream.c.
Referenced by ABTI_xstream_print().
void ABTD_xstream_context_revive (ABTD_xstream_context * p_ctx)
Definition at line 97 of file abtd_stream.c.
Referenced by ABT_xstream_revive().
void ABTD_xstream_context_set_self (ABTD_xstream_context * p_ctx)
Definition at line 107 of file abtd_stream.c.
Referenced by ABTI_xstream_start_primary().
static void* xstream_context_thread_func (void * arg) static
Definition at line 8 of file abtd_stream.c.
Referenced by ABTD_xstream_context_create().