ARGOBOTS: src/include/abti_sched.h File Reference
abti_sched.h File Reference
Macros
#define CNT_DECL(c)
#define CNT_INIT(c, v)
#define CNT_INC(c)
#define SCHED_SLEEP(c, t)
Functions
static ABTI_sched * ABTI_sched_get_ptr (ABT_sched sched)
static ABT_sched ABTI_sched_get_handle (ABTI_sched *p_sched)
static void ABTI_sched_discard_and_free (ABTI_global *p_global, ABTI_local *p_local, ABTI_sched *p_sched, ABT_bool force_free)
static void ABTI_sched_set_request (ABTI_sched *p_sched, uint32_t req)
static void ABTI_sched_unset_request (ABTI_sched *p_sched, uint32_t req)
Macro Definition Documentation
CNT_DECL
#define CNT_DECL (c)
Definition at line 78 of file abti_sched.h.
CNT_INC
#define CNT_INC (c)
Definition at line 80 of file abti_sched.h.
CNT_INIT
#define CNT_INIT (c, v)
Definition at line 79 of file abti_sched.h.
SCHED_SLEEP
#define SCHED_SLEEP (c, t)
Definition at line 81 of file abti_sched.h.
Function Documentation
ABTI_sched_discard_and_free()
static void ABTI_sched_discard_and_free (ABTI_global * p_global, ABTI_local * p_local, ABTI_sched * p_sched, ABT_bool force_free) inline static
Definition at line 43 of file abti_sched.h.
ABTI_sched_get_handle()
static ABT_sched ABTI_sched_get_handle (ABTI_sched * p_sched) inline static
Definition at line 26 of file abti_sched.h.
Referenced by ABT_sched_create(), ABT_sched_create_basic(), ABTI_sched_free(), ABTI_sched_get_migration_pool(), ABTI_ythread_create_sched(), and sched_create().
ABTI_sched_get_ptr()
static ABTI_sched* ABTI_sched_get_ptr (ABT_sched sched) inline static
Definition at line 11 of file abti_sched.h.
Referenced by ABT_info_print_sched(), ABT_pool_add_sched(), ABT_sched_exit(), ABT_sched_finish(), ABT_sched_free(), ABT_sched_get_data(), ABT_sched_get_num_pools(), ABT_sched_get_pools(), ABT_sched_get_size(), ABT_sched_get_total_size(), ABT_sched_has_to_stop(), ABT_sched_set_data(), ABT_xstream_create(), ABT_xstream_create_with_rank(), sched_free(), sched_init(), and sched_run().
ABTI_sched_set_request()
static void ABTI_sched_set_request (ABTI_sched * p_sched, uint32_t req) inline static
Definition at line 60 of file abti_sched.h.
Referenced by ABTI_sched_exit(), and ABTI_sched_finish().
ABTI_sched_unset_request()
static void ABTI_sched_unset_request (ABTI_sched * p_sched, uint32_t req) inline static
Definition at line 65 of file abti_sched.h.