ARGOBOTS: src/include/abti_unit.h File Reference
abti_unit.h File Reference
Functions
static void ABTI_ktable_set (ABTI_xstream *p_local_xstream, ABTD_atomic_ptr *pp_ktable, ABTI_key *p_key, void *value)
static void * ABTI_ktable_get (ABTD_atomic_ptr *pp_ktable, ABTI_key *p_key)
static int ABTI_ktable_is_valid (ABTI_ktable *p_ktable)
static ABT_thread_state ABTI_unit_state_get_thread_state (ABTI_unit_state state)
static ABT_task_state ABTI_unit_state_get_task_state (ABTI_unit_state state)
static ABT_bool ABTI_unit_type_is_thread (ABTI_unit_type type)
static ABT_bool ABTI_unit_type_is_task (ABTI_unit_type type)
static ABT_bool ABTI_unit_type_is_ext (ABTI_unit_type type)
static ABT_bool ABTI_unit_type_is_thread_user (ABTI_unit_type type)
static ABT_bool ABTI_unit_type_is_thread_main (ABTI_unit_type type)
static ABT_bool ABTI_unit_type_is_thread_main_sched (ABTI_unit_type type)
static ABT_unit_type ABTI_unit_type_get_type (ABTI_unit_type type)
static ABTI_thread * ABTI_unit_get_thread (ABTI_unit *p_unit)
static ABTI_task * ABTI_unit_get_task (ABTI_unit *p_unit)
Function Documentation
static void* ABTI_ktable_get (ABTD_atomic_ptr * pp_ktable, ABTI_key * p_key) inline static
static int ABTI_ktable_is_valid (ABTI_ktable * p_ktable) inline static
static void ABTI_ktable_set (ABTI_xstream * p_local_xstream, ABTD_atomic_ptr * pp_ktable, ABTI_key * p_key, void * value) inline static
static ABTI_task* ABTI_unit_get_task (ABTI_unit * p_unit) inline static
Definition at line 102 of file abti_unit.h.
Referenced by ABT_task_self(), ABT_task_self_id(), ABTI_tool_query(), and unit_get_task().
static ABTI_thread* ABTI_unit_get_thread (ABTI_unit * p_unit) inline static
Definition at line 97 of file abti_unit.h.
Referenced by ABT_barrier_wait(), ABT_cond_signal(), ABT_cond_timedwait(), ABT_eventual_set(), ABT_eventual_wait(), ABT_finalize(), ABT_future_set(), ABT_future_wait(), ABT_self_suspend(), ABT_task_free(), ABT_task_join(), ABT_thread_exit(), ABT_thread_self(), ABT_thread_self_id(), ABT_thread_yield(), ABT_thread_yield_to(), ABT_xstream_exit(), ABTD_thread_terminate_no_arg(), ABTI_cond_broadcast(), ABTI_cond_wait(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_mutex_unlock_se(), ABTI_mutex_wait(), ABTI_mutex_wait_low(), ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), ABTI_thread_context_switch_to_sibling_internal(), ABTI_thread_htable_pop(), ABTI_thread_htable_pop_low(), ABTI_thread_htable_switch_low(), ABTI_thread_join(), ABTI_thread_self_id(), ABTI_thread_self_xstream_rank(), ABTI_tool_query(), ABTI_xstream_join(), ABTI_xstream_schedule_thread(), ABTI_xstream_update_main_sched(), and unit_get_thread().
static ABT_task_state ABTI_unit_state_get_task_state (ABTI_unit_state state) inline static
Definition at line 37 of file abti_unit.h.
Referenced by ABT_task_get_state().
static ABT_thread_state ABTI_unit_state_get_thread_state (ABTI_unit_state state) inline static
Definition at line 19 of file abti_unit.h.
Referenced by ABT_thread_get_state().
static ABT_unit_type ABTI_unit_type_get_type (ABTI_unit_type type) inline static
Definition at line 85 of file abti_unit.h.
Referenced by ABT_self_get_type(), and unit_get_type().
static ABT_bool ABTI_unit_type_is_ext (ABTI_unit_type type) inline static
Definition at line 64 of file abti_unit.h.
Referenced by ABTI_unit_type_get_type().
static ABT_bool ABTI_unit_type_is_task (ABTI_unit_type type) inline static
Definition at line 58 of file abti_unit.h.
Referenced by ABT_task_self(), ABT_task_self_id(), ABTI_unit_type_get_type(), unit_create_from_task(), and unit_get_task().
static ABT_bool ABTI_unit_type_is_thread (ABTI_unit_type type) inline static
Definition at line 53 of file abti_unit.h.
Referenced by ABT_barrier_wait(), ABT_cond_signal(), ABT_cond_timedwait(), ABT_eventual_set(), ABT_eventual_wait(), ABT_future_set(), ABT_future_wait(), ABT_self_is_primary(), ABT_self_suspend(), ABT_task_free(), ABT_task_join(), ABT_thread_exit(), ABT_thread_self(), ABT_thread_self_id(), ABT_thread_yield(), ABT_xstream_exit(), ABT_xstream_set_main_sched(), ABTD_thread_terminate_no_arg(), ABTI_cond_broadcast(), ABTI_cond_wait(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_mutex_unlock_se(), ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), ABTI_thread_context_switch_to_sibling_internal(), ABTI_thread_join(), ABTI_tool_query(), ABTI_unit_type_get_type(), ABTI_xstream_join(), unit_create_from_thread(), and unit_get_thread().
static ABT_bool ABTI_unit_type_is_thread_main (ABTI_unit_type type) inline static
Definition at line 74 of file abti_unit.h.
Referenced by ABT_finalize(), ABT_self_is_primary(), ABT_thread_is_primary(), ABTI_thread_create_internal(), ABTI_thread_finish_context_sched_to_main_thread(), ABTI_thread_print(), and ABTI_xstream_update_main_sched().
static ABT_bool ABTI_unit_type_is_thread_main_sched (ABTI_unit_type type) inline static
Definition at line 79 of file abti_unit.h.
Referenced by ABTI_sched_free(), ABTI_thread_create_internal(), ABTI_thread_finish_context_sched_to_main_thread(), ABTI_thread_print(), and ABTI_thread_set_blocked().
static ABT_bool ABTI_unit_type_is_thread_user (ABTI_unit_type type) inline static
Definition at line 69 of file abti_unit.h.
Referenced by ABT_thread_cancel(), ABT_thread_free(), ABT_thread_migrate_to_sched(), ABT_thread_set_migratable(), ABTI_thread_create_internal(), ABTI_thread_join(), ABTI_thread_migrate_to_pool(), ABTI_thread_migrate_to_xstream(), and ABTI_thread_print().