ARGOBOTS: src/arch/abtd_thread.c File Reference
abtd_thread.c File Reference
#include "abti.h"
Functions
static void ABTD_thread_terminate (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
void ABTD_thread_func_wrapper (void *p_arg)
void ABTD_thread_exit (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
void ABTD_thread_terminate_no_arg ()
void ABTD_thread_cancel (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
void ABTD_thread_print_context (ABTI_thread *p_thread, FILE *p_os, int indent)
Function Documentation
void ABTD_thread_cancel (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread)
Definition at line 105 of file abtd_thread.c.
Referenced by ABTI_xstream_schedule_thread().
void ABTD_thread_exit (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread)
Definition at line 30 of file abtd_thread.c.
Referenced by ABT_thread_exit().
void ABTD_thread_func_wrapper (void * p_arg)
Definition at line 11 of file abtd_thread.c.
Referenced by ABTD_thread_context_arm_thread(), and ABTD_thread_context_create().
void ABTD_thread_print_context (ABTI_thread * p_thread, FILE * p_os, int indent)
Definition at line 137 of file abtd_thread.c.
Referenced by ABTI_info_print_unit().
static void ABTD_thread_terminate (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread) inline static
Definition at line 35 of file abtd_thread.c.
Referenced by ABTD_thread_exit(), ABTD_thread_func_wrapper(), and ABTD_thread_terminate_no_arg().
void ABTD_thread_terminate_no_arg ()
Definition at line 94 of file abtd_thread.c.
Referenced by ABTD_thread_context_dynamic_promote_thread().