ARGOBOTS: src/include/abti_barrier.h File Reference
abti_barrier.h File Reference
Functions
static ABTI_barrier * ABTI_barrier_get_ptr (ABT_barrier barrier)
static ABT_barrier ABTI_barrier_get_handle (ABTI_barrier *p_barrier)
Function Documentation
ABTI_barrier_get_handle()
static ABT_barrier ABTI_barrier_get_handle (ABTI_barrier * p_barrier) inline static
Definition at line 27 of file abti_barrier.h.
Referenced by ABT_barrier_create(), and tool_query().
ABTI_barrier_get_ptr()
static ABTI_barrier* ABTI_barrier_get_ptr (ABT_barrier barrier) inline static
Definition at line 12 of file abti_barrier.h.
Referenced by ABT_barrier_free(), ABT_barrier_get_num_waiters(), ABT_barrier_reinit(), and ABT_barrier_wait().