ARGOBOTS: src/ythread.c File Reference
ythread.c File Reference
#include "abti.h"
Functions
static void ythread_callback_yield_impl (void *arg, ABT_pool_context context)
void ABTI_ythread_callback_yield_user_yield (void *arg)
void ABTI_ythread_callback_yield_loop (void *arg)
void ABTI_ythread_callback_yield_user_yield_to (void *arg)
void ABTI_ythread_callback_yield_create_to (void *arg)
void ABTI_ythread_callback_yield_revive_to (void *arg)
void ABTI_ythread_callback_thread_yield_to (void *arg)
void ABTI_ythread_callback_resume_yield_to (void *arg)
void ABTI_ythread_callback_suspend (void *arg)
void ABTI_ythread_callback_resume_suspend_to (void *arg)
void ABTI_ythread_callback_exit (void *arg)
void ABTI_ythread_callback_resume_exit_to (void *arg)
void ABTI_ythread_callback_suspend_unlock (void *arg)
void ABTI_ythread_callback_suspend_join (void *arg)
void ABTI_ythread_callback_suspend_replace_sched (void *arg)
void ABTI_ythread_callback_orphan (void *arg)
ABTU_no_sanitize_address void ABTI_ythread_print_stack (ABTI_global *p_global, ABTI_ythread *p_ythread, FILE *p_os)
Function Documentation
ABTI_ythread_callback_exit()
void ABTI_ythread_callback_exit (void * arg)
Definition at line 139 of file ythread.c.
Referenced by ABTI_ythread_exit(), ABTI_ythread_exit_to(), and ABTI_ythread_exit_to_primary().
ABTI_ythread_callback_orphan()
void ABTI_ythread_callback_orphan (void * arg)
Definition at line 222 of file ythread.c.
Referenced by ABTI_ythread_yield_orphan().
ABTI_ythread_callback_resume_exit_to()
void ABTI_ythread_callback_resume_exit_to (void * arg)
Definition at line 147 of file ythread.c.
Referenced by ABTI_ythread_resume_exit_to().
ABTI_ythread_callback_resume_suspend_to()
void ABTI_ythread_callback_resume_suspend_to (void * arg)
Definition at line 116 of file ythread.c.
Referenced by ABTI_ythread_resume_suspend_to().
ABTI_ythread_callback_resume_yield_to()
void ABTI_ythread_callback_resume_yield_to (void * arg)
Definition at line 83 of file ythread.c.
Referenced by ABTI_ythread_resume_yield_to().
ABTI_ythread_callback_suspend()
void ABTI_ythread_callback_suspend (void * arg)
Definition at line 103 of file ythread.c.
Referenced by ABTI_ythread_suspend(), and ABTI_ythread_suspend_to().
ABTI_ythread_callback_suspend_join()
void ABTI_ythread_callback_suspend_join (void * arg)
Definition at line 181 of file ythread.c.
Referenced by ABTI_ythread_suspend_join().
ABTI_ythread_callback_suspend_replace_sched()
void ABTI_ythread_callback_suspend_replace_sched (void * arg)
Definition at line 203 of file ythread.c.
Referenced by ABTI_ythread_suspend_replace_sched().
ABTI_ythread_callback_suspend_unlock()
void ABTI_ythread_callback_suspend_unlock (void * arg)
Definition at line 162 of file ythread.c.
Referenced by ABTI_ythread_suspend_unlock().
ABTI_ythread_callback_thread_yield_to()
void ABTI_ythread_callback_thread_yield_to (void * arg)
Definition at line 61 of file ythread.c.
Referenced by ABTI_ythread_thread_yield_to().
ABTI_ythread_callback_yield_create_to()
void ABTI_ythread_callback_yield_create_to (void * arg)
Definition at line 49 of file ythread.c.
Referenced by ABTI_ythread_yield_to().
ABTI_ythread_callback_yield_loop()
void ABTI_ythread_callback_yield_loop (void * arg)
Definition at line 39 of file ythread.c.
Referenced by ABTI_ythread_yield().
ABTI_ythread_callback_yield_revive_to()
void ABTI_ythread_callback_yield_revive_to (void * arg)
Definition at line 54 of file ythread.c.
Referenced by ABTI_ythread_yield_to().
ABTI_ythread_callback_yield_user_yield()
void ABTI_ythread_callback_yield_user_yield (void * arg)
Definition at line 34 of file ythread.c.
Referenced by ABTI_ythread_yield().
ABTI_ythread_callback_yield_user_yield_to()
void ABTI_ythread_callback_yield_user_yield_to (void * arg)
Definition at line 44 of file ythread.c.
Referenced by ABTI_ythread_yield_to().
ABTI_ythread_print_stack()
ABTU_no_sanitize_address void ABTI_ythread_print_stack (ABTI_global * p_global, ABTI_ythread * p_ythread, FILE * p_os)
Definition at line 230 of file ythread.c.
ythread_callback_yield_impl()
static void ythread_callback_yield_impl (void * arg, ABT_pool_context context) inline static
Definition at line 21 of file ythread.c.
Referenced by ABTI_ythread_callback_yield_create_to(), ABTI_ythread_callback_yield_loop(), ABTI_ythread_callback_yield_revive_to(), ABTI_ythread_callback_yield_user_yield(), and ABTI_ythread_callback_yield_user_yield_to().