ARGOBOTS: src/include/abti_pool.h File Reference
abti_pool.h File Reference
Macros
#define ABTI_IS_POOL_PRODUCER_CHECK_ENABLED 1
#define ABTI_IS_POOL_CONSUMER_CHECK_ENABLED 1
#define ABTI_pool_set_consumer(p_local, p_pool)
#define ABTI_pool_set_producer(p_local, p_pool)
#define ABTI_pool_push(p_local, p_pool, unit)
#define ABTI_pool_add_thread(p_local, p_thread)
#define ABTI_pool_remove(p_local, p_pool, unit)
Functions
static ABTI_pool * ABTI_pool_get_ptr (ABT_pool pool)
static ABT_pool ABTI_pool_get_handle (ABTI_pool *p_pool)
static void ABTI_pool_inc_num_blocked (ABTI_pool *p_pool)
static void ABTI_pool_dec_num_blocked (ABTI_pool *p_pool)
static void ABTI_pool_inc_num_migrations (ABTI_pool *p_pool)
static void ABTI_pool_dec_num_migrations (ABTI_pool *p_pool)
static int ABTI_pool_set_consumer_common_impl (ABTI_pool *p_pool, ABTI_native_thread_id consumer_id)
static int ABTI_pool_set_consumer_id (ABTI_pool *p_pool, ABTI_native_thread_id consumer_id)
static int ABTI_pool_set_consumer_impl (ABTI_local *p_local, ABTI_pool *p_pool)
static int ABTI_pool_set_producer_impl (ABTI_local *p_local, ABTI_pool *p_pool)
static int ABTI_pool_push_impl (ABTI_local *p_local, ABTI_pool *p_pool, ABT_unit unit)
static int ABTI_pool_add_thread_impl (ABTI_local *p_local, ABTI_thread *p_thread)
static int ABTI_pool_remove_impl (ABTI_local *p_local, ABTI_pool *p_pool, ABT_unit unit)
static ABT_unit ABTI_pool_pop_wait (ABTI_pool *p_pool, double time_secs)
static ABT_unit ABTI_pool_pop_timedwait (ABTI_pool *p_pool, double abstime_secs)
static ABT_unit ABTI_pool_pop (ABTI_pool *p_pool)
static void ABTI_pool_retain (ABTI_pool *p_pool)
static int32_t ABTI_pool_release (ABTI_pool *p_pool)
static size_t ABTI_pool_get_size (ABTI_pool *p_pool)
static size_t ABTI_pool_get_total_size (ABTI_pool *p_pool)
Macro Definition Documentation
#define ABTI_IS_POOL_CONSUMER_CHECK_ENABLED 1
Definition at line 18 of file abti_pool.h.
#define ABTI_IS_POOL_PRODUCER_CHECK_ENABLED 1
Definition at line 12 of file abti_pool.h.
#define ABTI_pool_add_thread (p_local, p_thread)
Value:
ABTI_pool_add_thread_impl(ABTI_IS_POOL_PRODUCER_CHECK_ENABLED ? (p_local)  \
                                                                  : NULL,      \
                              p_thread)
Definition at line 236 of file abti_pool.h.
Referenced by ABTI_ythread_set_ready(), and xstream_schedule_ythread().
#define ABTI_pool_push (p_local, p_pool, unit)
Value:
ABTI_pool_push_impl(ABTI_IS_POOL_PRODUCER_CHECK_ENABLED ? (p_local)        \
                                                            : NULL,            \
                        p_pool, unit)
Definition at line 218 of file abti_pool.h.
Referenced by ABT_pool_push(), ABT_thread_yield_to(), ABTI_mutex_lock(), ABTI_pool_add_thread_impl(), mutex_lock_low(), task_create(), thread_revive(), xstream_migrate_thread(), xstream_update_main_sched(), and ythread_create().
#define ABTI_pool_remove (p_local, p_pool, unit)
Value:
ABTI_pool_remove_impl(ABTI_IS_POOL_CONSUMER_CHECK_ENABLED ? (p_local)      \
                                                              : NULL,          \
                          p_pool, unit)
Definition at line 257 of file abti_pool.h.
Referenced by ABT_pool_remove(), ABT_thread_yield_to(), and thread_join().
#define ABTI_pool_set_consumer (p_local, p_pool)
Value:
ABTI_pool_set_consumer_impl(ABTI_IS_POOL_CONSUMER_CHECK_ENABLED            \
                                    ? (p_local)                                \
                                    : NULL,                                    \
                                p_pool)
Definition at line 143 of file abti_pool.h.
Referenced by ABTI_pool_remove_impl(), xstream_init_main_sched(), xstream_join(), and xstream_update_main_sched().
#define ABTI_pool_set_producer (p_local, p_pool)
Value:
ABTI_pool_set_producer_impl(ABTI_IS_POOL_PRODUCER_CHECK_ENABLED            \
                                    ? (p_local)                                \
                                    : NULL,                                    \
                                p_pool)
Definition at line 198 of file abti_pool.h.
Referenced by ABTI_pool_push_impl().
Function Documentation
static int ABTI_pool_add_thread_impl (ABTI_local * p_local, ABTI_thread * p_thread) inline static
Definition at line 223 of file abti_pool.h.
static void ABTI_pool_dec_num_blocked (ABTI_pool * p_pool) inline static
Definition at line 60 of file abti_pool.h.
Referenced by ABTI_ythread_set_ready(), mutex_unlock_se(), and thread_join().
static void ABTI_pool_dec_num_migrations (ABTI_pool * p_pool) inline static
Definition at line 72 of file abti_pool.h.
Referenced by thread_migrate_to_xstream(), and xstream_migrate_thread().
static ABT_pool ABTI_pool_get_handle (ABTI_pool * p_pool) inline static
Definition at line 38 of file abti_pool.h.
Referenced by ABT_pool_create(), ABT_pool_create_basic(), ABT_thread_get_last_pool(), ABTI_pool_free(), ABTI_pool_get_size(), ABTI_pool_pop(), ABTI_pool_pop_timedwait(), ABTI_pool_pop_wait(), ABTI_pool_push_impl(), ABTI_pool_remove_impl(), ABTI_sched_create_basic(), info_print_thread_stacks_in_pool(), pool_create(), sched_create(), and tool_query().
static ABTI_pool* ABTI_pool_get_ptr (ABT_pool pool) inline static
Definition at line 23 of file abti_pool.h.
Referenced by ABT_info_print_pool(), ABT_info_print_thread_stacks_in_pool(), ABT_pool_add_sched(), ABT_pool_free(), ABT_pool_get_access(), ABT_pool_get_data(), ABT_pool_get_id(), ABT_pool_get_size(), ABT_pool_get_total_size(), ABT_pool_pop(), ABT_pool_pop_timedwait(), ABT_pool_pop_wait(), ABT_pool_print_all(), ABT_pool_push(), ABT_pool_remove(), ABT_pool_set_data(), ABT_task_create(), ABT_thread_create(), ABT_thread_create_many(), ABT_thread_migrate_to_pool(), ABT_thread_revive(), ABT_thread_set_associated_pool(), ABT_unit_set_associated_pool(), ABT_xstream_run_unit(), ABTI_info_check_print_all_thread_stacks(), ABTI_sched_free(), ABTI_sched_get_effective_size(), ABTI_sched_get_migration_pool(), ABTI_sched_get_size(), ABTI_sched_get_total_size(), ABTI_sched_print(), ABTI_xstream_get_main_pool(), ABTI_ythread_create_main(), info_print_unit(), pool_free(), pool_get_access_num(), pool_get_size(), pool_init(), pool_pop(), pool_pop_private(), pool_pop_shared(), pool_pop_timedwait(), pool_pop_wait(), pool_print_all(), pool_push(), pool_push_private(), pool_push_shared(), pool_remove(), pool_remove_private(), pool_remove_shared(), sched_create(), sched_run(), xstream_init_main_sched(), and xstream_update_main_sched().
static size_t ABTI_pool_get_size (ABTI_pool * p_pool) inline static
Definition at line 308 of file abti_pool.h.
Referenced by ABT_pool_get_size(), ABTI_pool_get_total_size(), ABTI_pool_print(), ABTI_sched_get_effective_size(), and ABTI_sched_get_size().
static size_t ABTI_pool_get_total_size (ABTI_pool * p_pool) inline static
Definition at line 313 of file abti_pool.h.
Referenced by ABT_pool_get_total_size(), and ABTI_sched_get_total_size().
static void ABTI_pool_inc_num_blocked (ABTI_pool * p_pool) inline static
Definition at line 54 of file abti_pool.h.
Referenced by ABTI_ythread_set_blocked(), and thread_join().
static void ABTI_pool_inc_num_migrations (ABTI_pool * p_pool) inline static
Definition at line 66 of file abti_pool.h.
Referenced by ABT_thread_migrate_to_pool(), ABT_thread_migrate_to_sched(), and thread_migrate_to_xstream().
static ABT_unit ABTI_pool_pop (ABTI_pool * p_pool) inline static
Definition at line 283 of file abti_pool.h.
Referenced by ABT_pool_pop(), and sched_run().
static ABT_unit ABTI_pool_pop_timedwait (ABTI_pool * p_pool, double abstime_secs) inline static
Definition at line 272 of file abti_pool.h.
Referenced by ABT_pool_pop_timedwait().
static ABT_unit ABTI_pool_pop_wait (ABTI_pool * p_pool, double time_secs) inline static
Definition at line 262 of file abti_pool.h.
Referenced by ABT_pool_pop_wait(), and sched_run().
static int ABTI_pool_push_impl (ABTI_local * p_local, ABTI_pool * p_pool, ABT_unit unit) inline static
Definition at line 204 of file abti_pool.h.
static int32_t ABTI_pool_release (ABTI_pool * p_pool) inline static
Definition at line 302 of file abti_pool.h.
Referenced by ABTI_sched_free().
static int ABTI_pool_remove_impl (ABTI_local * p_local, ABTI_pool * p_pool, ABT_unit unit) inline static
Definition at line 241 of file abti_pool.h.
static void ABTI_pool_retain (ABTI_pool * p_pool) inline static
Definition at line 295 of file abti_pool.h.
Referenced by sched_create().
static int ABTI_pool_set_consumer_common_impl (ABTI_pool * p_pool, ABTI_native_thread_id consumer_id) inline static
Definition at line 84 of file abti_pool.h.
Referenced by ABTI_pool_set_consumer_id(), and ABTI_pool_set_consumer_impl().
static int ABTI_pool_set_consumer_id (ABTI_pool * p_pool, ABTI_native_thread_id consumer_id) inline static
Definition at line 121 of file abti_pool.h.
Referenced by ABT_pool_add_sched().
static int ABTI_pool_set_consumer_impl (ABTI_local * p_local, ABTI_pool * p_pool) inline static
Definition at line 130 of file abti_pool.h.
static int ABTI_pool_set_producer_impl (ABTI_local * p_local, ABTI_pool * p_pool) inline static
Definition at line 154 of file abti_pool.h.