ARGOBOTS: src/sched/sched_config.c File Reference
sched_config.c File Reference
#include "abti.h"
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
Data Structures
struct sched_config_element
Macros
#define SCHED_CONFIG_HTABLE_SIZE 8
Functions
static void sched_config_create_element_int (sched_config_element *p_elem, int val)
static void sched_config_create_element_double (sched_config_element *p_elem, double val)
static void sched_config_create_element_ptr (sched_config_element *p_elem, void *ptr)
static ABTU_ret_err int sched_config_create_element_typed (sched_config_element *p_elem, ABT_sched_config_type type, const void *p_val)
static void sched_config_read_element (const sched_config_element *p_elem, void *ptr)
int ABT_sched_config_create (ABT_sched_config *config,...)
Create a new scheduler configuration.
int ABT_sched_config_read (ABT_sched_config config, int num_vars,...)
Retrieve values from a scheduler configuration.
int ABT_sched_config_free (ABT_sched_config *config)
Free a scheduler configuration.
int ABT_sched_config_set (ABT_sched_config config, int idx, ABT_sched_config_type type, const void *val)
Register a value to a scheduler configuration.
int ABT_sched_config_get (ABT_sched_config config, int idx, ABT_sched_config_type *type, void *val)
Retrieve a value from a scheduler configuration.
ABTU_ret_err int ABTI_sched_config_read (const ABTI_sched_config *p_config, int idx, void *p_val)
Variables
ABT_sched_config_var ABT_sched_config_var_end
Predefined ABT_sched_config_var to mark the last parameter.
ABT_sched_config_var ABT_sched_config_access
Unused predefined ABT_sched_config_var.
ABT_sched_config_var ABT_sched_config_automatic
Predefined ABT_sched_config_var to configure whether the scheduler is freed automatically or not.
ABT_sched_config_var ABT_sched_basic_freq
Predefined ABT_sched_config_var to configure the frequency for checking events of the basic scheduler.
Macro Definition Documentation
SCHED_CONFIG_HTABLE_SIZE
#define SCHED_CONFIG_HTABLE_SIZE 8
Definition at line 12 of file sched_config.c.
Function Documentation
ABTI_sched_config_read()
ABTU_ret_err int ABTI_sched_config_read (const ABTI_sched_config * p_config, int idx, void * p_val)
Definition at line 415 of file sched_config.c.
Referenced by sched_create(), and sched_init().
sched_config_create_element_double()
static void sched_config_create_element_double (sched_config_element * p_elem, double val) static
Definition at line 443 of file sched_config.c.
Referenced by ABT_sched_config_create(), and sched_config_create_element_typed().
sched_config_create_element_int()
static void sched_config_create_element_int (sched_config_element * p_elem, int val) static
Definition at line 435 of file sched_config.c.
Referenced by ABT_sched_config_create(), and sched_config_create_element_typed().
sched_config_create_element_ptr()
static void sched_config_create_element_ptr (sched_config_element * p_elem, void * ptr) static
Definition at line 451 of file sched_config.c.
Referenced by ABT_sched_config_create(), and sched_config_create_element_typed().
sched_config_create_element_typed()
static ABTU_ret_err int sched_config_create_element_typed (sched_config_element * p_elem, ABT_sched_config_type type, const void * p_val) static
Definition at line 460 of file sched_config.c.
Referenced by ABT_sched_config_set().
sched_config_read_element()
static void sched_config_read_element (const sched_config_element * p_elem, void * ptr) static
Definition at line 482 of file sched_config.c.
Referenced by ABT_sched_config_get(), ABT_sched_config_read(), and ABTI_sched_config_read().