ARGOBOTS: src/sched/config.c File Reference
config.c File Reference
#include "abti.h"
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
Functions
static size_t sched_config_type_size (ABT_sched_config_type type)
static ABTU_ret_err int sched_config_get (const ABTI_sched_config *p_config, int idx, ABT_sched_config_type *p_type, void *p_val)
static ABTU_ret_err int sched_config_set (ABTI_sched_config *p_config, int idx, ABT_sched_config_type type, const void *p_val)
static void sched_config_free (ABTI_sched_config *p_config)
int ABT_sched_config_create (ABT_sched_config *config,...)
Create a new scheduler configuration.
int ABT_sched_config_read (ABT_sched_config config, int num_vars,...)
Retrieve values from a scheduler configuration.
int ABT_sched_config_free (ABT_sched_config *config)
Free a scheduler configuration.
int ABT_sched_config_set (ABT_sched_config config, int idx, ABT_sched_config_type type, const void *val)
Register a value to a scheduler configuration.
int ABT_sched_config_get (ABT_sched_config config, int idx, ABT_sched_config_type *type, void *val)
Retrieve a value from a scheduler configuration.
ABTU_ret_err int ABTI_sched_config_read (const ABTI_sched_config *p_config, int idx, void *p_val)
Variables
ABT_sched_config_var ABT_sched_config_var_end
Predefined ABT_sched_config_var to mark the last parameter.
ABT_sched_config_var ABT_sched_config_access
Unused predefined ABT_sched_config_var.
ABT_sched_config_var ABT_sched_config_automatic
Predefined ABT_sched_config_var to configure whether the scheduler is freed automatically or not.
ABT_sched_config_var ABT_sched_basic_freq
Predefined ABT_sched_config_var to configure the frequency for checking events of the basic scheduler.
Function Documentation
ABTI_sched_config_read()
ABTU_ret_err int ABTI_sched_config_read (const ABTI_sched_config * p_config, int idx, void * p_val)
Definition at line 374 of file config.c.
Referenced by sched_create(), and sched_init().
sched_config_free()
static void sched_config_free (ABTI_sched_config * p_config) static
Definition at line 479 of file config.c.
Referenced by ABT_sched_config_create(), and ABT_sched_config_free().
sched_config_get()
static ABTU_ret_err int sched_config_get (const ABTI_sched_config * p_config, int idx, ABT_sched_config_type * p_type, void * p_val) static
Definition at line 384 of file config.c.
Referenced by ABT_sched_config_get(), ABT_sched_config_read(), and ABTI_sched_config_read().
sched_config_set()
static ABTU_ret_err int sched_config_set (ABTI_sched_config * p_config, int idx, ABT_sched_config_type type, const void * p_val) static
Definition at line 414 of file config.c.
Referenced by ABT_sched_config_create(), and ABT_sched_config_set().
sched_config_type_size()
static size_t sched_config_type_size (ABT_sched_config_type type) inline static
Definition at line 494 of file config.c.
Referenced by sched_config_get(), and sched_config_set().