ARGOBOTS: src/pool/fifo_wait.c File Reference
fifo_wait.c File Reference
#include "abti.h"
#include "thread_queue.h"
Data Structures
struct data
Typedefs
typedef struct data data_t
Functions
static int pool_init (ABT_pool pool, ABT_pool_config config)
static void pool_free (ABT_pool pool)
static ABT_bool pool_is_empty (ABT_pool pool)
static size_t pool_get_size (ABT_pool pool)
static void pool_push (ABT_pool pool, ABT_unit unit, ABT_pool_context context)
static ABT_thread pool_pop (ABT_pool pool, ABT_pool_context context)
static ABT_thread pool_pop_wait (ABT_pool pool, double time_secs, ABT_pool_context context)
static void pool_push_many (ABT_pool pool, const ABT_unit *units, size_t num_units, ABT_pool_context context)
static void pool_pop_many (ABT_pool pool, ABT_thread *threads, size_t max_threads, size_t *num_popped, ABT_pool_context context)
static void pool_print_all (ABT_pool pool, void *arg, void(*print_fn)(void *, ABT_thread))
static ABT_unit pool_create_unit (ABT_pool pool, ABT_thread thread)
static void pool_free_unit (ABT_pool pool, ABT_unit unit)
static int pool_remove (ABT_pool pool, ABT_unit unit)
static ABT_unit pool_pop_timedwait (ABT_pool pool, double abstime_secs)
static ABT_bool pool_unit_is_in_pool (ABT_unit unit)
static data_t * pool_get_data_ptr (void *p_data)
ABTU_ret_err int ABTI_pool_get_fifo_wait_def (ABT_pool_access access, ABTI_pool_required_def *p_required_def, ABTI_pool_optional_def *p_optional_def, ABTI_pool_deprecated_def *p_deprecated_def)
static void convert_double_sec_to_timespec (struct timespec *ts_out, double seconds)
Typedef Documentation
data_t
typedef struct data data_t
Definition at line 39 of file fifo_wait.c.
Function Documentation
ABTI_pool_get_fifo_wait_def()
ABTU_ret_err int ABTI_pool_get_fifo_wait_def (ABT_pool_access access, ABTI_pool_required_def * p_required_def, ABTI_pool_optional_def * p_optional_def, ABTI_pool_deprecated_def * p_deprecated_def)
Definition at line 47 of file fifo_wait.c.
Referenced by ABTI_pool_create_basic().
convert_double_sec_to_timespec()
static void convert_double_sec_to_timespec (struct timespec * ts_out, double seconds) inline static
Definition at line 201 of file fifo_wait.c.
Referenced by pool_pop_timedwait().
pool_create_unit()
static ABT_unit pool_create_unit (ABT_pool pool, ABT_thread thread) static
Definition at line 301 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_free()
static void pool_free (ABT_pool pool) static
Definition at line 100 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_free_unit()
static void pool_free_unit (ABT_pool pool, ABT_unit unit) static
Definition at line 308 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_get_data_ptr()
static data_t* pool_get_data_ptr (void * p_data) inline static
Definition at line 41 of file fifo_wait.c.
Referenced by pool_free(), pool_get_size(), pool_is_empty(), pool_pop(), pool_pop_many(), pool_pop_timedwait(), pool_pop_wait(), pool_print_all(), pool_push(), pool_push_many(), and pool_remove().
pool_get_size()
static size_t pool_get_size (ABT_pool pool) static
Definition at line 117 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_init()
static int pool_init (ABT_pool pool, ABT_pool_config config) static
Definition at line 73 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_is_empty()
static ABT_bool pool_is_empty (ABT_pool pool) static
Definition at line 110 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_pop()
static ABT_thread pool_pop (ABT_pool pool, ABT_pool_context context) static
Definition at line 227 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_pop_many()
static void pool_pop_many (ABT_pool pool, ABT_thread * threads, size_t max_threads, size_t * num_popped, ABT_pool_context context) static
Definition at line 242 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_pop_timedwait()
static ABT_unit pool_pop_timedwait (ABT_pool pool, double abstime_secs) static
Definition at line 208 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_pop_wait()
static ABT_thread pool_pop_wait (ABT_pool pool, double time_secs, ABT_pool_context context) static
Definition at line 163 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_print_all()
static void pool_print_all (ABT_pool pool, void * arg, void(*)(void *, ABT_thread) print_fn) static
Definition at line 281 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_push()
static void pool_push (ABT_pool pool, ABT_unit unit, ABT_pool_context context) static
Definition at line 124 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_push_many()
static void pool_push_many (ABT_pool pool, const ABT_unit * units, size_t num_units, ABT_pool_context context) static
Definition at line 137 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_remove()
static int pool_remove (ABT_pool pool, ABT_unit unit) static
Definition at line 265 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().
pool_unit_is_in_pool()
static ABT_bool pool_unit_is_in_pool (ABT_unit unit) static
Definition at line 294 of file fifo_wait.c.
Referenced by ABTI_pool_get_fifo_wait_def().