ARGOBOTS: src/key.c File Reference
key.c File Reference
#include "abti.h"
Functions
int ABT_key_create (void(*destructor)(void *value), ABT_key *newkey)
Create an WU-specific data key.
int ABT_key_free (ABT_key *key)
Free an WU-specific data key.
int ABT_key_set (ABT_key key, void *value)
Associate a value with the key.
int ABT_key_get (ABT_key key, void **value)
Get the value associated with the key.
void ABTI_ktable_free (ABTI_xstream *p_local_xstream, ABTI_ktable *p_ktable)
Variables
static ABTD_atomic_uint32 g_key_id = ABTD_ATOMIC_UINT32_STATIC_INITIALIZER(0)
Function Documentation
void ABTI_ktable_free (ABTI_xstream * p_local_xstream, ABTI_ktable * p_ktable)
Definition at line 160 of file key.c.
Referenced by ABTI_task_free(), ABTI_thread_free_internal(), ABTI_thread_free_main(), and ABTI_thread_free_main_sched().
Variable Documentation
ABTD_atomic_uint32 g_key_id = ABTD_ATOMIC_UINT32_STATIC_INITIALIZER(0) static
Definition at line 13 of file key.c.