ARGOBOTS: ABTI_local_func Struct Reference
ABTI_local_func Struct Reference
#include <abti.h>
Data Fields
char padding1 [ABT_CONFIG_STATIC_CACHELINE_SIZE]
ABTI_local *(* get_local_f)(void)
void(* set_local_xstream_f)(ABTI_xstream *)
void *(* get_local_ptr_f)(void)
char padding2 [ABT_CONFIG_STATIC_CACHELINE_SIZE]
Detailed Description
Definition at line 232 of file abti.h.
Field Documentation
get_local_f
ABTI_local*(* ABTI_local_func::get_local_f) (void)
Definition at line 234 of file abti.h.
Referenced by ABTI_local_get_local_uninlined().
get_local_ptr_f
void*(* ABTI_local_func::get_local_ptr_f) (void)
Definition at line 236 of file abti.h.
Referenced by ABTI_local_get_local_ptr().
padding1
char ABTI_local_func::padding1[ABT_CONFIG_STATIC_CACHELINE_SIZE]
Definition at line 233 of file abti.h.
padding2
char ABTI_local_func::padding2[ABT_CONFIG_STATIC_CACHELINE_SIZE]
Definition at line 237 of file abti.h.
set_local_xstream_f
void(* ABTI_local_func::set_local_xstream_f) (ABTI_xstream *)
Definition at line 235 of file abti.h.
Referenced by ABTI_local_set_xstream().
The documentation for this struct was generated from the following file:
src/include/abti.h