ARGOBOTS: src/include/abti_rwlock.h File Reference
abti_rwlock.h File Reference
#include "abti_mutex.h"
#include "abti_cond.h"
Functions
static ABTI_rwlock * ABTI_rwlock_get_ptr (ABT_rwlock rwlock)
static ABT_rwlock ABTI_rwlock_get_handle (ABTI_rwlock *p_rwlock)
Function Documentation
ABTI_rwlock_get_handle()
static ABT_rwlock ABTI_rwlock_get_handle (ABTI_rwlock * p_rwlock) inline static
Definition at line 29 of file abti_rwlock.h.
Referenced by ABT_rwlock_create(), and tool_query().
ABTI_rwlock_get_ptr()
static ABTI_rwlock* ABTI_rwlock_get_ptr (ABT_rwlock rwlock) inline static
Definition at line 14 of file abti_rwlock.h.
Referenced by ABT_rwlock_free(), ABT_rwlock_rdlock(), ABT_rwlock_unlock(), and ABT_rwlock_wrlock().