ARGOBOTS: src/include/abti_thread_htable.h File Reference
abti_thread_htable.h File Reference
#include "abt_config.h"
Data Structures
struct ABTI_thread_queue
struct ABTI_thread_htable
Macros
#define USE_PTHREAD_MUTEX
#define ABTI_THREAD_HTABLE_LOCK(m) pthread_mutex_lock(&m)
#define ABTI_THREAD_HTABLE_UNLOCK(m) pthread_mutex_unlock(&m)
Functions
static void ABTI_thread_queue_acquire_mutex (ABTI_thread_queue *p_queue)
static void ABTI_thread_queue_release_mutex (ABTI_thread_queue *p_queue)
static void ABTI_thread_queue_acquire_low_mutex (ABTI_thread_queue *p_queue)
static void ABTI_thread_queue_release_low_mutex (ABTI_thread_queue *p_queue)
static void ABTI_thread_htable_add_h_node (ABTI_thread_htable *p_htable, ABTI_thread_queue *p_node)
static void ABTI_thread_htable_del_h_head (ABTI_thread_htable *p_htable)
static void ABTI_thread_htable_add_l_node (ABTI_thread_htable *p_htable, ABTI_thread_queue *p_node)
static void ABTI_thread_htable_del_l_head (ABTI_thread_htable *p_htable)
Macro Definition Documentation
#define ABTI_THREAD_HTABLE_LOCK (m) pthread_mutex_lock(&m)
Definition at line 70 of file abti_thread_htable.h.
Referenced by ABTI_mutex_wait(), ABTI_mutex_wait_low(), and ABTI_mutex_wake_de().
#define ABTI_THREAD_HTABLE_UNLOCK (m) pthread_mutex_unlock(&m)
Definition at line 71 of file abti_thread_htable.h.
Referenced by ABTI_mutex_wait(), ABTI_mutex_wait_low(), and ABTI_mutex_wake_de().
#define USE_PTHREAD_MUTEX
Definition at line 16 of file abti_thread_htable.h.
Function Documentation
static void ABTI_thread_htable_add_h_node (ABTI_thread_htable * p_htable, ABTI_thread_queue * p_node) inline static
Definition at line 105 of file abti_thread_htable.h.
Referenced by ABTI_mutex_wait().
static void ABTI_thread_htable_add_l_node (ABTI_thread_htable * p_htable, ABTI_thread_queue * p_node) inline static
Definition at line 141 of file abti_thread_htable.h.
Referenced by ABTI_mutex_wait_low().
static void ABTI_thread_htable_del_h_head (ABTI_thread_htable * p_htable) inline static
Definition at line 121 of file abti_thread_htable.h.
Referenced by ABTI_mutex_wake_de().
static void ABTI_thread_htable_del_l_head (ABTI_thread_htable * p_htable) inline static
Definition at line 157 of file abti_thread_htable.h.
Referenced by ABTI_mutex_wake_de().
static void ABTI_thread_queue_acquire_low_mutex (ABTI_thread_queue * p_queue) inline static
Definition at line 91 of file abti_thread_htable.h.
Referenced by ABTI_thread_htable_add_low(), ABTI_thread_htable_pop_low(), ABTI_thread_htable_push_low(), and ABTI_thread_htable_switch_low().
static void ABTI_thread_queue_acquire_mutex (ABTI_thread_queue * p_queue) inline static
Definition at line 77 of file abti_thread_htable.h.
Referenced by ABTI_thread_htable_add(), ABTI_thread_htable_pop(), and ABTI_thread_htable_push().
static void ABTI_thread_queue_release_low_mutex (ABTI_thread_queue * p_queue) inline static
Definition at line 100 of file abti_thread_htable.h.
Referenced by ABTI_thread_htable_add_low(), ABTI_thread_htable_pop_low(), ABTI_thread_htable_push_low(), and ABTI_thread_htable_switch_low().
static void ABTI_thread_queue_release_mutex (ABTI_thread_queue * p_queue) inline static
Definition at line 85 of file abti_thread_htable.h.
Referenced by ABTI_thread_htable_add(), ABTI_thread_htable_pop(), and ABTI_thread_htable_push().