ARGOBOTS: src/unit.c File Reference
unit.c File Reference
#include "abti.h"
Data Structures
struct atomic_unit
struct unit_to_thread
Typedefs
typedef struct atomic_unit atomic_unit
typedef struct unit_to_thread unit_to_thread
Functions
static void unit_init_hash_table (ABTI_global *p_global)
static void unit_finalize_hash_table (ABTI_global *p_global)
static ABTU_ret_err int unit_map_thread (ABTI_global *p_global, ABT_unit unit, ABTI_thread *p_thread)
static void unit_unmap_thread (ABTI_global *p_global, ABT_unit unit)
static ABTI_thread * unit_get_thread_from_user_defined_unit (ABTI_global *p_global, ABT_unit unit)
int ABT_unit_set_associated_pool (ABT_unit unit, ABT_pool pool)
No operation.
int ABT_unit_get_thread (ABT_unit unit, ABT_thread *thread)
Get a thread handle of the target work unit.
void ABTI_unit_init_hash_table (ABTI_global *p_global)
void ABTI_unit_finalize_hash_table (ABTI_global *p_global)
ABTU_ret_err int ABTI_unit_map_thread (ABTI_global *p_global, ABT_unit unit, ABTI_thread *p_thread)
void ABTI_unit_unmap_thread (ABTI_global *p_global, ABT_unit unit)
ABTI_thread * ABTI_unit_get_thread_from_user_defined_unit (ABTI_global *p_global, ABT_unit unit)
static size_t unit_get_hash_index (ABT_unit unit)
static ABT_unit atomic_relaxed_load_unit (const atomic_unit *p_ptr)
static void atomic_relaxed_store_unit (atomic_unit *p_ptr, ABT_unit val)
static unit_to_thread * atomic_acquire_load_unit_to_thread (const ABTI_atomic_unit_to_thread *p_ptr)
static unit_to_thread * atomic_relaxed_load_unit_to_thread (const ABTI_atomic_unit_to_thread *p_ptr)
static void atomic_release_store_unit_to_thread (ABTI_atomic_unit_to_thread *p_ptr, unit_to_thread *val)
static void atomic_relaxed_store_unit_to_thread (ABTI_atomic_unit_to_thread *p_ptr, unit_to_thread *val)
Typedef Documentation
atomic_unit
typedef struct atomic_unit atomic_unit
unit_to_thread
typedef struct unit_to_thread unit_to_thread
Function Documentation
ABTI_unit_finalize_hash_table()
void ABTI_unit_finalize_hash_table (ABTI_global * p_global)
Definition at line 96 of file unit.c.
Referenced by finailze_library().
ABTI_unit_get_thread_from_user_defined_unit()
ABTI_thread* ABTI_unit_get_thread_from_user_defined_unit (ABTI_global * p_global, ABT_unit unit)
Definition at line 112 of file unit.c.
Referenced by ABTI_unit_get_thread(), and ABTI_unit_set_associated_pool().
ABTI_unit_init_hash_table()
void ABTI_unit_init_hash_table (ABTI_global * p_global)
Definition at line 91 of file unit.c.
Referenced by init_library().
ABTI_unit_map_thread()
ABTU_ret_err int ABTI_unit_map_thread (ABTI_global * p_global, ABT_unit unit, ABTI_thread * p_thread)
Definition at line 101 of file unit.c.
Referenced by ABTI_thread_init_pool(), ABTI_thread_set_associated_pool(), and ABTI_unit_set_associated_pool().
ABTI_unit_unmap_thread()
void ABTI_unit_unmap_thread (ABTI_global * p_global, ABT_unit unit)
Definition at line 107 of file unit.c.
Referenced by ABTI_thread_set_associated_pool(), ABTI_thread_unset_associated_pool(), and ABTI_unit_set_associated_pool().
atomic_acquire_load_unit_to_thread()
static unit_to_thread* atomic_acquire_load_unit_to_thread (const ABTI_atomic_unit_to_thread * p_ptr) inline static
Definition at line 163 of file unit.c.
Referenced by unit_get_thread_from_user_defined_unit().
atomic_relaxed_load_unit()
static ABT_unit atomic_relaxed_load_unit (const atomic_unit * p_ptr) inline static
Definition at line 140 of file unit.c.
Referenced by unit_finalize_hash_table(), unit_get_thread_from_user_defined_unit(), unit_map_thread(), and unit_unmap_thread().
atomic_relaxed_load_unit_to_thread()
static unit_to_thread* atomic_relaxed_load_unit_to_thread (const ABTI_atomic_unit_to_thread * p_ptr) inline static
Definition at line 169 of file unit.c.
Referenced by unit_finalize_hash_table(), unit_map_thread(), and unit_unmap_thread().
atomic_relaxed_store_unit()
static void atomic_relaxed_store_unit (atomic_unit * p_ptr, ABT_unit val) inline static
Definition at line 145 of file unit.c.
Referenced by unit_map_thread(), and unit_unmap_thread().
atomic_relaxed_store_unit_to_thread()
static void atomic_relaxed_store_unit_to_thread (ABTI_atomic_unit_to_thread * p_ptr, unit_to_thread * val) inline static
Definition at line 182 of file unit.c.
Referenced by unit_init_hash_table().
atomic_release_store_unit_to_thread()
static void atomic_release_store_unit_to_thread (ABTI_atomic_unit_to_thread * p_ptr, unit_to_thread * val) inline static
Definition at line 175 of file unit.c.
Referenced by unit_map_thread().
unit_finalize_hash_table()
static void unit_finalize_hash_table (ABTI_global * p_global) static
Definition at line 199 of file unit.c.
Referenced by ABTI_unit_finalize_hash_table().
unit_get_hash_index()
static size_t unit_get_hash_index (ABT_unit unit) inline static
Definition at line 122 of file unit.c.
Referenced by unit_get_thread_from_user_defined_unit(), unit_map_thread(), and unit_unmap_thread().
unit_get_thread_from_user_defined_unit()
static ABTI_thread * unit_get_thread_from_user_defined_unit (ABTI_global * p_global, ABT_unit unit) inline static
Definition at line 278 of file unit.c.
Referenced by ABTI_unit_get_thread_from_user_defined_unit().
unit_init_hash_table()
static void unit_init_hash_table (ABTI_global * p_global) static
Definition at line 188 of file unit.c.
Referenced by ABTI_unit_init_hash_table().
unit_map_thread()
static ABTU_ret_err int unit_map_thread (ABTI_global * p_global, ABT_unit unit, ABTI_thread * p_thread) inline static
Definition at line 218 of file unit.c.
Referenced by ABTI_unit_map_thread().
unit_unmap_thread()
static void unit_unmap_thread (ABTI_global * p_global, ABT_unit unit) inline static
Definition at line 256 of file unit.c.
Referenced by ABTI_unit_unmap_thread().