ARGOBOTS: src/include/abti_local.h File Reference
abti_local.h File Reference
Functions
static ABTI_local * ABTI_local_get_local (void)
static ABTI_local * ABTI_local_get_local_uninlined (void)
static void ABTI_local_set_xstream (ABTI_xstream *p_local_xstream)
static void * ABTI_local_get_local_ptr (void)
static ABTI_xstream * ABTI_local_get_xstream_or_null (ABTI_local *p_local)
static ABTI_xstream * ABTI_local_get_xstream (ABTI_local *p_local)
Function Documentation
static ABTI_local* ABTI_local_get_local (void) inline static
Definition at line 41 of file abti_local.h.
Referenced by ABT_barrier_wait(), ABT_cond_broadcast(), ABT_cond_signal(), ABT_cond_timedwait(), ABT_cond_wait(), ABT_eventual_set(), ABT_eventual_wait(), ABT_future_set(), ABT_future_wait(), ABT_mutex_lock(), ABT_mutex_lock_low(), ABT_mutex_spinlock(), ABT_mutex_trylock(), ABT_mutex_unlock(), ABT_mutex_unlock_de(), ABT_mutex_unlock_se(), ABT_pool_add_sched(), ABT_rwlock_rdlock(), ABT_rwlock_unlock(), ABT_rwlock_wrlock(), ABT_sched_free(), ABT_sched_has_to_stop(), ABT_self_get_last_pool_id(), ABT_task_create(), ABT_task_create_on_xstream(), ABT_thread_create(), ABT_thread_create_many(), ABT_thread_create_on_xstream(), ABT_thread_free(), ABT_thread_free_many(), ABT_thread_join(), ABT_thread_join_many(), ABT_thread_migrate(), ABT_thread_migrate_to_pool(), ABT_thread_migrate_to_sched(), ABT_thread_migrate_to_xstream(), ABT_thread_resume(), ABT_thread_revive(), ABT_thread_set_callback(), ABT_thread_set_specific(), ABT_xstream_free(), ABT_xstream_join(), ABT_xstream_revive(), ABTD_ythread_func_wrapper(), ABTD_ythread_terminate_no_arg(), finailze_library(), sched_run(), thread_main_sched_func(), and thread_root_func().
static void* ABTI_local_get_local_ptr (void) inline static
Definition at line 69 of file abti_local.h.
Referenced by ABTI_self_get_native_thread_id(), and ABTI_self_get_thread_id().
static ABTI_local* ABTI_local_get_local_uninlined (void) inline static
Definition at line 51 of file abti_local.h.
Referenced by ABT_xstream_create_with_rank(), ABTI_ythread_context_switch_to_child_internal(), ABTI_ythread_context_switch_to_parent_internal(), ABTI_ythread_context_switch_to_sibling_internal(), thread_key_destructor_stackable_sched(), and thread_main_sched_func().
static ABTI_xstream* ABTI_local_get_xstream (ABTI_local * p_local) inline static
Definition at line 86 of file abti_local.h.
Referenced by ABT_thread_free(), ABT_thread_join(), ABT_xstream_revive(), ABTD_ythread_func_wrapper(), ABTD_ythread_terminate_no_arg(), ABTI_thread_free(), ABTI_thread_revive(), ABTI_xstream_free(), ABTI_ythread_context_switch_to_child_internal(), ABTI_ythread_context_switch_to_parent_internal(), ABTI_ythread_context_switch_to_sibling_internal(), ABTI_ythread_set_ready(), finailze_library(), sched_run(), task_create(), thread_free(), thread_join(), thread_main_sched_func(), thread_root_func(), xstream_join(), and ythread_create().
static ABTI_xstream* ABTI_local_get_xstream_or_null (ABTI_local * p_local) inline static
Definition at line 77 of file abti_local.h.
Referenced by ABT_barrier_wait(), ABT_cond_timedwait(), ABT_eventual_wait(), ABT_future_wait(), ABT_self_get_last_pool_id(), ABT_thread_free(), ABT_thread_join(), ABT_xstream_free(), ABT_xstream_revive(), ABTI_cond_wait(), ABTI_mem_alloc_desc(), ABTI_mem_alloc_ythread_default(), ABTI_mem_free_desc(), ABTI_mem_free_nythread(), ABTI_mem_free_thread(), ABTI_mutex_lock(), ABTI_sched_has_to_stop(), ABTI_self_get_native_thread_id(), ABTI_self_get_thread_id(), ABTI_thread_free(), ABTI_thread_revive(), ABTI_tool_event_thread_impl(), ABTI_xstream_free(), ABTI_ythread_set_ready(), finailze_library(), mutex_lock_low(), mutex_unlock_se(), task_create(), thread_free(), thread_join(), thread_migrate_to_pool(), xstream_join(), and ythread_create().
static void ABTI_local_set_xstream (ABTI_xstream * p_local_xstream) inline static
Definition at line 60 of file abti_local.h.
Referenced by finailze_library(), init_library(), and xstream_launch_root_ythread().