ARGOBOTS: src/arch/abtd_time.c File Reference
abtd_time.c File Reference
#include "abti.h"
Functions
void ABTD_time_init (void)
void ABTD_time_get (ABTD_time *p_time)
double ABTD_time_read_sec (ABTD_time *p_time)
Function Documentation
ABTD_time_get()
void ABTD_time_get (ABTD_time * p_time)
Definition at line 21 of file abtd_time.c.
Referenced by ABT_timer_start(), ABT_timer_stop(), ABT_timer_stop_and_add(), ABT_timer_stop_and_read(), and ABTI_get_wtime().
ABTD_time_init()
void ABTD_time_init (void)
Definition at line 11 of file abtd_time.c.
Referenced by ABTD_env_init(), and ABTD_time_read_sec().
ABTD_time_read_sec()
double ABTD_time_read_sec (ABTD_time * p_time)
Definition at line 35 of file abtd_time.c.
Referenced by ABT_timer_read(), ABT_timer_stop_and_add(), ABT_timer_stop_and_read(), and ABTI_get_wtime().