ARGOBOTS: src/include/abtd_thread.h File Reference
abtd_thread.h File Reference
Macros
#define ABT_API_PRIVATE
#define ABTD_thread_context_free(p_ctx)
Functions
void ABTD_thread_func_wrapper (void *p_arg)
void ABTD_thread_terminate_no_arg ()
static int ABTD_thread_context_create (ABTD_thread_context *p_link, size_t stacksize, void *p_stack, ABTD_thread_context *p_newctx)
static int ABTD_thread_context_invalidate (ABTD_thread_context *p_newctx)
static int ABTD_thread_context_init (ABTD_thread_context *p_link, ABTD_thread_context *p_newctx)
static int ABTD_thread_context_arm_thread (size_t stacksize, void *p_stack, ABTD_thread_context *p_newctx)
static void ABTD_thread_context_switch (ABTD_thread_context *p_old, ABTD_thread_context *p_new)
static void ABTD_thread_finish_context (ABTD_thread_context *p_old, ABTD_thread_context *p_new)
static void ABTD_thread_context_make_and_call (ABTD_thread_context *p_old, void(*f_thread)(void *), void *p_arg, void *p_stacktop)
static ABT_bool ABTD_thread_context_is_dynamic_promoted (ABTD_thread_context *p_ctx)
static void ABTDI_thread_context_dynamic_promote (void *p_stacktop, void *jump_f)
static void ABTD_thread_context_dynamic_promote_thread (void *p_stacktop)
Macro Definition Documentation
#define ABT_API_PRIVATE
Definition at line 12 of file abtd_thread.h.
#define ABTD_thread_context_free (p_ctx)
Definition at line 81 of file abtd_thread.h.
Referenced by ABTI_thread_free_internal(), and ABTI_thread_free_main_sched().
Function Documentation
static int ABTD_thread_context_arm_thread (size_t stacksize, void * p_stack, ABTD_thread_context * p_newctx) inline static
Definition at line 62 of file abtd_thread.h.
Referenced by ABTI_thread_context_switch_to_sibling_internal().
static int ABTD_thread_context_create (ABTD_thread_context * p_link, size_t stacksize, void * p_stack, ABTD_thread_context * p_newctx) inline static
Definition at line 20 of file abtd_thread.h.
Referenced by ABTI_thread_create_internal(), and ABTI_thread_revive().
static void ABTD_thread_context_dynamic_promote_thread (void * p_stacktop) inline static
Definition at line 122 of file abtd_thread.h.
Referenced by ABTI_thread_dynamic_promote_thread().
static int ABTD_thread_context_init (ABTD_thread_context * p_link, ABTD_thread_context * p_newctx) inline static
Definition at line 53 of file abtd_thread.h.
Referenced by ABTI_thread_create_internal().
static int ABTD_thread_context_invalidate (ABTD_thread_context * p_newctx) inline static
Definition at line 38 of file abtd_thread.h.
Referenced by ABTI_thread_create_internal().
static ABT_bool ABTD_thread_context_is_dynamic_promoted (ABTD_thread_context * p_ctx) inline static
Definition at line 105 of file abtd_thread.h.
Referenced by ABTI_thread_is_dynamic_promoted().
static void ABTD_thread_context_make_and_call (ABTD_thread_context * p_old, void(*)(void *) f_thread, void * p_arg, void * p_stacktop) inline static
Definition at line 96 of file abtd_thread.h.
Referenced by ABTI_thread_context_switch_to_child_internal().
static void ABTD_thread_context_switch (ABTD_thread_context * p_old, ABTD_thread_context * p_new) inline static
Definition at line 83 of file abtd_thread.h.
Referenced by ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), and ABTI_thread_context_switch_to_sibling_internal().
static void ABTD_thread_finish_context (ABTD_thread_context * p_old, ABTD_thread_context * p_new) inline static
Definition at line 89 of file abtd_thread.h.
Referenced by ABTI_thread_context_switch_to_parent_internal(), ABTI_thread_context_switch_to_sibling_internal(), and ABTI_thread_finish_context_sched_to_main_thread().
void ABTD_thread_func_wrapper (void * p_arg)
Definition at line 11 of file abtd_thread.c.
Referenced by ABTD_thread_context_arm_thread(), and ABTD_thread_context_create().
void ABTD_thread_terminate_no_arg ()
Definition at line 94 of file abtd_thread.c.
Referenced by ABTD_thread_context_dynamic_promote_thread().
static void ABTDI_thread_context_dynamic_promote (void * p_stacktop, void * jump_f) inline static
Definition at line 112 of file abtd_thread.h.
Referenced by ABTD_thread_context_dynamic_promote_thread().