ARGOBOTS: src/include/abti_tool.h File Reference
abti_tool.h File Reference
Macros
#define ABTI_TOOL_EVENT_TAG_SIZE 20 /* bits */
#define ABTI_TOOL_EVENT_TAG_MASK
#define ABTI_TOOL_EVENT_TAG_INC ((uint64_t)1 << (uint64_t)(64 - 1 - ABTI_TOOL_EVENT_TAG_SIZE))
#define ABTI_TOOL_EVENT_TAG_DIRTY_BIT ((uint64_t)1 << (uint64_t)(64 - 1))
#define ABTI_USE_TOOL_INTERFACE 1
#define ABTI_tool_event_thread_create(p_local_xstream, p_thread, p_caller,p_pool)
#define ABTI_tool_event_thread_join(p_local_xstream, p_thread, p_caller)
#define ABTI_tool_event_thread_free(p_local_xstream, p_thread, p_caller)
#define ABTI_tool_event_thread_revive(p_local_xstream, p_thread, p_caller,p_pool)
#define ABTI_tool_event_thread_run(p_local_xstream, p_thread, p_prev,p_parent)
#define ABTI_tool_event_thread_finish(p_local_xstream, p_thread, p_parent)
#define ABTI_tool_event_thread_cancel(p_local_xstream, p_thread)
#define ABTI_tool_event_thread_yield(p_local_xstream, p_thread, p_parent,sync_event_type, p_sync)
#define ABTI_tool_event_thread_suspend(p_local_xstream, p_thread, p_parent,sync_event_type, p_sync)
#define ABTI_tool_event_thread_resume(p_local_xstream, p_thread, p_caller)
#define ABTI_tool_event_task_create(p_local_xstream, p_task, p_caller, p_pool)
#define ABTI_tool_event_task_join(p_local_xstream, p_task, p_caller)
#define ABTI_tool_event_task_free(p_local_xstream, p_task, p_caller)
#define ABTI_tool_event_task_revive(p_local_xstream, p_task, p_caller, p_pool)
#define ABTI_tool_event_task_run(p_local_xstream, p_task, p_parent)
#define ABTI_tool_event_task_finish(p_local_xstream, p_task, p_parent)
#define ABTI_tool_event_task_cancel(p_local_xstream, p_task)
Functions
static ABT_thread ABTI_thread_get_handle (ABTI_thread *p_thread)
static ABT_task ABTI_task_get_handle (ABTI_task *p_task)
static ABTI_tool_context * ABTI_tool_context_get_ptr (ABT_tool_context tctx)
static ABT_tool_context ABTI_tool_context_get_handle (ABTI_tool_context *p_tctx)
static void ABTI_tool_event_thread_update_callback (ABT_tool_thread_callback_fn cb_func, uint64_t event_mask_thread, void *user_arg)
static void ABTI_tool_event_task_update_callback (ABT_tool_task_callback_fn cb_func, uint64_t event_mask_task, void *user_arg)
static void ABTI_tool_event_thread_impl (ABTI_xstream *p_local_xstream, uint64_t event_code, ABTI_thread *p_thread, ABTI_unit *p_caller, ABTI_pool *p_pool, ABTI_unit *p_parent, ABT_sync_event_type sync_event_type, void *p_sync_object)
static void ABTI_tool_event_task_impl (ABTI_xstream *p_local_xstream, uint64_t event_code, ABTI_task *p_task, ABTI_unit *p_caller, ABTI_pool *p_pool, ABTI_unit *p_parent, ABT_sync_event_type sync_event_type, void *p_sync_object)
static void ABTI_tool_event_thread_create_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_caller, ABTI_pool *p_pool)
static void ABTI_tool_event_thread_join_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_caller)
static void ABTI_tool_event_thread_free_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_caller)
static void ABTI_tool_event_thread_revive_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_caller, ABTI_pool *p_pool)
static void ABTI_tool_event_thread_run_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_prev, ABTI_unit *p_parent)
static void ABTI_tool_event_thread_finish_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_parent)
static void ABTI_tool_event_thread_cancel_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread)
static void ABTI_tool_event_thread_yield_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_parent, ABT_sync_event_type sync_event_type, void *p_sync)
static void ABTI_tool_event_thread_suspend_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_parent, ABT_sync_event_type sync_event_type, void *p_sync)
static void ABTI_tool_event_thread_resume_impl (ABTI_xstream *p_local_xstream, ABTI_thread *p_thread, ABTI_unit *p_caller)
static void ABTI_tool_event_task_create_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task, ABTI_unit *p_caller, ABTI_pool *p_pool)
static void ABTI_tool_event_task_join_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task, ABTI_unit *p_caller)
static void ABTI_tool_event_task_free_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task, ABTI_unit *p_caller)
static void ABTI_tool_event_task_revive_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task, ABTI_unit *p_caller, ABTI_pool *p_pool)
static void ABTI_tool_event_task_run_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task, ABTI_unit *p_parent)
static void ABTI_tool_event_task_finish_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task, ABTI_unit *p_parent)
static void ABTI_tool_event_task_cancel_impl (ABTI_xstream *p_local_xstream, ABTI_task *p_task)
Macro Definition Documentation
#define ABTI_TOOL_EVENT_TAG_DIRTY_BIT ((uint64_t)1 << (uint64_t)(64 - 1))
Definition at line 51 of file abti_tool.h.
Referenced by ABTI_tool_event_task_impl(), ABTI_tool_event_task_update_callback(), ABTI_tool_event_thread_impl(), and ABTI_tool_event_thread_update_callback().
#define ABTI_TOOL_EVENT_TAG_INC ((uint64_t)1 << (uint64_t)(64 - 1 - ABTI_TOOL_EVENT_TAG_SIZE))
Definition at line 49 of file abti_tool.h.
Referenced by ABTI_tool_event_task_update_callback(), and ABTI_tool_event_thread_update_callback().
#define ABTI_TOOL_EVENT_TAG_MASK
Value:
((((uint64_t)1 << (uint64_t)ABTI_TOOL_EVENT_TAG_SIZE) - 1)                 \
     << (uint64_t)(64 - 1 - ABTI_TOOL_EVENT_TAG_SIZE))
Definition at line 46 of file abti_tool.h.
Referenced by ABTI_tool_event_task_update_callback(), and ABTI_tool_event_thread_update_callback().
#define ABTI_TOOL_EVENT_TAG_SIZE 20 /* bits */
Definition at line 45 of file abti_tool.h.
#define ABTI_tool_event_task_cancel (p_local_xstream, p_task)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_cancel_impl(p_local_xstream, p_task);         \
        }                                                                      \
    } while (0)
Definition at line 508 of file abti_tool.h.
Referenced by ABTI_xstream_schedule_task().
#define ABTI_tool_event_task_create (p_local_xstream, p_task, p_caller, p_pool)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_create_impl(p_local_xstream, p_task,          \
                                             p_caller, p_pool);                \
        }                                                                      \
    } while (0)
Definition at line 463 of file abti_tool.h.
Referenced by ABTI_task_create().
#define ABTI_tool_event_task_finish (p_local_xstream, p_task, p_parent)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_finish_impl(p_local_xstream, p_task,          \
                                             p_parent);                        \
        }                                                                      \
    } while (0)
Definition at line 500 of file abti_tool.h.
Referenced by ABTI_xstream_schedule_task().
#define ABTI_tool_event_task_free (p_local_xstream, p_task, p_caller)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_free_impl(p_local_xstream, p_task, p_caller); \
        }                                                                      \
    } while (0)
Definition at line 478 of file abti_tool.h.
Referenced by ABTI_task_free().
#define ABTI_tool_event_task_join (p_local_xstream, p_task, p_caller)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_join_impl(p_local_xstream, p_task, p_caller); \
        }                                                                      \
    } while (0)
Definition at line 471 of file abti_tool.h.
Referenced by ABT_task_free(), and ABT_task_join().
#define ABTI_tool_event_task_revive (p_local_xstream, p_task, p_caller, p_pool)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_revive_impl(p_local_xstream, p_task,          \
                                             p_caller, p_pool);                \
        }                                                                      \
    } while (0)
Definition at line 485 of file abti_tool.h.
Referenced by ABTI_task_revive().
#define ABTI_tool_event_task_run (p_local_xstream, p_task, p_parent)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_task_run_impl(p_local_xstream, p_task, p_parent);  \
        }                                                                      \
    } while (0)
Definition at line 493 of file abti_tool.h.
Referenced by ABTI_xstream_schedule_task().
#define ABTI_tool_event_thread_cancel (p_local_xstream, p_thread)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_cancel_impl(p_local_xstream, p_thread);     \
        }                                                                      \
    } while (0)
Definition at line 428 of file abti_tool.h.
Referenced by ABTD_thread_cancel().
#define ABTI_tool_event_thread_create (p_local_xstream, p_thread, p_caller, p_pool)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_create_impl(p_local_xstream, p_thread,      \
                                               p_caller, p_pool);              \
        }                                                                      \
    } while (0)
Definition at line 377 of file abti_tool.h.
Referenced by ABTI_thread_create_internal(), and ABTI_xstream_launch_main_sched().
#define ABTI_tool_event_thread_finish (p_local_xstream, p_thread, p_parent)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_finish_impl(p_local_xstream, p_thread,      \
                                               p_parent);                      \
        }                                                                      \
    } while (0)
Definition at line 420 of file abti_tool.h.
Referenced by ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), ABTI_thread_context_switch_to_sibling_internal(), and ABTI_xstream_launch_main_sched().
#define ABTI_tool_event_thread_free (p_local_xstream, p_thread, p_caller)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_free_impl(p_local_xstream, p_thread,        \
                                             p_caller);                        \
        }                                                                      \
    } while (0)
Definition at line 394 of file abti_tool.h.
Referenced by ABTI_thread_free(), ABTI_thread_free_main(), ABTI_thread_free_main_sched(), and ABTI_xstream_launch_main_sched().
#define ABTI_tool_event_thread_join (p_local_xstream, p_thread, p_caller)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_join_impl(p_local_xstream, p_thread,        \
                                             p_caller);                        \
        }                                                                      \
    } while (0)
Definition at line 386 of file abti_tool.h.
Referenced by ABTI_thread_join().
#define ABTI_tool_event_thread_resume (p_local_xstream, p_thread, p_caller)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_resume_impl(p_local_xstream, p_thread,      \
                                               p_caller);                      \
        }                                                                      \
    } while (0)
Definition at line 455 of file abti_tool.h.
Referenced by ABTD_thread_terminate(), ABTI_mutex_unlock_se(), ABTI_thread_htable_switch_low(), and ABTI_thread_set_ready().
#define ABTI_tool_event_thread_revive (p_local_xstream, p_thread, p_caller, p_pool)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_revive_impl(p_local_xstream, p_thread,      \
                                               p_caller, p_pool);              \
        }                                                                      \
    } while (0)
Definition at line 402 of file abti_tool.h.
Referenced by ABTI_thread_revive().
#define ABTI_tool_event_thread_run (p_local_xstream, p_thread, p_prev, p_parent)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_run_impl(p_local_xstream, p_thread, p_prev, \
                                            p_parent);                         \
        }                                                                      \
    } while (0)
Definition at line 411 of file abti_tool.h.
Referenced by ABT_thread_yield_to(), ABTD_thread_func_wrapper(), ABTI_mutex_unlock_se(), ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), ABTI_thread_htable_switch_low(), ABTI_thread_join(), and ABTI_xstream_launch_main_sched().
#define ABTI_tool_event_thread_suspend (p_local_xstream, p_thread, p_parent, sync_event_type, p_sync)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_suspend_impl(p_local_xstream, p_thread,     \
                                                p_parent, sync_event_type,     \
                                                p_sync);                       \
        }                                                                      \
    } while (0)
Definition at line 445 of file abti_tool.h.
Referenced by ABTI_thread_htable_switch_low(), and ABTI_thread_join().
#define ABTI_tool_event_thread_yield (p_local_xstream, p_thread, p_parent, sync_event_type, p_sync)
Value:
do {                                                                       \
        if (ABTI_USE_TOOL_INTERFACE) {                                         \
            ABTI_tool_event_thread_yield_impl(p_local_xstream, p_thread,       \
                                              p_parent, sync_event_type,       \
                                              p_sync);                         \
        }                                                                      \
    } while (0)
Definition at line 435 of file abti_tool.h.
Referenced by ABT_thread_yield_to(), ABTI_mutex_unlock_se(), and ABTI_thread_context_switch_to_parent_internal().
#define ABTI_USE_TOOL_INTERFACE 1
Definition at line 372 of file abti_tool.h.
Function Documentation
static ABT_task ABTI_task_get_handle (ABTI_task * p_task) inline static
Referenced by ABTI_tool_event_task_impl().
static ABT_thread ABTI_thread_get_handle (ABTI_thread * p_thread) inline static
Referenced by ABTI_tool_event_thread_impl().
static ABT_tool_context ABTI_tool_context_get_handle (ABTI_tool_context * p_tctx) inline static
Definition at line 30 of file abti_tool.h.
Referenced by ABTI_tool_event_task_impl(), and ABTI_tool_event_thread_impl().
static ABTI_tool_context* ABTI_tool_context_get_ptr (ABT_tool_context tctx) inline static
Definition at line 14 of file abti_tool.h.
Referenced by ABT_tool_query_task(), and ABT_tool_query_thread().
static void ABTI_tool_event_task_cancel_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task) inline static
Definition at line 363 of file abti_tool.h.
static void ABTI_tool_event_task_create_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task, ABTI_unit * p_caller, ABTI_pool * p_pool) inline static
Definition at line 307 of file abti_tool.h.
static void ABTI_tool_event_task_finish_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task, ABTI_unit * p_parent) inline static
Definition at line 354 of file abti_tool.h.
static void ABTI_tool_event_task_free_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task, ABTI_unit * p_caller) inline static
Definition at line 325 of file abti_tool.h.
static void ABTI_tool_event_task_impl (ABTI_xstream * p_local_xstream, uint64_t event_code, ABTI_task * p_task, ABTI_unit * p_caller, ABTI_pool * p_pool, ABTI_unit * p_parent, ABT_sync_event_type sync_event_type, void * p_sync_object) inline static
Definition at line 166 of file abti_tool.h.
Referenced by ABTI_tool_event_task_cancel_impl(), ABTI_tool_event_task_create_impl(), ABTI_tool_event_task_finish_impl(), ABTI_tool_event_task_free_impl(), ABTI_tool_event_task_join_impl(), ABTI_tool_event_task_revive_impl(), and ABTI_tool_event_task_run_impl().
static void ABTI_tool_event_task_join_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task, ABTI_unit * p_caller) inline static
Definition at line 316 of file abti_tool.h.
static void ABTI_tool_event_task_revive_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task, ABTI_unit * p_caller, ABTI_pool * p_pool) inline static
Definition at line 335 of file abti_tool.h.
static void ABTI_tool_event_task_run_impl (ABTI_xstream * p_local_xstream, ABTI_task * p_task, ABTI_unit * p_parent) inline static
Definition at line 344 of file abti_tool.h.
static void ABTI_tool_event_task_update_callback (ABT_tool_task_callback_fn cb_func, uint64_t event_mask_task, void * user_arg) inline static
Definition at line 99 of file abti_tool.h.
Referenced by ABT_finalize(), and ABT_tool_register_task_callback().
static void ABTI_tool_event_thread_cancel_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread) inline static
Definition at line 261 of file abti_tool.h.
static void ABTI_tool_event_thread_create_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_caller, ABTI_pool * p_pool) inline static
Definition at line 204 of file abti_tool.h.
static void ABTI_tool_event_thread_finish_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_parent) inline static
Definition at line 252 of file abti_tool.h.
static void ABTI_tool_event_thread_free_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_caller) inline static
Definition at line 223 of file abti_tool.h.
static void ABTI_tool_event_thread_impl (ABTI_xstream * p_local_xstream, uint64_t event_code, ABTI_thread * p_thread, ABTI_unit * p_caller, ABTI_pool * p_pool, ABTI_unit * p_parent, ABT_sync_event_type sync_event_type, void * p_sync_object) inline static
Definition at line 129 of file abti_tool.h.
Referenced by ABTI_tool_event_thread_cancel_impl(), ABTI_tool_event_thread_create_impl(), ABTI_tool_event_thread_finish_impl(), ABTI_tool_event_thread_free_impl(), ABTI_tool_event_thread_join_impl(), ABTI_tool_event_thread_resume_impl(), ABTI_tool_event_thread_revive_impl(), ABTI_tool_event_thread_run_impl(), ABTI_tool_event_thread_suspend_impl(), and ABTI_tool_event_thread_yield_impl().
static void ABTI_tool_event_thread_join_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_caller) inline static
Definition at line 214 of file abti_tool.h.
static void ABTI_tool_event_thread_resume_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_caller) inline static
Definition at line 298 of file abti_tool.h.
static void ABTI_tool_event_thread_revive_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_caller, ABTI_pool * p_pool) inline static
Definition at line 232 of file abti_tool.h.
static void ABTI_tool_event_thread_run_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_prev, ABTI_unit * p_parent) inline static
Definition at line 242 of file abti_tool.h.
static void ABTI_tool_event_thread_suspend_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_parent, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 288 of file abti_tool.h.
static void ABTI_tool_event_thread_update_callback (ABT_tool_thread_callback_fn cb_func, uint64_t event_mask_thread, void * user_arg) inline static
Definition at line 54 of file abti_tool.h.
Referenced by ABT_finalize(), and ABT_tool_register_thread_callback().
static void ABTI_tool_event_thread_yield_impl (ABTI_xstream * p_local_xstream, ABTI_thread * p_thread, ABTI_unit * p_parent, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 269 of file abti_tool.h.