ARGOBOTS: src/include/abti_task.h File Reference
abti_task.h File Reference
Functions
static ABTI_task * ABTI_task_get_ptr (ABT_task task)
static ABT_task ABTI_task_get_handle (ABTI_task *p_task)
static void ABTI_task_set_request (ABTI_task *p_task, uint32_t req)
static void ABTI_task_unset_request (ABTI_task *p_task, uint32_t req)
Function Documentation
static ABT_task ABTI_task_get_handle (ABTI_task * p_task) inline static
Definition at line 26 of file abti_task.h.
Referenced by ABT_task_create(), ABT_task_create_on_xstream(), ABT_task_self(), ABTI_task_create(), ABTI_task_revive(), ABTI_tool_query(), and unit_get_task().
static ABTI_task* ABTI_task_get_ptr (ABT_task task) inline static
Definition at line 11 of file abti_task.h.
Referenced by ABT_info_print_task(), ABT_task_cancel(), ABT_task_equal(), ABT_task_free(), ABT_task_get_arg(), ABT_task_get_id(), ABT_task_get_last_pool(), ABT_task_get_last_pool_id(), ABT_task_get_specific(), ABT_task_get_state(), ABT_task_get_xstream(), ABT_task_is_migratable(), ABT_task_is_unnamed(), ABT_task_join(), ABT_task_revive(), ABT_task_set_migratable(), ABT_task_set_specific(), ABTI_unit_set_associated_pool(), ABTI_xstream_run_unit(), and unit_create_from_task().
static void ABTI_task_set_request (ABTI_task * p_task, uint32_t req) inline static
Definition at line 41 of file abti_task.h.
Referenced by ABT_task_cancel().
static void ABTI_task_unset_request (ABTI_task * p_task, uint32_t req) inline static
Definition at line 46 of file abti_task.h.