ARGOBOTS: src/include/abti_sync_lifo.h File Reference
abti_sync_lifo.h File Reference
Data Structures
struct ABTI_sync_lifo_element
Typedefs
typedef struct ABTI_sync_lifo_element ABTI_sync_lifo_element
Functions
typedef __attribute__ ((aligned(ABT_CONFIG_STATIC_CACHELINE_SIZE))) struct
static void ABTI_sync_lifo_init (ABTI_sync_lifo *p_lifo)
static void ABTI_sync_lifo_destroy (ABTI_sync_lifo *p_lifo)
static void ABTI_sync_lifo_push_unsafe (ABTI_sync_lifo *p_lifo, ABTI_sync_lifo_element *p_elem)
static ABTI_sync_lifo_element * ABTI_sync_lifo_pop_unsafe (ABTI_sync_lifo *p_lifo)
static void ABTI_sync_lifo_push (ABTI_sync_lifo *p_lifo, ABTI_sync_lifo_element *p_elem)
static ABTI_sync_lifo_element * ABTI_sync_lifo_pop (ABTI_sync_lifo *p_lifo)
Variables
ABTI_sync_lifo
Typedef Documentation
ABTI_sync_lifo_element
typedef struct ABTI_sync_lifo_element ABTI_sync_lifo_element
Function Documentation
__attribute__()
typedef __attribute__ ((aligned(ABT_CONFIG_STATIC_CACHELINE_SIZE)))
Definition at line 20 of file abti_sync_lifo.h.
ABTI_sync_lifo_destroy()
static void ABTI_sync_lifo_destroy (ABTI_sync_lifo * p_lifo) inline static
Definition at line 40 of file abti_sync_lifo.h.
Referenced by ABTI_mem_pool_destroy_global_pool().
ABTI_sync_lifo_init()
static void ABTI_sync_lifo_init (ABTI_sync_lifo * p_lifo) inline static
Definition at line 29 of file abti_sync_lifo.h.
Referenced by ABTI_mem_pool_init_global_pool().
ABTI_sync_lifo_pop()
static ABTI_sync_lifo_element* ABTI_sync_lifo_pop (ABTI_sync_lifo * p_lifo) inline static
Definition at line 116 of file abti_sync_lifo.h.
Referenced by ABTI_mem_pool_take_bucket().
ABTI_sync_lifo_pop_unsafe()
static ABTI_sync_lifo_element* ABTI_sync_lifo_pop_unsafe (ABTI_sync_lifo * p_lifo) inline static
Definition at line 66 of file abti_sync_lifo.h.
Referenced by ABTI_mem_pool_destroy_global_pool(), and ABTI_sync_lifo_pop().
ABTI_sync_lifo_push()
static void ABTI_sync_lifo_push (ABTI_sync_lifo * p_lifo, ABTI_sync_lifo_element * p_elem) inline static
Definition at line 90 of file abti_sync_lifo.h.
Referenced by ABTI_mem_pool_return_bucket(), and ABTI_mem_pool_take_bucket().
ABTI_sync_lifo_push_unsafe()
static void ABTI_sync_lifo_push_unsafe (ABTI_sync_lifo * p_lifo, ABTI_sync_lifo_element * p_elem) inline static
Definition at line 45 of file abti_sync_lifo.h.
Referenced by ABTI_sync_lifo_push().
Variable Documentation
ABTI_sync_lifo
ABTI_sync_lifo
Definition at line 27 of file abti_sync_lifo.h.