ARGOBOTS: src/include/abti_thread.h File Reference
abti_thread.h File Reference
Functions
static ABTI_thread * ABTI_thread_get_ptr (ABT_thread thread)
static ABT_thread ABTI_thread_get_handle (ABTI_thread *p_thread)
static ABTI_thread * ABTI_thread_context_get_thread (ABTD_thread_context *p_ctx)
static ABT_bool ABTI_thread_is_dynamic_promoted (ABTI_thread *p_thread)
static void ABTI_thread_dynamic_promote_thread (ABTI_thread *p_thread)
static ABTI_thread * ABTI_thread_context_switch_to_sibling_internal (ABTI_xstream **pp_local_xstream, ABTI_thread *p_old, ABTI_thread *p_new, ABT_bool is_finish)
static ABTI_thread * ABTI_thread_context_switch_to_parent_internal (ABTI_xstream **pp_local_xstream, ABTI_thread *p_old, ABT_bool is_finish, ABT_sync_event_type sync_event_type, void *p_sync)
static ABTI_thread * ABTI_thread_context_switch_to_child_internal (ABTI_xstream **pp_local_xstream, ABTI_thread *p_old, ABTI_thread *p_new)
static ABTI_thread * ABTI_thread_context_switch_to_sibling (ABTI_xstream **pp_local_xstream, ABTI_thread *p_old, ABTI_thread *p_new)
static ABTI_thread * ABTI_thread_context_switch_to_parent (ABTI_xstream **pp_local_xstream, ABTI_thread *p_old, ABT_sync_event_type sync_event_type, void *p_sync)
static ABTI_thread * ABTI_thread_context_switch_to_child (ABTI_xstream **pp_local_xstream, ABTI_thread *p_old, ABTI_thread *p_new)
static ABTU_noreturn void ABTI_thread_finish_context_to_sibling (ABTI_xstream *p_local_xstream, ABTI_thread *p_old, ABTI_thread *p_new)
static ABTU_noreturn void ABTI_thread_finish_context_to_parent (ABTI_xstream *p_local_xstream, ABTI_thread *p_old)
static ABTU_noreturn void ABTI_thread_finish_context_sched_to_main_thread (ABTI_sched *p_main_sched)
static void ABTI_thread_set_request (ABTI_thread *p_thread, uint32_t req)
static void ABTI_thread_unset_request (ABTI_thread *p_thread, uint32_t req)
static void ABTI_thread_yield (ABTI_xstream **pp_local_xstream, ABTI_thread *p_thread, ABT_sync_event_type sync_event_type, void *p_sync)
Function Documentation
static ABTI_thread* ABTI_thread_context_get_thread (ABTD_thread_context * p_ctx) inline static
Definition at line 42 of file abti_thread.h.
Referenced by ABTD_thread_cancel(), ABTD_thread_func_wrapper(), ABTD_thread_terminate(), ABTI_thread_context_switch_to_child_internal(), and ABTI_thread_finish_context_sched_to_main_thread().
static ABTI_thread* ABTI_thread_context_switch_to_child (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_old, ABTI_thread * p_new) inline static
Definition at line 317 of file abti_thread.h.
Referenced by ABTI_xstream_schedule_thread().
static ABTI_thread* ABTI_thread_context_switch_to_child_internal (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_old, ABTI_thread * p_new) inline static
Definition at line 210 of file abti_thread.h.
Referenced by ABTI_thread_context_switch_to_child().
static ABTI_thread* ABTI_thread_context_switch_to_parent (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_old, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 306 of file abti_thread.h.
Referenced by ABT_finalize(), ABTI_sched_has_to_stop(), ABTI_thread_suspend(), ABTI_thread_yield(), ABTI_xstream_start_primary(), and ABTI_xstream_update_main_sched().
static ABTI_thread* ABTI_thread_context_switch_to_parent_internal (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_old, ABT_bool is_finish, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 175 of file abti_thread.h.
Referenced by ABTI_thread_context_switch_to_parent(), and ABTI_thread_finish_context_to_parent().
static ABTI_thread* ABTI_thread_context_switch_to_sibling (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_old, ABTI_thread * p_new) inline static
Definition at line 298 of file abti_thread.h.
Referenced by ABT_thread_yield_to(), ABTI_mutex_unlock_se(), ABTI_thread_htable_switch_low(), and ABTI_thread_join().
static ABTI_thread* ABTI_thread_context_switch_to_sibling_internal (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_old, ABTI_thread * p_new, ABT_bool is_finish) inline static
Definition at line 143 of file abti_thread.h.
Referenced by ABTI_thread_context_switch_to_sibling(), and ABTI_thread_finish_context_to_sibling().
static void ABTI_thread_dynamic_promote_thread (ABTI_thread * p_thread) inline static
Definition at line 132 of file abti_thread.h.
Referenced by ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), and ABTI_thread_context_switch_to_sibling_internal().
static ABTU_noreturn void ABTI_thread_finish_context_sched_to_main_thread (ABTI_sched * p_main_sched) inline static
Definition at line 345 of file abti_thread.h.
Referenced by ABTI_xstream_schedule().
static ABTU_noreturn void ABTI_thread_finish_context_to_parent (ABTI_xstream * p_local_xstream, ABTI_thread * p_old) inline static
Definition at line 334 of file abti_thread.h.
Referenced by ABTD_thread_terminate().
static ABTU_noreturn void ABTI_thread_finish_context_to_sibling (ABTI_xstream * p_local_xstream, ABTI_thread * p_old, ABTI_thread * p_new) inline static
Definition at line 325 of file abti_thread.h.
Referenced by ABTD_thread_terminate().
static ABT_thread ABTI_thread_get_handle (ABTI_thread * p_thread) inline static
Definition at line 26 of file abti_thread.h.
Referenced by ABT_thread_create(), ABT_thread_create_many(), ABT_thread_create_on_xstream(), ABT_thread_self(), ABTI_thread_create_internal(), ABTI_thread_revive(), ABTI_tool_query(), ABTI_xstream_migrate_thread(), ABTI_xstream_update_main_sched(), and unit_get_thread().
static ABTI_thread* ABTI_thread_get_ptr (ABT_thread thread) inline static
Definition at line 11 of file abti_thread.h.
Referenced by ABT_info_print_thread(), ABT_info_print_thread_stack(), ABT_thread_cancel(), ABT_thread_equal(), ABT_thread_free(), ABT_thread_free_many(), ABT_thread_get_arg(), ABT_thread_get_attr(), ABT_thread_get_id(), ABT_thread_get_last_pool(), ABT_thread_get_last_pool_id(), ABT_thread_get_specific(), ABT_thread_get_stacksize(), ABT_thread_get_state(), ABT_thread_is_migratable(), ABT_thread_is_primary(), ABT_thread_is_unnamed(), ABT_thread_join(), ABT_thread_join_many(), ABT_thread_migrate(), ABT_thread_migrate_to_pool(), ABT_thread_migrate_to_sched(), ABT_thread_migrate_to_xstream(), ABT_thread_resume(), ABT_thread_revive(), ABT_thread_set_arg(), ABT_thread_set_associated_pool(), ABT_thread_set_callback(), ABT_thread_set_migratable(), ABT_thread_set_specific(), ABT_thread_yield_to(), ABTI_info_print_unit(), ABTI_unit_set_associated_pool(), ABTI_xstream_run_unit(), and unit_create_from_thread().
static ABT_bool ABTI_thread_is_dynamic_promoted (ABTI_thread * p_thread) inline static
Definition at line 48 of file abti_thread.h.
Referenced by ABTI_thread_context_switch_to_child_internal(), ABTI_thread_context_switch_to_parent_internal(), and ABTI_thread_context_switch_to_sibling_internal().
static void ABTI_thread_set_request (ABTI_thread * p_thread, uint32_t req) inline static
Definition at line 359 of file abti_thread.h.
Referenced by ABT_finalize(), ABT_thread_cancel(), ABT_thread_exit(), ABTI_thread_migrate_to_pool(), ABTI_thread_set_blocked(), and ABTI_xstream_update_main_sched().
static void ABTI_thread_unset_request (ABTI_thread * p_thread, uint32_t req) inline static
Definition at line 364 of file abti_thread.h.
Referenced by ABTI_xstream_migrate_thread(), and ABTI_xstream_schedule_thread().
static void ABTI_thread_yield (ABTI_xstream ** pp_local_xstream, ABTI_thread * p_thread, ABT_sync_event_type sync_event_type, void * p_sync) inline static
Definition at line 370 of file abti_thread.h.
Referenced by ABT_cond_timedwait(), ABT_task_free(), ABT_task_join(), ABT_thread_yield(), ABT_xstream_exit(), ABTI_mutex_lock(), ABTI_mutex_lock_low(), ABTI_mutex_unlock_se(), ABTI_thread_join(), ABTI_thread_migrate_to_pool(), and ABTI_xstream_join().