ARGOBOTS: src/include/abtd_atomic.h File Reference
abtd_atomic.h File Reference
#include <stdint.h>
Data Structures
struct ABTD_atomic_bool
struct ABTD_atomic_int
struct ABTD_atomic_size
struct ABTD_atomic_int32
struct ABTD_atomic_uint32
struct ABTD_atomic_int64
struct ABTD_atomic_uint64
struct ABTD_atomic_ptr
Macros
#define ABTD_ATOMIC_BOOL_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_INT_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_SIZE_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_INT32_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_UINT32_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_INT64_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_UINT64_STATIC_INITIALIZER(val)
#define ABTD_ATOMIC_PTR_STATIC_INITIALIZER(val)
Typedefs
typedef struct ABTD_atomic_bool ABTD_atomic_bool
typedef struct ABTD_atomic_int ABTD_atomic_int
typedef struct ABTD_atomic_size ABTD_atomic_size
typedef struct ABTD_atomic_int32 ABTD_atomic_int32
typedef struct ABTD_atomic_uint32 ABTD_atomic_uint32
typedef struct ABTD_atomic_int64 ABTD_atomic_int64
typedef struct ABTD_atomic_uint64 ABTD_atomic_uint64
typedef struct ABTD_atomic_ptr ABTD_atomic_ptr
Functions
static int ABTDI_atomic_val_cas_int (ABTD_atomic_int *ptr, int oldv, int newv, int weak)
static size_t ABTDI_atomic_val_cas_size (ABTD_atomic_size *ptr, size_t oldv, size_t newv, int weak)
static int32_t ABTDI_atomic_val_cas_int32 (ABTD_atomic_int32 *ptr, int32_t oldv, int32_t newv, int weak)
static uint32_t ABTDI_atomic_val_cas_uint32 (ABTD_atomic_uint32 *ptr, uint32_t oldv, uint32_t newv, int weak)
static int64_t ABTDI_atomic_val_cas_int64 (ABTD_atomic_int64 *ptr, int64_t oldv, int64_t newv, int weak)
static uint64_t ABTDI_atomic_val_cas_uint64 (ABTD_atomic_uint64 *ptr, uint64_t oldv, uint64_t newv, int weak)
static void * ABTDI_atomic_val_cas_ptr (ABTD_atomic_ptr *ptr, void *oldv, void *newv, int weak)
static int ABTDI_atomic_bool_cas_int (ABTD_atomic_int *ptr, int oldv, int newv, int weak)
static int ABTDI_atomic_bool_cas_size (ABTD_atomic_size *ptr, size_t oldv, size_t newv, int weak)
static int ABTDI_atomic_bool_cas_int32 (ABTD_atomic_int32 *ptr, int32_t oldv, int32_t newv, int weak)
static int ABTDI_atomic_bool_cas_uint32 (ABTD_atomic_uint32 *ptr, uint32_t oldv, uint32_t newv, int weak)
static int ABTDI_atomic_bool_cas_int64 (ABTD_atomic_int64 *ptr, int64_t oldv, int64_t newv, int weak)
static int ABTDI_atomic_bool_cas_uint64 (ABTD_atomic_uint64 *ptr, uint64_t oldv, uint64_t newv, int weak)
static int ABTDI_atomic_bool_cas_ptr (ABTD_atomic_ptr *ptr, void *oldv, void *newv, int weak)
static int ABTD_atomic_val_cas_weak_int (ABTD_atomic_int *ptr, int oldv, int newv)
static size_t ABTD_atomic_val_cas_weak_size (ABTD_atomic_size *ptr, size_t oldv, size_t newv)
static int32_t ABTD_atomic_val_cas_weak_int32 (ABTD_atomic_int32 *ptr, int32_t oldv, int32_t newv)
static uint32_t ABTD_atomic_val_cas_weak_uint32 (ABTD_atomic_uint32 *ptr, uint32_t oldv, uint32_t newv)
static int64_t ABTD_atomic_val_cas_weak_int64 (ABTD_atomic_int64 *ptr, int64_t oldv, int64_t newv)
static uint64_t ABTD_atomic_val_cas_weak_uint64 (ABTD_atomic_uint64 *ptr, uint64_t oldv, uint64_t newv)
static void * ABTD_atomic_val_cas_weak_ptr (ABTD_atomic_ptr *ptr, void *oldv, void *newv)
static int ABTD_atomic_val_cas_strong_int (ABTD_atomic_int *ptr, int oldv, int newv)
static size_t ABTD_atomic_val_cas_strong_size (ABTD_atomic_size *ptr, size_t oldv, size_t newv)
static int32_t ABTD_atomic_val_cas_strong_int32 (ABTD_atomic_int32 *ptr, int32_t oldv, int32_t newv)
static uint32_t ABTD_atomic_val_cas_strong_uint32 (ABTD_atomic_uint32 *ptr, uint32_t oldv, uint32_t newv)
static int64_t ABTD_atomic_val_cas_strong_int64 (ABTD_atomic_int64 *ptr, int64_t oldv, int64_t newv)
static uint64_t ABTD_atomic_val_cas_strong_uint64 (ABTD_atomic_uint64 *ptr, uint64_t oldv, uint64_t newv)
static void * ABTD_atomic_val_cas_strong_ptr (ABTD_atomic_ptr *ptr, void *oldv, void *newv)
static int ABTD_atomic_bool_cas_weak_int (ABTD_atomic_int *ptr, int oldv, int newv)
static int ABTD_atomic_bool_cas_weak_size (ABTD_atomic_size *ptr, size_t oldv, size_t newv)
static int ABTD_atomic_bool_cas_weak_int32 (ABTD_atomic_int32 *ptr, int32_t oldv, int32_t newv)
static int ABTD_atomic_bool_cas_weak_uint32 (ABTD_atomic_uint32 *ptr, uint32_t oldv, uint32_t newv)
static int ABTD_atomic_bool_cas_weak_int64 (ABTD_atomic_int64 *ptr, int64_t oldv, int64_t newv)
static int ABTD_atomic_bool_cas_weak_uint64 (ABTD_atomic_uint64 *ptr, uint64_t oldv, uint64_t newv)
static int ABTD_atomic_bool_cas_weak_ptr (ABTD_atomic_ptr *ptr, void *oldv, void *newv)
static int ABTD_atomic_bool_cas_strong_int (ABTD_atomic_int *ptr, int oldv, int newv)
static int ABTD_atomic_bool_cas_strong_size (ABTD_atomic_size *ptr, size_t oldv, size_t newv)
static int ABTD_atomic_bool_cas_strong_int32 (ABTD_atomic_int32 *ptr, int32_t oldv, int32_t newv)
static int ABTD_atomic_bool_cas_strong_uint32 (ABTD_atomic_uint32 *ptr, uint32_t oldv, uint32_t newv)
static int ABTD_atomic_bool_cas_strong_int64 (ABTD_atomic_int64 *ptr, int64_t oldv, int64_t newv)
static int ABTD_atomic_bool_cas_strong_uint64 (ABTD_atomic_uint64 *ptr, uint64_t oldv, uint64_t newv)
static int ABTD_atomic_bool_cas_strong_ptr (ABTD_atomic_ptr *ptr, void *oldv, void *newv)
static int ABTD_atomic_fetch_add_int (ABTD_atomic_int *ptr, int v)
static size_t ABTD_atomic_fetch_add_size (ABTD_atomic_size *ptr, size_t v)
static int32_t ABTD_atomic_fetch_add_int32 (ABTD_atomic_int32 *ptr, int32_t v)
static uint32_t ABTD_atomic_fetch_add_uint32 (ABTD_atomic_uint32 *ptr, uint32_t v)
static int64_t ABTD_atomic_fetch_add_int64 (ABTD_atomic_int64 *ptr, int64_t v)
static uint64_t ABTD_atomic_fetch_add_uint64 (ABTD_atomic_uint64 *ptr, uint64_t v)
static int ABTD_atomic_fetch_sub_int (ABTD_atomic_int *ptr, int v)
static size_t ABTD_atomic_fetch_sub_size (ABTD_atomic_size *ptr, size_t v)
static int32_t ABTD_atomic_fetch_sub_int32 (ABTD_atomic_int32 *ptr, int32_t v)
static uint32_t ABTD_atomic_fetch_sub_uint32 (ABTD_atomic_uint32 *ptr, uint32_t v)
static int64_t ABTD_atomic_fetch_sub_int64 (ABTD_atomic_int64 *ptr, int64_t v)
static uint64_t ABTD_atomic_fetch_sub_uint64 (ABTD_atomic_uint64 *ptr, uint64_t v)
static int ABTD_atomic_fetch_and_int (ABTD_atomic_int *ptr, int v)
static size_t ABTD_atomic_fetch_and_size (ABTD_atomic_size *ptr, size_t v)
static int32_t ABTD_atomic_fetch_and_int32 (ABTD_atomic_int32 *ptr, int32_t v)
static uint32_t ABTD_atomic_fetch_and_uint32 (ABTD_atomic_uint32 *ptr, uint32_t v)
static int64_t ABTD_atomic_fetch_and_int64 (ABTD_atomic_int64 *ptr, int64_t v)
static uint64_t ABTD_atomic_fetch_and_uint64 (ABTD_atomic_uint64 *ptr, uint64_t v)
static int ABTD_atomic_fetch_or_int (ABTD_atomic_int *ptr, int v)
static size_t ABTD_atomic_fetch_or_size (ABTD_atomic_size *ptr, size_t v)
static int32_t ABTD_atomic_fetch_or_int32 (ABTD_atomic_int32 *ptr, int32_t v)
static uint32_t ABTD_atomic_fetch_or_uint32 (ABTD_atomic_uint32 *ptr, uint32_t v)
static int64_t ABTD_atomic_fetch_or_int64 (ABTD_atomic_int64 *ptr, int64_t v)
static uint64_t ABTD_atomic_fetch_or_uint64 (ABTD_atomic_uint64 *ptr, uint64_t v)
static int ABTD_atomic_fetch_xor_int (ABTD_atomic_int *ptr, int v)
static size_t ABTD_atomic_fetch_xor_size (ABTD_atomic_size *ptr, size_t v)
static int32_t ABTD_atomic_fetch_xor_int32 (ABTD_atomic_int32 *ptr, int32_t v)
static uint32_t ABTD_atomic_fetch_xor_uint32 (ABTD_atomic_uint32 *ptr, uint32_t v)
static int64_t ABTD_atomic_fetch_xor_int64 (ABTD_atomic_int64 *ptr, int64_t v)
static uint64_t ABTD_atomic_fetch_xor_uint64 (ABTD_atomic_uint64 *ptr, uint64_t v)
static uint16_t ABTD_atomic_test_and_set_bool (ABTD_atomic_bool *ptr)
static void ABTD_atomic_relaxed_clear_bool (ABTD_atomic_bool *ptr)
static void ABTD_atomic_release_clear_bool (ABTD_atomic_bool *ptr)
static ABT_bool ABTD_atomic_relaxed_load_bool (const ABTD_atomic_bool *ptr)
static int ABTD_atomic_relaxed_load_int (const ABTD_atomic_int *ptr)
static size_t ABTD_atomic_relaxed_load_size (const ABTD_atomic_size *ptr)
static int32_t ABTD_atomic_relaxed_load_int32 (const ABTD_atomic_int32 *ptr)
static uint32_t ABTD_atomic_relaxed_load_uint32 (const ABTD_atomic_uint32 *ptr)
static int64_t ABTD_atomic_relaxed_load_int64 (const ABTD_atomic_int64 *ptr)
static uint64_t ABTD_atomic_relaxed_load_uint64 (const ABTD_atomic_uint64 *ptr)
static void * ABTD_atomic_relaxed_load_ptr (const ABTD_atomic_ptr *ptr)
static ABT_bool ABTD_atomic_acquire_load_bool (const ABTD_atomic_bool *ptr)
static int ABTD_atomic_acquire_load_int (const ABTD_atomic_int *ptr)
static size_t ABTD_atomic_acquire_load_size (const ABTD_atomic_size *ptr)
static int32_t ABTD_atomic_acquire_load_int32 (const ABTD_atomic_int32 *ptr)
static uint32_t ABTD_atomic_acquire_load_uint32 (const ABTD_atomic_uint32 *ptr)
static int64_t ABTD_atomic_acquire_load_int64 (const ABTD_atomic_int64 *ptr)
static uint64_t ABTD_atomic_acquire_load_uint64 (const ABTD_atomic_uint64 *ptr)
static void * ABTD_atomic_acquire_load_ptr (const ABTD_atomic_ptr *ptr)
static void ABTD_atomic_relaxed_store_int (ABTD_atomic_int *ptr, int val)
static void ABTD_atomic_relaxed_store_size (ABTD_atomic_size *ptr, size_t val)
static void ABTD_atomic_relaxed_store_int32 (ABTD_atomic_int32 *ptr, int32_t val)
static void ABTD_atomic_relaxed_store_uint32 (ABTD_atomic_uint32 *ptr, uint32_t val)
static void ABTD_atomic_relaxed_store_int64 (ABTD_atomic_int64 *ptr, int64_t val)
static void ABTD_atomic_relaxed_store_uint64 (ABTD_atomic_uint64 *ptr, uint64_t val)
static void ABTD_atomic_relaxed_store_ptr (ABTD_atomic_ptr *ptr, void *val)
static void ABTD_atomic_release_store_int (ABTD_atomic_int *ptr, int val)
static void ABTD_atomic_release_store_size (ABTD_atomic_size *ptr, size_t val)
static void ABTD_atomic_release_store_int32 (ABTD_atomic_int32 *ptr, int32_t val)
static void ABTD_atomic_release_store_uint32 (ABTD_atomic_uint32 *ptr, uint32_t val)
static void ABTD_atomic_release_store_int64 (ABTD_atomic_int64 *ptr, int64_t val)
static void ABTD_atomic_release_store_uint64 (ABTD_atomic_uint64 *ptr, uint64_t val)
static void ABTD_atomic_release_store_ptr (ABTD_atomic_ptr *ptr, void *val)
static int ABTD_atomic_exchange_int (ABTD_atomic_int *ptr, int v)
static size_t ABTD_atomic_exchange_size (ABTD_atomic_size *ptr, size_t v)
static int32_t ABTD_atomic_exchange_int32 (ABTD_atomic_int32 *ptr, int32_t v)
static uint32_t ABTD_atomic_exchange_uint32 (ABTD_atomic_uint32 *ptr, uint32_t v)
static int64_t ABTD_atomic_exchange_int64 (ABTD_atomic_int64 *ptr, int64_t v)
static uint64_t ABTD_atomic_exchange_uint64 (ABTD_atomic_uint64 *ptr, uint64_t v)
static void * ABTD_atomic_exchange_ptr (ABTD_atomic_ptr *ptr, void *v)
static void ABTD_atomic_mem_barrier (void)
static void ABTD_compiler_barrier (void)
static void ABTD_atomic_pause (void)
Macro Definition Documentation
#define ABTD_ATOMIC_BOOL_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 43 of file abtd_atomic.h.
#define ABTD_ATOMIC_INT32_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 55 of file abtd_atomic.h.
#define ABTD_ATOMIC_INT64_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 63 of file abtd_atomic.h.
#define ABTD_ATOMIC_INT_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 47 of file abtd_atomic.h.
#define ABTD_ATOMIC_PTR_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 71 of file abtd_atomic.h.
#define ABTD_ATOMIC_SIZE_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 51 of file abtd_atomic.h.
#define ABTD_ATOMIC_UINT32_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 59 of file abtd_atomic.h.
#define ABTD_ATOMIC_UINT64_STATIC_INITIALIZER (val)
Value:
{                                                                          \
        (val)                                                                  \
    }
Definition at line 67 of file abtd_atomic.h.
Typedef Documentation
typedef struct ABTD_atomic_bool ABTD_atomic_bool
typedef struct ABTD_atomic_int ABTD_atomic_int
typedef struct ABTD_atomic_int32 ABTD_atomic_int32
typedef struct ABTD_atomic_int64 ABTD_atomic_int64
typedef struct ABTD_atomic_ptr ABTD_atomic_ptr
typedef struct ABTD_atomic_size ABTD_atomic_size
typedef struct ABTD_atomic_uint32 ABTD_atomic_uint32
typedef struct ABTD_atomic_uint64 ABTD_atomic_uint64
Function Documentation
static ABT_bool ABTD_atomic_acquire_load_bool (const ABTD_atomic_bool * ptr) inline static
Definition at line 861 of file abtd_atomic.h.
Referenced by ABTI_spinlock_is_locked().
static int ABTD_atomic_acquire_load_int (const ABTD_atomic_int * ptr) inline static
Definition at line 878 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_int(), ABTI_waitlist_wait_and_unlock(), ABTI_waitlist_wait_timedout_and_unlock(), ABTI_ythread_print_stack(), ABTI_ythread_set_ready(), info_trigger_print_all_thread_stacks(), pool_remove(), pool_remove_private(), pool_remove_shared(), thread_join_yield_thread(), and unit_is_in_pool().
static int32_t ABTD_atomic_acquire_load_int32 (const ABTD_atomic_int32 * ptr) inline static
Definition at line 911 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_int32(), ABTI_pool_get_total_size(), ABTI_pool_print(), ABTI_pool_release(), and ABTI_sched_get_effective_size().
static int64_t ABTD_atomic_acquire_load_int64 (const ABTD_atomic_int64 * ptr) inline static
Definition at line 945 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_int64().
static void* ABTD_atomic_acquire_load_ptr (const ABTD_atomic_ptr * ptr) inline static
Definition at line 979 of file abtd_atomic.h.
Referenced by ABTD_atomic_acquire_load_ythread_context_ptr(), ABTD_atomic_exchange_ptr(), ABTI_ktable_get(), ABTI_ktable_set(), ABTI_ktable_set_impl(), ABTI_mem_pool_take_bucket(), and thread_free().
static size_t ABTD_atomic_acquire_load_size (const ABTD_atomic_size * ptr) inline static
Definition at line 894 of file abtd_atomic.h.
Referenced by ABT_future_test(), and ABTD_atomic_exchange_size().
static uint32_t ABTD_atomic_acquire_load_uint32 (const ABTD_atomic_uint32 * ptr) inline static
Definition at line 928 of file abtd_atomic.h.
Referenced by ABT_initialized(), ABTD_atomic_exchange_uint32(), ABTI_sched_has_to_stop(), ABTI_sched_print(), and ABTI_ythread_set_ready().
static uint64_t ABTD_atomic_acquire_load_uint64 (const ABTD_atomic_uint64 * ptr) inline static
Definition at line 962 of file abtd_atomic.h.
Referenced by ABT_xstream_barrier_wait(), ABTD_atomic_exchange_uint64(), ABTI_tool_event_thread_impl(), and ABTI_tool_event_thread_update_callback().
static int ABTD_atomic_bool_cas_strong_int (ABTD_atomic_int * ptr, int oldv, int newv) inline static
Definition at line 385 of file abtd_atomic.h.
Referenced by info_trigger_print_all_thread_stacks().
static int ABTD_atomic_bool_cas_strong_int32 (ABTD_atomic_int32 * ptr, int32_t oldv, int32_t newv) inline static
Definition at line 397 of file abtd_atomic.h.
static int ABTD_atomic_bool_cas_strong_int64 (ABTD_atomic_int64 * ptr, int64_t oldv, int64_t newv) inline static
Definition at line 410 of file abtd_atomic.h.
static int ABTD_atomic_bool_cas_strong_ptr (ABTD_atomic_ptr * ptr, void * oldv, void * newv) inline static
Definition at line 423 of file abtd_atomic.h.
static int ABTD_atomic_bool_cas_strong_size (ABTD_atomic_size * ptr, size_t oldv, size_t newv) inline static
Definition at line 391 of file abtd_atomic.h.
static int ABTD_atomic_bool_cas_strong_uint32 (ABTD_atomic_uint32 * ptr, uint32_t oldv, uint32_t newv) inline static
Definition at line 403 of file abtd_atomic.h.
static int ABTD_atomic_bool_cas_strong_uint64 (ABTD_atomic_uint64 * ptr, uint64_t oldv, uint64_t newv) inline static
Definition at line 416 of file abtd_atomic.h.
static int ABTD_atomic_bool_cas_weak_int (ABTD_atomic_int * ptr, int oldv, int newv) inline static
Definition at line 343 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_int().
static int ABTD_atomic_bool_cas_weak_int32 (ABTD_atomic_int32 * ptr, int32_t oldv, int32_t newv) inline static
Definition at line 355 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_int32().
static int ABTD_atomic_bool_cas_weak_int64 (ABTD_atomic_int64 * ptr, int64_t oldv, int64_t newv) inline static
Definition at line 367 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_int64().
static int ABTD_atomic_bool_cas_weak_ptr (ABTD_atomic_ptr * ptr, void * oldv, void * newv) inline static
Definition at line 379 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_ptr(), ABTI_ktable_set(), and ABTI_mem_pool_take_bucket().
static int ABTD_atomic_bool_cas_weak_size (ABTD_atomic_size * ptr, size_t oldv, size_t newv) inline static
Definition at line 349 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_size().
static int ABTD_atomic_bool_cas_weak_uint32 (ABTD_atomic_uint32 * ptr, uint32_t oldv, uint32_t newv) inline static
Definition at line 361 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_uint32().
static int ABTD_atomic_bool_cas_weak_uint64 (ABTD_atomic_uint64 * ptr, uint64_t oldv, uint64_t newv) inline static
Definition at line 373 of file abtd_atomic.h.
Referenced by ABTD_atomic_exchange_uint64().
static int ABTD_atomic_exchange_int (ABTD_atomic_int * ptr, int v) inline static
Definition at line 1148 of file abtd_atomic.h.
static int32_t ABTD_atomic_exchange_int32 (ABTD_atomic_int32 * ptr, int32_t v) inline static
Definition at line 1174 of file abtd_atomic.h.
static int64_t ABTD_atomic_exchange_int64 (ABTD_atomic_int64 * ptr, int64_t v) inline static
Definition at line 1202 of file abtd_atomic.h.
static void* ABTD_atomic_exchange_ptr (ABTD_atomic_ptr * ptr, void * v) inline static
Definition at line 1230 of file abtd_atomic.h.
static size_t ABTD_atomic_exchange_size (ABTD_atomic_size * ptr, size_t v) inline static
Definition at line 1161 of file abtd_atomic.h.
static uint32_t ABTD_atomic_exchange_uint32 (ABTD_atomic_uint32 * ptr, uint32_t v) inline static
Definition at line 1188 of file abtd_atomic.h.
static uint64_t ABTD_atomic_exchange_uint64 (ABTD_atomic_uint64 * ptr, uint64_t v) inline static
Definition at line 1216 of file abtd_atomic.h.
static int ABTD_atomic_fetch_add_int (ABTD_atomic_int * ptr, int v) inline static
Definition at line 429 of file abtd_atomic.h.
static int32_t ABTD_atomic_fetch_add_int32 (ABTD_atomic_int32 * ptr, int32_t v) inline static
Definition at line 447 of file abtd_atomic.h.
Referenced by ABTI_pool_inc_num_blocked(), and ABTI_pool_retain().
static int64_t ABTD_atomic_fetch_add_int64 (ABTD_atomic_int64 * ptr, int64_t v) inline static
Definition at line 467 of file abtd_atomic.h.
static size_t ABTD_atomic_fetch_add_size (ABTD_atomic_size * ptr, size_t v) inline static
Definition at line 438 of file abtd_atomic.h.
static uint32_t ABTD_atomic_fetch_add_uint32 (ABTD_atomic_uint32 * ptr, uint32_t v) inline static
Definition at line 457 of file abtd_atomic.h.
Referenced by ABT_key_create().
static uint64_t ABTD_atomic_fetch_add_uint64 (ABTD_atomic_uint64 * ptr, uint64_t v) inline static
Definition at line 477 of file abtd_atomic.h.
Referenced by pool_get_new_id().
static int ABTD_atomic_fetch_and_int (ABTD_atomic_int * ptr, int v) inline static
Definition at line 545 of file abtd_atomic.h.
static int32_t ABTD_atomic_fetch_and_int32 (ABTD_atomic_int32 * ptr, int32_t v) inline static
Definition at line 563 of file abtd_atomic.h.
static int64_t ABTD_atomic_fetch_and_int64 (ABTD_atomic_int64 * ptr, int64_t v) inline static
Definition at line 583 of file abtd_atomic.h.
static size_t ABTD_atomic_fetch_and_size (ABTD_atomic_size * ptr, size_t v) inline static
Definition at line 554 of file abtd_atomic.h.
static uint32_t ABTD_atomic_fetch_and_uint32 (ABTD_atomic_uint32 * ptr, uint32_t v) inline static
Definition at line 573 of file abtd_atomic.h.
Referenced by ABTI_sched_unset_request(), and ABTI_thread_unset_request().
static uint64_t ABTD_atomic_fetch_and_uint64 (ABTD_atomic_uint64 * ptr, uint64_t v) inline static
Definition at line 593 of file abtd_atomic.h.
static int ABTD_atomic_fetch_or_int (ABTD_atomic_int * ptr, int v) inline static
Definition at line 603 of file abtd_atomic.h.
static int32_t ABTD_atomic_fetch_or_int32 (ABTD_atomic_int32 * ptr, int32_t v) inline static
Definition at line 621 of file abtd_atomic.h.
static int64_t ABTD_atomic_fetch_or_int64 (ABTD_atomic_int64 * ptr, int64_t v) inline static
Definition at line 641 of file abtd_atomic.h.
static size_t ABTD_atomic_fetch_or_size (ABTD_atomic_size * ptr, size_t v) inline static
Definition at line 612 of file abtd_atomic.h.
static uint32_t ABTD_atomic_fetch_or_uint32 (ABTD_atomic_uint32 * ptr, uint32_t v) inline static
Definition at line 631 of file abtd_atomic.h.
Referenced by ABT_xstream_cancel(), ABT_xstream_exit(), ABTD_ythread_cancel(), ABTI_sched_set_request(), ABTI_thread_set_request(), ABTI_ythread_context_switch_to_child_internal(), and ythread_terminate().
static uint64_t ABTD_atomic_fetch_or_uint64 (ABTD_atomic_uint64 * ptr, uint64_t v) inline static
Definition at line 651 of file abtd_atomic.h.
static int ABTD_atomic_fetch_sub_int (ABTD_atomic_int * ptr, int v) inline static
Definition at line 487 of file abtd_atomic.h.
static int32_t ABTD_atomic_fetch_sub_int32 (ABTD_atomic_int32 * ptr, int32_t v) inline static
Definition at line 505 of file abtd_atomic.h.
Referenced by ABTI_pool_dec_num_blocked(), and ABTI_pool_release().
static int64_t ABTD_atomic_fetch_sub_int64 (ABTD_atomic_int64 * ptr, int64_t v) inline static
Definition at line 525 of file abtd_atomic.h.
static size_t ABTD_atomic_fetch_sub_size (ABTD_atomic_size * ptr, size_t v) inline static
Definition at line 496 of file abtd_atomic.h.
static uint32_t ABTD_atomic_fetch_sub_uint32 (ABTD_atomic_uint32 * ptr, uint32_t v) inline static
Definition at line 515 of file abtd_atomic.h.
static uint64_t ABTD_atomic_fetch_sub_uint64 (ABTD_atomic_uint64 * ptr, uint64_t v) inline static
Definition at line 535 of file abtd_atomic.h.
static int ABTD_atomic_fetch_xor_int (ABTD_atomic_int * ptr, int v) inline static
Definition at line 661 of file abtd_atomic.h.
static int32_t ABTD_atomic_fetch_xor_int32 (ABTD_atomic_int32 * ptr, int32_t v) inline static
Definition at line 679 of file abtd_atomic.h.
static int64_t ABTD_atomic_fetch_xor_int64 (ABTD_atomic_int64 * ptr, int64_t v) inline static
Definition at line 699 of file abtd_atomic.h.
static size_t ABTD_atomic_fetch_xor_size (ABTD_atomic_size * ptr, size_t v) inline static
Definition at line 670 of file abtd_atomic.h.
static uint32_t ABTD_atomic_fetch_xor_uint32 (ABTD_atomic_uint32 * ptr, uint32_t v) inline static
Definition at line 689 of file abtd_atomic.h.
static uint64_t ABTD_atomic_fetch_xor_uint64 (ABTD_atomic_uint64 * ptr, uint64_t v) inline static
Definition at line 709 of file abtd_atomic.h.
static void ABTD_atomic_mem_barrier (void) inline static
Definition at line 1243 of file abtd_atomic.h.
static void ABTD_atomic_pause (void) inline static
Definition at line 1257 of file abtd_atomic.h.
Referenced by ABT_xstream_barrier_wait(), ABTI_ktable_set(), ABTI_waitlist_wait_timedout_and_unlock(), ABTI_ythread_set_ready(), and thread_join_busywait().
static void ABTD_atomic_relaxed_clear_bool (ABTD_atomic_bool * ptr) inline static
Definition at line 729 of file abtd_atomic.h.
Referenced by ABTI_spinlock_clear().
static ABT_bool ABTD_atomic_relaxed_load_bool (const ABTD_atomic_bool * ptr) inline static
Definition at line 748 of file abtd_atomic.h.
static int ABTD_atomic_relaxed_load_int (const ABTD_atomic_int * ptr) inline static
Definition at line 763 of file abtd_atomic.h.
Referenced by ABT_thread_revive(), ABT_xstream_revive(), and ABTI_thread_revive().
static int32_t ABTD_atomic_relaxed_load_int32 (const ABTD_atomic_int32 * ptr) inline static
Definition at line 790 of file abtd_atomic.h.
static int64_t ABTD_atomic_relaxed_load_int64 (const ABTD_atomic_int64 * ptr) inline static
Definition at line 818 of file abtd_atomic.h.
static void* ABTD_atomic_relaxed_load_ptr (const ABTD_atomic_ptr * ptr) inline static
Definition at line 846 of file abtd_atomic.h.
Referenced by ABTD_atomic_relaxed_load_ythread_context_ptr(), ABTI_ktable_free(), ABTI_mem_pool_destroy_global_pool(), ABTI_sync_lifo_pop_unsafe(), and ABTI_sync_lifo_push_unsafe().
static size_t ABTD_atomic_relaxed_load_size (const ABTD_atomic_size * ptr) inline static
Definition at line 776 of file abtd_atomic.h.
Referenced by ABT_future_set(), and ABT_future_wait().
static uint32_t ABTD_atomic_relaxed_load_uint32 (const ABTD_atomic_uint32 * ptr) inline static
Definition at line 804 of file abtd_atomic.h.
Referenced by ABTI_tool_event_ythread_yield_impl().
static uint64_t ABTD_atomic_relaxed_load_uint64 (const ABTD_atomic_uint64 * ptr) inline static
Definition at line 832 of file abtd_atomic.h.
Referenced by ABT_xstream_barrier_wait().
static void ABTD_atomic_relaxed_store_int (ABTD_atomic_int * ptr, int val) inline static
Definition at line 996 of file abtd_atomic.h.
Referenced by ABT_cond_timedwait(), ABT_xstream_revive(), ABTI_pool_add_thread(), ABTI_thread_revive(), ABTI_waitlist_wait_and_unlock(), ABTI_waitlist_wait_timedout_and_unlock(), init_library(), task_create(), and unit_create_from_thread().
static void ABTD_atomic_relaxed_store_int32 (ABTD_atomic_int32 * ptr, int32_t val) inline static
Definition at line 1015 of file abtd_atomic.h.
static void ABTD_atomic_relaxed_store_int64 (ABTD_atomic_int64 * ptr, int64_t val) inline static
Definition at line 1035 of file abtd_atomic.h.
static void ABTD_atomic_relaxed_store_ptr (ABTD_atomic_ptr * ptr, void * val) inline static
Definition at line 1055 of file abtd_atomic.h.
Referenced by ABTD_atomic_relaxed_store_ythread_context_ptr(), ABTI_ktable_set_impl(), ABTI_mem_pool_init_global_pool(), ABTI_sync_lifo_init(), ABTI_sync_lifo_pop_unsafe(), ABTI_sync_lifo_push_unsafe(), task_create(), thread_migrate_to_pool(), and ythread_create().
static void ABTD_atomic_relaxed_store_size (ABTD_atomic_size * ptr, size_t val) inline static
Definition at line 1005 of file abtd_atomic.h.
Referenced by ABT_future_create().
static void ABTD_atomic_relaxed_store_uint32 (ABTD_atomic_uint32 * ptr, uint32_t val) inline static
Definition at line 1025 of file abtd_atomic.h.
Referenced by ABT_xstream_revive(), ABTI_thread_revive(), sched_create(), and task_create().
static void ABTD_atomic_relaxed_store_uint64 (ABTD_atomic_uint64 * ptr, uint64_t val) inline static
Definition at line 1045 of file abtd_atomic.h.
Referenced by ABT_xstream_barrier_create(), ABTI_sched_reset_id(), and init_library().
static void ABTD_atomic_release_clear_bool (ABTD_atomic_bool * ptr) inline static
Definition at line 738 of file abtd_atomic.h.
Referenced by ABTI_spinlock_release().
static void ABTD_atomic_release_store_int (ABTD_atomic_int * ptr, int val) inline static
Definition at line 1065 of file abtd_atomic.h.
Referenced by ABTI_waitlist_broadcast(), ABTI_waitlist_signal(), ABTI_xstream_terminate_thread(), ABTI_ythread_set_blocked(), ABTI_ythread_yield(), info_trigger_print_all_thread_stacks(), pool_pop(), pool_pop_private(), pool_pop_shared(), pool_pop_timedwait(), pool_pop_wait(), pool_push(), pool_push_private(), pool_push_shared(), pool_remove(), pool_remove_private(), pool_remove_shared(), ythread_create(), and ythread_terminate().
static void ABTD_atomic_release_store_int32 (ABTD_atomic_int32 * ptr, int32_t val) inline static
Definition at line 1088 of file abtd_atomic.h.
Referenced by pool_create().
static void ABTD_atomic_release_store_int64 (ABTD_atomic_int64 * ptr, int64_t val) inline static
Definition at line 1112 of file abtd_atomic.h.
static void ABTD_atomic_release_store_ptr (ABTD_atomic_ptr * ptr, void * val) inline static
Definition at line 1136 of file abtd_atomic.h.
Referenced by ABTD_atomic_release_store_ythread_context_ptr(), ABTI_ktable_set(), and ABTI_ktable_set_impl().
static void ABTD_atomic_release_store_size (ABTD_atomic_size * ptr, size_t val) inline static
Definition at line 1076 of file abtd_atomic.h.
Referenced by ABT_future_reset(), and ABT_future_set().
static void ABTD_atomic_release_store_uint32 (ABTD_atomic_uint32 * ptr, uint32_t val) inline static
Definition at line 1100 of file abtd_atomic.h.
Referenced by ABTI_ythread_context_switch_to_child_internal(), finailze_library(), init_library(), ythread_create(), and ythread_terminate().
static void ABTD_atomic_release_store_uint64 (ABTD_atomic_uint64 * ptr, uint64_t val) inline static
Definition at line 1124 of file abtd_atomic.h.
Referenced by ABT_xstream_barrier_wait(), ABTI_pool_reset_id(), and ABTI_tool_event_thread_update_callback().
static uint16_t ABTD_atomic_test_and_set_bool (ABTD_atomic_bool * ptr) inline static
Definition at line 719 of file abtd_atomic.h.
Referenced by ABTI_spinlock_acquire(), and ABTI_spinlock_try_acquire().
static int ABTD_atomic_val_cas_strong_int (ABTD_atomic_int * ptr, int oldv, int newv) inline static
Definition at line 297 of file abtd_atomic.h.
static int32_t ABTD_atomic_val_cas_strong_int32 (ABTD_atomic_int32 * ptr, int32_t oldv, int32_t newv) inline static
Definition at line 309 of file abtd_atomic.h.
static int64_t ABTD_atomic_val_cas_strong_int64 (ABTD_atomic_int64 * ptr, int64_t oldv, int64_t newv) inline static
Definition at line 323 of file abtd_atomic.h.
static void* ABTD_atomic_val_cas_strong_ptr (ABTD_atomic_ptr * ptr, void * oldv, void * newv) inline static
Definition at line 337 of file abtd_atomic.h.
static size_t ABTD_atomic_val_cas_strong_size (ABTD_atomic_size * ptr, size_t oldv, size_t newv) inline static
Definition at line 303 of file abtd_atomic.h.
static uint32_t ABTD_atomic_val_cas_strong_uint32 (ABTD_atomic_uint32 * ptr, uint32_t oldv, uint32_t newv) inline static
Definition at line 317 of file abtd_atomic.h.
static uint64_t ABTD_atomic_val_cas_strong_uint64 (ABTD_atomic_uint64 * ptr, uint64_t oldv, uint64_t newv) inline static
Definition at line 331 of file abtd_atomic.h.
static int ABTD_atomic_val_cas_weak_int (ABTD_atomic_int * ptr, int oldv, int newv) inline static
Definition at line 253 of file abtd_atomic.h.
static int32_t ABTD_atomic_val_cas_weak_int32 (ABTD_atomic_int32 * ptr, int32_t oldv, int32_t newv) inline static
Definition at line 265 of file abtd_atomic.h.
static int64_t ABTD_atomic_val_cas_weak_int64 (ABTD_atomic_int64 * ptr, int64_t oldv, int64_t newv) inline static
Definition at line 278 of file abtd_atomic.h.
static void* ABTD_atomic_val_cas_weak_ptr (ABTD_atomic_ptr * ptr, void * oldv, void * newv) inline static
Definition at line 291 of file abtd_atomic.h.
static size_t ABTD_atomic_val_cas_weak_size (ABTD_atomic_size * ptr, size_t oldv, size_t newv) inline static
Definition at line 259 of file abtd_atomic.h.
static uint32_t ABTD_atomic_val_cas_weak_uint32 (ABTD_atomic_uint32 * ptr, uint32_t oldv, uint32_t newv) inline static
Definition at line 271 of file abtd_atomic.h.
static uint64_t ABTD_atomic_val_cas_weak_uint64 (ABTD_atomic_uint64 * ptr, uint64_t oldv, uint64_t newv) inline static
Definition at line 284 of file abtd_atomic.h.
static void ABTD_compiler_barrier (void) inline static
Definition at line 1252 of file abtd_atomic.h.
static int ABTDI_atomic_bool_cas_int (ABTD_atomic_int * ptr, int oldv, int newv, int weak) inline static
Definition at line 172 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_int(), and ABTD_atomic_bool_cas_weak_int().
static int ABTDI_atomic_bool_cas_int32 (ABTD_atomic_int32 * ptr, int32_t oldv, int32_t newv, int weak) inline static
Definition at line 194 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_int32(), and ABTD_atomic_bool_cas_weak_int32().
static int ABTDI_atomic_bool_cas_int64 (ABTD_atomic_int64 * ptr, int64_t oldv, int64_t newv, int weak) inline static
Definition at line 218 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_int64(), and ABTD_atomic_bool_cas_weak_int64().
static int ABTDI_atomic_bool_cas_ptr (ABTD_atomic_ptr * ptr, void * oldv, void * newv, int weak) inline static
Definition at line 242 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_ptr(), and ABTD_atomic_bool_cas_weak_ptr().
static int ABTDI_atomic_bool_cas_size (ABTD_atomic_size * ptr, size_t oldv, size_t newv, int weak) inline static
Definition at line 183 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_size(), and ABTD_atomic_bool_cas_weak_size().
static int ABTDI_atomic_bool_cas_uint32 (ABTD_atomic_uint32 * ptr, uint32_t oldv, uint32_t newv, int weak) inline static
Definition at line 206 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_uint32(), and ABTD_atomic_bool_cas_weak_uint32().
static int ABTDI_atomic_bool_cas_uint64 (ABTD_atomic_uint64 * ptr, uint64_t oldv, uint64_t newv, int weak) inline static
Definition at line 230 of file abtd_atomic.h.
Referenced by ABTD_atomic_bool_cas_strong_uint64(), and ABTD_atomic_bool_cas_weak_uint64().
static int ABTDI_atomic_val_cas_int (ABTD_atomic_int * ptr, int oldv, int newv, int weak) inline static
Definition at line 76 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_int(), and ABTD_atomic_val_cas_weak_int().
static int32_t ABTDI_atomic_val_cas_int32 (ABTD_atomic_int32 * ptr, int32_t oldv, int32_t newv, int weak) inline static
Definition at line 103 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_int32(), and ABTD_atomic_val_cas_weak_int32().
static int64_t ABTDI_atomic_val_cas_int64 (ABTD_atomic_int64 * ptr, int64_t oldv, int64_t newv, int weak) inline static
Definition at line 131 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_int64(), and ABTD_atomic_val_cas_weak_int64().
static void* ABTDI_atomic_val_cas_ptr (ABTD_atomic_ptr * ptr, void * oldv, void * newv, int weak) inline static
Definition at line 159 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_ptr(), and ABTD_atomic_val_cas_weak_ptr().
static size_t ABTDI_atomic_val_cas_size (ABTD_atomic_size * ptr, size_t oldv, size_t newv, int weak) inline static
Definition at line 89 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_size(), and ABTD_atomic_val_cas_weak_size().
static uint32_t ABTDI_atomic_val_cas_uint32 (ABTD_atomic_uint32 * ptr, uint32_t oldv, uint32_t newv, int weak) inline static
Definition at line 117 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_uint32(), and ABTD_atomic_val_cas_weak_uint32().
static uint64_t ABTDI_atomic_val_cas_uint64 (ABTD_atomic_uint64 * ptr, uint64_t oldv, uint64_t newv, int weak) inline static
Definition at line 145 of file abtd_atomic.h.
Referenced by ABTD_atomic_val_cas_strong_uint64(), and ABTD_atomic_val_cas_weak_uint64().