ARGOBOTS: src/include/abti_config.h File Reference
abti_config.h File Reference
Functions
static ABTI_sched_config * ABTI_sched_config_get_ptr (ABT_sched_config config)
static ABT_sched_config ABTI_sched_config_get_handle (ABTI_sched_config *p_config)
Function Documentation
ABTI_sched_config_get_handle()
static ABT_sched_config ABTI_sched_config_get_handle (ABTI_sched_config * p_config) inline static
Definition at line 28 of file abti_config.h.
Referenced by ABT_sched_config_create(), and sched_create().
ABTI_sched_config_get_ptr()
static ABTI_sched_config* ABTI_sched_config_get_ptr (ABT_sched_config config) inline static
Definition at line 12 of file abti_config.h.
Referenced by ABT_sched_config_free(), ABT_sched_config_read(), ABT_sched_create(), ABT_sched_create_basic(), ABT_xstream_create_basic(), and sched_init().