ARGOBOTS: src/global.c File Reference
global.c File Reference
#include "abti.h"
Functions
static ABTU_ret_err int init_library (void)
static ABTU_ret_err int finailze_library (void)
static ABT_bool is_initialized_library (void)
int ABT_init (int argc, char **argv)
Initialize the Argobots execution environment.
int ABT_finalize (void)
Finalize the Argobots execution environment.
int ABT_initialized (void)
Check if the Argobots execution environment has been initialized.
ABT_bool ABTI_initialized (void)
Variables
ABTI_global * gp_ABTI_global = NULL
static uint32_t g_ABTI_num_inits = 0
static ABTD_spinlock g_ABTI_init_lock = ABTD_SPINLOCK_STATIC_INITIALIZER()
static ABTD_atomic_uint32 g_ABTI_initialized
Function Documentation
ABTI_initialized()
ABT_bool ABTI_initialized (void)
Definition at line 187 of file global.c.
Referenced by ABT_barrier_create(), ABT_barrier_free(), ABT_barrier_get_num_waiters(), ABT_barrier_reinit(), ABT_barrier_wait(), ABT_cond_create(), ABT_cond_free(), ABT_eventual_create(), ABT_eventual_free(), ABT_eventual_test(), ABT_eventual_wait(), ABT_finalize(), ABT_future_create(), ABT_future_free(), ABT_future_reset(), ABT_future_set(), ABT_future_test(), ABT_future_wait(), ABT_key_create(), ABT_key_free(), ABT_key_get(), ABT_key_set(), ABT_mutex_attr_create(), ABT_mutex_attr_free(), ABT_mutex_attr_get_recursive(), ABT_mutex_attr_set_recursive(), ABT_mutex_create(), ABT_mutex_create_with_attr(), ABT_mutex_free(), ABT_mutex_get_attr(), ABT_pool_add_sched(), ABT_pool_config_create(), ABT_pool_config_free(), ABT_pool_config_get(), ABT_pool_config_set(), ABT_pool_create(), ABT_pool_create_basic(), ABT_pool_free(), ABT_pool_get_access(), ABT_pool_get_data(), ABT_pool_get_id(), ABT_pool_get_size(), ABT_pool_get_total_size(), ABT_pool_is_empty(), ABT_pool_pop(), ABT_pool_pop_timedwait(), ABT_pool_pop_wait(), ABT_pool_print_all(), ABT_pool_print_all_threads(), ABT_pool_push(), ABT_pool_remove(), ABT_pool_set_data(), ABT_pool_user_def_create(), ABT_pool_user_def_free(), ABT_pool_user_def_set_free(), ABT_pool_user_def_set_get_size(), ABT_pool_user_def_set_init(), ABT_pool_user_def_set_pop_many(), ABT_pool_user_def_set_pop_wait(), ABT_pool_user_def_set_print_all(), ABT_pool_user_def_set_push_many(), ABT_rwlock_create(), ABT_rwlock_free(), ABT_rwlock_rdlock(), ABT_rwlock_unlock(), ABT_rwlock_wrlock(), ABT_sched_config_create(), ABT_sched_config_free(), ABT_sched_config_get(), ABT_sched_config_read(), ABT_sched_config_set(), ABT_sched_create(), ABT_sched_create_basic(), ABT_sched_exit(), ABT_sched_finish(), ABT_sched_free(), ABT_sched_get_data(), ABT_sched_get_num_pools(), ABT_sched_get_pools(), ABT_sched_get_size(), ABT_sched_get_total_size(), ABT_sched_has_to_stop(), ABT_sched_set_data(), ABT_self_exit(), ABT_self_exit_to(), ABT_self_get_arg(), ABT_self_get_last_pool(), ABT_self_get_last_pool_id(), ABT_self_get_specific(), ABT_self_get_thread(), ABT_self_get_thread_func(), ABT_self_get_thread_id(), ABT_self_get_type(), ABT_self_get_unit(), ABT_self_get_xstream(), ABT_self_get_xstream_rank(), ABT_self_is_primary(), ABT_self_is_unnamed(), ABT_self_on_primary_xstream(), ABT_self_resume_exit_to(), ABT_self_resume_suspend_to(), ABT_self_resume_yield_to(), ABT_self_schedule(), ABT_self_set_arg(), ABT_self_set_associated_pool(), ABT_self_set_specific(), ABT_self_suspend(), ABT_self_suspend_to(), ABT_self_yield(), ABT_self_yield_to(), ABT_task_create(), ABT_task_create_on_xstream(), ABT_thread_attr_create(), ABT_thread_attr_free(), ABT_thread_attr_get_stack(), ABT_thread_attr_set_callback(), ABT_thread_attr_set_stack(), ABT_thread_create(), ABT_thread_create_on_xstream(), ABT_thread_create_to(), ABT_thread_revive(), ABT_thread_revive_to(), ABT_thread_set_callback(), ABT_tool_query_thread(), ABT_tool_register_thread_callback(), ABT_unit_get_thread(), ABT_unit_set_associated_pool(), ABT_xstream_barrier_create(), ABT_xstream_barrier_free(), ABT_xstream_barrier_wait(), ABT_xstream_cancel(), ABT_xstream_create(), ABT_xstream_create_basic(), ABT_xstream_create_with_rank(), ABT_xstream_exit(), ABT_xstream_free(), ABT_xstream_get_rank(), ABT_xstream_join(), ABT_xstream_revive(), ABT_xstream_self(), ABT_xstream_self_rank(), ABT_xstream_set_main_sched_basic(), ABT_xstream_set_rank(), pool_pop_thread_ex(), pool_pop_threads_ex(), pool_pop_wait_thread_ex(), pool_push_thread_ex(), and pool_push_threads_ex().
finailze_library()
static ABTU_ret_err int finailze_library (void) static
Definition at line 289 of file global.c.
Referenced by ABT_finalize().
init_library()
static ABTU_ret_err int init_library (void) static
Definition at line 196 of file global.c.
Referenced by ABT_init().
is_initialized_library()
static ABT_bool is_initialized_library (void) inline static
Definition at line 365 of file global.c.
Referenced by ABT_initialized(), and ABTI_initialized().
Variable Documentation
g_ABTI_init_lock
ABTD_spinlock g_ABTI_init_lock = ABTD_SPINLOCK_STATIC_INITIALIZER() static
Definition at line 24 of file global.c.
Referenced by ABT_finalize(), and ABT_init().
g_ABTI_initialized
ABTD_atomic_uint32 g_ABTI_initialized static
Initial value:
=
    ABTD_ATOMIC_UINT32_STATIC_INITIALIZER(0)
Definition at line 26 of file global.c.
Referenced by finailze_library(), init_library(), and is_initialized_library().
g_ABTI_num_inits
uint32_t g_ABTI_num_inits = 0 static
Definition at line 22 of file global.c.
Referenced by ABT_init(), and finailze_library().
gp_ABTI_global
ABTI_global* gp_ABTI_global = NULL
Definition at line 19 of file global.c.
Referenced by ABTI_global_get_global(), ABTI_global_get_global_or_null(), ABTI_global_set_global(), and ABTI_tool_event_thread().