ARGOBOTS: src/arch/abtd_ythread.c File Reference
abtd_ythread.c File Reference
#include "abti.h"
Functions
static void ythread_terminate (ABTI_xstream *p_local_xstream, ABTI_ythread *p_ythread)
void ABTD_ythread_func_wrapper (void *p_arg)
void ABTD_ythread_exit (ABTI_xstream *p_local_xstream, ABTI_ythread *p_ythread)
void ABTD_ythread_terminate_no_arg ()
void ABTD_ythread_cancel (ABTI_xstream *p_local_xstream, ABTI_ythread *p_ythread)
void ABTD_ythread_print_context (ABTI_ythread *p_ythread, FILE *p_os, int indent)
Function Documentation
ABTD_ythread_cancel()
void ABTD_ythread_cancel (ABTI_xstream * p_local_xstream, ABTI_ythread * p_ythread)
Definition at line 113 of file abtd_ythread.c.
Referenced by xstream_schedule_ythread().
ABTD_ythread_exit()
void ABTD_ythread_exit (ABTI_xstream * p_local_xstream, ABTI_ythread * p_ythread)
Definition at line 30 of file abtd_ythread.c.
Referenced by ABTI_ythread_exit().
ABTD_ythread_func_wrapper()
void ABTD_ythread_func_wrapper (void * p_arg)
Definition at line 11 of file abtd_ythread.c.
Referenced by ABTD_ythread_context_arm_ythread(), and ABTD_ythread_context_create().
ABTD_ythread_print_context()
void ABTD_ythread_print_context (ABTI_ythread * p_ythread, FILE * p_os, int indent)
Definition at line 148 of file abtd_ythread.c.
Referenced by ABTI_ythread_print_stack().
ABTD_ythread_terminate_no_arg()
void ABTD_ythread_terminate_no_arg ()
Definition at line 100 of file abtd_ythread.c.
Referenced by ABTD_ythread_context_dynamic_promote_ythread().
ythread_terminate()
static void ythread_terminate (ABTI_xstream * p_local_xstream, ABTI_ythread * p_ythread) inline static
Definition at line 35 of file abtd_ythread.c.
Referenced by ABTD_ythread_exit(), ABTD_ythread_func_wrapper(), and ABTD_ythread_terminate_no_arg().