ARGOBOTS: src/mem/malloc.c File Reference
malloc.c File Reference
#include "abti.h"
Functions
ABTU_ret_err int ABTI_mem_init (ABTI_global *p_global)
ABTU_ret_err int ABTI_mem_init_local (ABTI_global *p_global, ABTI_xstream *p_local_xstream)
void ABTI_mem_finalize (ABTI_global *p_global)
void ABTI_mem_finalize_local (ABTI_xstream *p_local_xstream)
Function Documentation
ABTI_mem_finalize()
void ABTI_mem_finalize (ABTI_global * p_global)
Definition at line 192 of file malloc.c.
Referenced by finailze_library(), and init_library().
ABTI_mem_finalize_local()
void ABTI_mem_finalize_local (ABTI_xstream * p_local_xstream)
Definition at line 196 of file malloc.c.
Referenced by xstream_create().
ABTI_mem_init()
ABTU_ret_err int ABTI_mem_init (ABTI_global * p_global)
Definition at line 181 of file malloc.c.
Referenced by init_library().
ABTI_mem_init_local()
ABTU_ret_err int ABTI_mem_init_local (ABTI_global * p_global, ABTI_xstream * p_local_xstream)
Definition at line 186 of file malloc.c.
Referenced by xstream_create().